= weechat(1)
:doctype: manpage
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: pl
// TRANSLATION MISSING
:man manual: WeeChat Manual
:man source: WeeChat {revnumber}

== NAZWA

weechat - rozszerzalny klient rozmów

== SKŁADNIA

[verse]
*weechat* [-a|--no-connect] [-d|--dir <ścieżka>] [-p|--no-plugin] [-r|--run-command <komenda>] [-s|--no-script] [--upgrade] [wtyczka:opcja...]
*weechat* [-c|--colors]
*weechat* [-h|--help]
*weechat* [-l|--license]
*weechat* [-v|--version]

== OPIS

WeeChat (Wee Enhanced Environment for Chat) to darmowy klient rozmów, szybki
i lekki, przeznaczony dla wielu systemów operacyjnych.
Posiada dużo opcji konfiguracyjnych i dodatkowych wtyczek.

== OPCJE

include::cmdline_options.pl.asciidoc[]

== OPCJE WTYCZEK

Kompletna dokumentacja na temat opcji wtyczek dostępna jest
w https://weechat.org/doc[WeeChat user's guide].

Dzięki wtyczce irc możliwe jest połączenie z serwerami tymczasowymi za pomocą
URLi jak:

    irc[6][s]://[[nick][:hasło]@]serwer[:port][/#kanał1[,#kanał2...]]

Aby wejść na kanał IRC poświęcony WeeChat pod nickiem "mójnick":

    irc://mójnick@chat.freenode.net/#weechat

Adresy IPv6 mogą być otoczone nawiasami kwadratowymi, aby możliwe było podanie
numeru potyu po adresie, na przykład:

    irc://mójnick@[2001:db8:0:85a3::ac1f:8001]:6668/#test

== PLIKI

$HOME/.weechat/weechat.conf::
    główny plik konfiguracyjny WeeChat

$HOME/.weechat/plugins.conf::
    plik konfiguracyjny wtyczek

$HOME/.weechat/sec.conf::
    plik konfiguracyjny z zabezpieczonymi danymi

$HOME/.weechat/alias.conf::
    plik konfiguracyjny wtyczki _alias_

$HOME/.weechat/aspell.conf::
    plik konfiguracyjny wtyczki _aspell_

$HOME/.weechat/charset.conf::
    plik konfiguracyjny wtyczki _charset_

$HOME/.weechat/exec.conf::
    plik konfiguracyjny wtyczki _exec_

$HOME/.weechat/irc.conf::
    plik konfiguracyjny wtyczki _irc_

$HOME/.weechat/logger.conf::
    plik konfiguracyjny wtyczki _logger_

$HOME/.weechat/relay.conf::
    plik konfiguracyjny wtyczki _relay_

$HOME/.weechat/script.conf::
    plik konfiguracyjny wtyczki _script_

$HOME/.weechat/trigger.conf::
    plik konfiguracyjny wtyczki _trigger_

$HOME/.weechat/xfer.conf::
    plik konfiguracyjny wtyczki _xfer_

$HOME/.weechat/weechat.log::
    plik z logami WeeChat

== AUTORZY

Autorem tej strony pomocy {author}.

Tłumaczenie Krzysztof Korościk.

== PRAWA AUTORSKIE

WeeChat jest tworzony przez Sébastien Helleu i społeczność (pełna lista dostępna
jest w pliku AUTHORS).

Copyright (C) 2003-2016 {author}

WeeChat is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

Pełna licencja znajduje się w pliku COPYING.

Strona www: https://weechat.org/

== WSPARCIE / ZGŁASZANIE BŁĘDÓW

W celu uzyskania pomocy, lub zgłoszenia błędu zajrzyj na: https://weechat.org/dev/support
