= WeeChat FAQ (Często zadawane pytania)
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:toc:
:toc-title: Spis treści


[NOTE]
Ten dokument jest napisany dla WeeChat w wersji ≥ 0.3.0, ale powinien być używany
dla najnowszej stabilnej wersji.


[[general]]
== Ogólne

[[weechat_name]]
=== Skąd się wzięła nazwa "WeeChat"?

"Wee" to akronim rekursywny oznaczającym "Wee Enhanced Environment".
Stąd kompletna nazwa to "Wee Enhanced Environment for Chat".

"Wee" oznacza również "bardzo mały" (tak jest jeszcze inne znaczenie, ale nie
pasuje ono do WeeChat!).

[[why_choose_weechat]]
=== Dlaczego wybrać WeeChat? X-Chat i Irssi są takie dobre...

Ponieważ Weechat jest bardzo lekki i posiada innowacyjne funkcje.

Więcej informacji na stronie: http://weechat.org/about/features

[[compilation_install]]
== Kompilacja / instalacja

[[gui]]
=== Słyszałem o wielu GUI dla WeeChat. Jak mogę je skompilować/użyć?

Dostępne są zdalne interfejsy, linki można znaleźć na stronie z cechami:
http://weechat.org/about/features

[[compile_git]]
=== Nie mogę skompilować WeeChat po sklonowaniu repozytorium git, dlaczego?

Zalecaną metodą kompilacji WeeChat jest użycie cmake.

Jeśli kompilujesz używając autotools (nie cmake), upewnij się, że posiadasz
najnowszą wersję autoconf i automake.

Innym sposobem jest zainstalowanie "paczki deweloperskiej", która wymaga mniej
zależności. Ten pakiet jest budowany prawie codziennie z użyciem repozytorium
git. Ten pakiet może odpowiadać dokładnie wersji z gita i jest mniej wygodny
przy aktualizowaniu jak klonowanie z gita.

// TRANSLATION MISSING
[[compile_osx]]
=== How can I install WeeChat on OS X?

// TRANSLATION MISSING
It is recommended to use http://brew.sh/[Homebrew], you can get help with:

----
brew info weechat
----

// TRANSLATION MISSING
You can install WeeChat with this command:

----
brew install weechat --with-python --with-perl
----

[[lost]]
=== Uruchomiłem WeeChat, ale czuję się zagubiony, co robić?

Dla pomocy wpisz `/help`. Aby uzyskać pomoc dla komendy wpisz `/help komenda`.
Klawisze i komendy są wypisane w dokumentacji.

Nowym użytkownikom zaleca się przeczytanie quickstart (szybki start):
http://weechat.org/doc

[[display]]
== Wyświetlanie

[[charset]]
=== Nie widzę niektórych znaków diakrytycznych, co mogę zrobić?

Jest to częsty problem, przeczytaj i sprawdź *WSZYSTKIE* poniższe rozwiązania:

* sprawdź czy weechat jest zlinkowany z libncursesw (uwaga: wymagane na
  większości dystrybucji ale nie wszystkich): `ldd /ścieżka/do/weechat`
* sprawdź czy wtyczka "Charset" jest załadowana za pomocą komendy `/plugin`
  (jeśli nie jest, to najprawdopodobniej potrzebujesz pakietu "weechat-plugins")
* sprawdź wyjście komendy `/charset` (w głównym buforze). Powinieneś zobaczyć
  'ISO-XXXXXX' lub 'UTF-8' dla kodowania terminala. Jeśli widzisz 'ANSI_X3.4-1968'
  lub inne wartości, twoje ustawienie dla locale najprawdopodobniej jest złe
  (napraw swoje $LANG).
* ustaw globalną wartość dekodowania, na przykład:
  `/set charset.default.decode "ISO-8859-2"`
* jeśli korzystasz z UTF-8:
** sprawdź czy twój terminal jest przystosowany dla UTF-8 (zalecanym terminalem
   dla UTF-8 jest rxvt-unicode)
** jeśli korzystasz ze screena, sprawdź czy jest uruchomiony z trybem UTF-8
   ("`defutf8 on`" w ~/.screenrc lub `screen -U` uruchamiając screena)
* sprawdź czy opcja 'weechat.look.eat_newline_glitch' jest wyłączona (ta opcja
  może powodować błędy wyświetlania)

[NOTE]
UTF-8 jest zalecany dla WeeChat. Jeśli korzystasz z lokalizacji ISO lub innych,
sprawdź czy *wszystkie* twoje ustawienia (terminal, screen, ..) są ISO,
a *nie* UTF-8.

[[bars_background]]
=== Paski jak tytuł i status nie są filtrowane, kolor tła zatrzymuje się po tekście, czemu?

Może to być spowodowane złą wartością zmiennej środowiskowej TERM (spójrz na
wynik `echo $TERM` w terminalu).

W zależności, gdzie uruchamiasz WeeChat, powinieneś uzyskać:

* jeśli WeeChat jest uruchomiony lokalnie lub na zdalnej maszynie bez screena,
  zależy od używanego terminala: 'xterm', 'xterm-256color', 'rxvt-unicode',
  'rxvt-256color', ...
* jeśli WeeChat działa w screenie, należy użyć 'screen' lub 'screen-256color'.

W razie potrzeby, popraw zmienna TERM: `export TERM="xxx"`.

[[screen_weird_chars]]
=== Podczas używania WeeChat pod screenem/tmuxem pojawiają mi się dziwne, losowe znaki, jak to naprawić?

Może to być spowodowane przez złą wartość zmiennej TERM w swojej powłoce (spójrz
na wynik `echo $TERM` w swoim terminalu, *poza screenem/tmuxem*).

Na przykład, 'xterm-color' może wyświetlać takie dziwne znaki, możesz użyć 'xterm',
który działa dobrze (jak wiele innych wartości).

W razie potrzeby, popraw zmienna TERM: `export TERM="xxx"`.

[[osx_display_broken]]
=== Skompilowałem WeeChat pod OS X i wszędzie na ekranie widzę "(null)", co jest nie tak?

Jeśli samodzielnie skompilowałeś ncursesw, spróbuj użyć domyślnej wersji (dostarczanej
z systemem).

Ponadto, pod OS X, zaleca się instalowanie WeeChat za pomocą managera pakietów
Homebrew.

[[buffer_vs_window]]
=== Słyszałem o "buforach" i "oknach", jaka jest między nimi różnica?

'bufor' jest określany przez numer, nazwę, wyświetlane linie (i trochę innych
danych).

'okno' jest to obszar ekranu wyświetlający bufor. Możliwe jest podzielenie
ekranu na wiele okien.

Każde okno wyświetla jeden bufor. Bufor może być ukryty (nie wyświetlany przez
okno) lub wyświetlany w jednym lub więcej oknach.

[[buffers_list]]
=== Jak wyświetlić listę z buforami po lewej stronie?

Użyj skryptu 'buffers.pl':

----
/script install buffers.pl
----

W celu ograniczenia rozmiaru paska:

----
/set weechat.bar.buffers.size_max 15
----

Żeby przenieść pasek na dół:

----
/set weechat.bar.buffers.position bottom
----

[[customize_prefix]]
=== Jak mogę ograniczyć długość wyświetlanych nicków lub usunąć wyrównanie w oknie rozmowy?

W celu ograniczenia długości nicków w oknie rozmowy:

----
/set weechat.look.prefix_align_max 15
----

Żeby usunąć wyrównanie nicków:

----
/set weechat.look.prefix_align none
----

[[input_bar_size]]
=== Jak używać linii poleceń z więcej niż jednym wierszem?

Opcja 'size' paska wprowadzania może zostać ustawiona na wartość wyższą niż 1
(dla ustalonej wartości, domyślny rozmiar to 1) lub 0 dla dynamicznego rozmiaru,
następnie opcja 'size_max' ustali maksymalny rozmiar (0 = brak limitu).

Przykład dynamicznego rozmiaru:

----
/set weechat.bar.input.size 0
----

Maksymalny rozmiar równy 2:

----
/set weechat.bar.input.size_max 2
----

[[one_input_root_bar]]
=== Czy jest możliwe wyświetlanie tylko jednego paska wejściowego dla wszystkich okien (po podzieleniu)?

Tak, należy stworzyć pasek typu "root" (z elementem mówiącym, w którym oknie
aktualnie jesteśmy), następnie usunąć obecny pasek wejściowy.

Na przykład:

----
/bar add rootinput root bottom 1 0 [buffer_name]+[input_prompt]+(away),[input_search],[input_paste],input_text
/bar del input
----

Jeśli kiedyś przestanie ci to odpowiadać, po prostu usuń ten pasek, WeeChat
automatycznie stworzy nowy pasek "input" jeśli element "input_text" nie zostanie
użyty w żadnym z pasków:

----
/bar del rootinput
----

[[terminal_copy_paste]]
=== Jak mogę kopiować/wklejać tekst bez wklejania listy nicków?

W WeeChat od wersji ≥ 1.0, możesz użyć trybu niesformatowanego wyświetlania (domyślnie: key[alt-l]).

Możesz użyć terminala z prostokątnym zaznaczaniem (jak rxvt-unicode,
konsole, gnome-terminal, ...). Klawisze to zazwyczaj key[ctrl-]key[alt-] zaznaczenie myszką.

Innym rozwiązaniem jest przesunięcie listy nicków na górę lub dół, na przykład:

----
/set weechat.bar.nicklist.position top
----

[[urls]]
=== Jak mogę kliknąć na długi URL (dłuższy niż linia)?

W WeeChat od wersji ≥ 1.0, możesz użyć trybu niesformatowanego wyświetlania (domyślnie: key[alt-l]).

Domyślnie WeeChat wyświetla czas i przedrostki dla każdej linii i opcjonalne paski
dookoła obszaru rozmowy. Aby usprawnić klikanie w urle można przesunąć listę nicków
na górę oraz usunąć wyrównanie nicków:

----
/set weechat.bar.nicklist.position top
/set weechat.look.prefix_align none
/set weechat.look.align_end_of_lines time
----

W WeeChat ≥ 0.3.6 można włączyć opcję "eat_newline_glitch", dzięki której znaki
nowej linii nie są dodawane na końcu każdej wyświetlanej linii (nie zakłóci to
zaznaczania urli):

----
/set weechat.look.eat_newline_glitch on
----

[IMPORTANT]
Ta opcja może spowodować pojawienie się błędów. Jeśli doświadczysz takich problemów
wyłącz tą opcję.

Innym rozwiązaniem jest użycie skryptu:

----
/script search url
----

[[change_locale_without_quit]]
=== Chcę zmienić język komunikatów wyświetlanych przez WeeChat, ale bez jego zamykania, czy jest to możliwe?

Tak, dla wersji WeeChat ≥ 1.0:

----
/set env LANG pl_PL.UTF-8
/upgrade
----

Dla starszych wersji WeeChat:

----
/script install shell.py
/shell setenv LANG=pl_PL.UTF-8
/upgrade
----

[[use_256_colors]]
=== Jak mogę użyć 256 kolorów w WeeChat?

256 kolorów jest wspierane tylko w WeeChat ≥ 0.3.4.

Najpierw należy sprawdzić czy wartość zmiennej środowiskowej 'TERM' jest poprawna,\
zalecane wartości to:

* w screenie: 'screen-256color'
* poza screenem: 'xterm-256color', 'rxvt-256color', 'putty-256color',...

[NOTE]
Może okazać się konieczne zainstalowanie pakietu "ncurses-term" w celu użycia
tych wartości w zmiennej 'TERM'.

Jeśli używasz screena, możesz dodać to do swojego '~/.screenrc':

----
term screen-256color
----

Jeśli twoja zmienna 'TERM' posiada złą wartość i WeeChat jest już uruchomiony,
możesz zmienić ją za pomocą tych dwóch komend (dla wersji Weechat ≥ 1.0):

----
/set env TERM screen-256color
/upgrade
----

Dla wersji 0.3.4, musisz użyć komendy `/color` w celu dodania nowych kolorów.

Dla wersji ≥ 0.3.5, można używać dowolnego numeru koloru w opcjach (opcjonalnie:
można stworzyć alias dla koloru za pomocą komendy `/color`).

Więcej informacji na temat zarządzania kolorami można uzyskać w poradniku użytkownika.

[[search_text]]
=== Jak mogę wyszukać tekst w buforze (jak za pomocą /lastlog w irssi)?

Domyślny skrót klawiszowy to key[ctrl-r] (komenda: `/input search_text`).

Poruszanie się między podświetleniami: key[alt-p] / key[alt-n].

Po więcej informacji zajrzyj do poradnika użytkownika (domyślne skróty klawiszowe).

[[terminal_focus]]
=== Jak mogę wykonywać komendy, kiedy terminal stanie się/przestanie być aktywny?

Musisz włączyć obsługę tego zdarzenia za pomocą specjalnego kodu wysyłanego do terminala.

*Ważne*:

* Obecnie *tylko* 'xterm' wspiera tą funkcję.
* *Nie* działa to pod screen/tmux.

Żeby wysłać kod podczas uruchamiania WeeChat:

----
/set weechat.startup.command_after_plugins "/print -stdout \033[?1004h\n"
----

Następnie przypisz dwie kombinacje klawiszy dla stanu aktywności (zamień komendy
`/print` własnymi komendami:

----
/key bind meta2-I /print -core focus
/key bind meta2-O /print -core unfocus
----

[[key_bindings]]
== Przypisania klawiszy

[[meta_keys]]
=== Niektóre skróty klawiszowe (alt + klawisz) nie działają, dlaczego?

Jeśli używasz terminali jak xterm lub uxterm, niektóre skróty domyślnie
nie będą działać. Możesz dodać następujące linie do pliku '~/.Xresources':

* dla xterm:
----
XTerm*metaSendsEscape: true
----
* dla uxterm:
----
UXTerm*metaSendsEscape: true
----

Następnie przeładować zasoby (`xrdb -override ~/.Xresources`) lub zrestartować X.

[[customize_key_bindings]]
=== Jak mogę zmienić przypisania klawiszy?

Przypisania klawiszy można dostosować za pomocą komendy `/key`.

Domyślnie key[alt-k] pozwala pobrać kod klawiszy i umieścić go w wierszu
poleceń.

[[jump_to_buffer_11_or_higher]]
=== Jakim skrótem można przejść do buforu 11 (lub o większym numerze)?

Skrót to key[alt-j] i dwie cyfry, na przykład key[alt-j], key[1], key[1]
przejdzie do buforu 11.

Można również samemu stworzyć skrót, na przykład:

----
/key bind meta-q /buffer *11
----

Lista domyślnych skrótów znajduje się w poradniku użytkownika.

[[global_history]]
=== Jak używać globalnej historii (zamiast historii buforu) za pomocą strzałek góra/dół?

Możesz przypisać strzałki w górę i dół do globalnej historii (domyślnie dla
globalnej historii przypisane są klawisze key[ctrl-↑] oraz key[ctrl-↓]).

Przykład:

----
/key bind meta2-A /input history_global_previous
/key bind meta2-B /input history_global_next
----

[NOTE]
Klawisze "meta2-A" i "meta2-B" mogą być inne dla twojego terminala. W celu
znalezienia ich kodów wciśnij key[alt-k] następnie przycisk (góra lub dół).

[[mouse]]
== Obsługa myszy

[[mouse_not_working]]
=== Obsługa myszy w ogóle nie działa, co mogę zrobić?

Mysz nie jest obsługiwana w WeeChat ≥ 0.3.6.

Na samym początku należy włączyć obsługę myszy:

----
/mouse enable
----

Jeśli to nie pomogło należy sprawdzić wartość zmiennej TERM w swojej powłoce
(wynik komendy `echo $TERM` w swoim terminalu).
W zależności od używanego terminfo, mysz może nie być wspierana.

Możesz sprawdzić wsparcie myszy w terminalu:

----
$ printf '\033[?1002h'
----

Następnie kliknij pierwszy znak w terminalu (górny lewy róg). Powinieneś zobaczyć " !!#!!".

Aby wyłączyć wsparcie dla myszy w terminalu:

----
$ printf '\033[?1002l'
----

[[mouse_coords]]
=== Mysz nic nie robi dla X lub Y większych od 94 (lub 222), dlaczego?

Niektóre terminale wysyłają tylko znaki ISO dla położenia myszy, dlatego nie
działa to dla X/Y większych dla 94 (lub 222).

Powinieneś użyć terminala wspierającego położenia UTF-8 dla myszy, jak
rxvt-unicode.

[[mouse_select_paste]]
=== Jak mogę zaznaczyć lub wkleić tekst w terminalu z włączoną obsługa myszy w WeeChat?

Kiedy obsługa myszy jest włączona w WeeChat, można użyć modyfikatora key[shift]
do zaznaczania lub kliknać w terminalu, tak jak w przypadku wyłączonej obsługi
myszy (w niektórych terminalach jak iTerm należy użyć key[alt] zamiast
key[shift]).

[[irc]]
== IRC

[[irc_ssl_connection]]
=== Mam problemy podczas połączenia z serwerem używającym SSL, co mogę zrobić?

Jeśli używasz Mac OS X, musisz zainstalować `curl-ca-bundle` i ustawić ścieżkę
do certyfikatów w WeeChat:

----
/set weechat.network.gnutls_ca_file "/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt"
----

Jeśli widzisz błędy gnutls, możesz użyć innej wielkości klucza
Diffie-Hellman (domyślnie 2048):

----
/set irc.server.freenode.ssl_dhkey_size 1024
----

Jeśli widzisz błędy związanie z certyfikatami, możesz wyłączyć opcję "ssl_verify"
(należy jednak uważać, ponieważ połączenie będzie mniej bezpieczne):

----
/set irc.server.freenode.ssl_verify off
----

[[irc_ssl_handshake_error]]
=== Podczas łączenia się z serwerem poprzez SSL widzę tylko błąd "TLS handshake failed", co mogę zrobić?

Możesz spróbować innego ciągu priorytetu (tylko WeeChat ≥ 0.3.5), zamień "xxx"
nazwą serwera:

----
/set irc.server.xxx.ssl_priorities "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.0:+VERS-SSL3.0:%COMPAT"
----

[[irc_ssl_freenode]]
=== Jak mogę połączyć się z serwerem freenode używając SSL?

Ustaw opcję 'weechat.network.gnutls_ca_file' do pliku z certyfikatami:

----
/set weechat.network.gnutls_ca_file "/etc/ssl/certs/ca-certificates.crt"
----

[NOTE]
Należy sprawdzić czy plik znajduje się w systemie (zazwyczaj dostarczany
przez pakiet "ca-certificates").

Ustaw port serwera, SSL, dhkey_size, następnie się połącz:
----
/set irc.server.freenode.addresses "chat.freenode.net/7000"
/set irc.server.freenode.ssl on
/set irc.server.freenode.ssl_dhkey_size 1024
/connect freenode
----

[[irc_oauth]]
=== Jak połączyć się z serwerem wymagającym "oauth"?

Niektóre serwery jak 'twitch' wymagają oauth do połączenia.

Oauth to po prostu hasło w postaci "oauth:hasło".

W celu dodania takiego serwera i połączenia się z nim należ wykonać następujące
polecenia (należy zastąpić nazwę i adres odpowiednimi wartościami):

----
/server add nazwa irc.server.org -password=oauth:hasło
/connect nazwa
----

[[irc_sasl]]
=== Jak mogę się zidentyfikować przed wejściem na kanały?

Jeśli serwer wspiera SASL, możesz użyć tego zamiast wysyłać komendę do nickserva,
na przykład:

----
/set irc.server_default.sasl_mechanism dh-blowfish
/set irc.server.freenode.sasl_username "nick"
/set irc.server.freenode.sasl_password "xxxxxxx"
----

Jeśli serwer nie wspiera SASL, możesz dodać odstęp pomiędzy komendą a wejściem
na kanały):

----
/set irc.server.freenode.command_delay 5
----

[[ignore_vs_filter]]
=== Jaka jest różnica między komendami/ignore i /filter ?

Komenda `/ignore` jest komendą IRC, zatem odnosi się tylko do buforów IRC
(serwery i kanały).
Pozwala ignorować niektóre nicki lub hosty użytkowników serwera lub kanału
(komendy nie stosuje się do treści wiadomości).
Pasujące wiadomości są usuwane przez wtyczkę IRC przed wyświetleniem (nigdy
ich nie zobaczysz).

Komenda `/filter` jest komenda rdzenia, zatem odnosi się do dowolnego bufora.
Pozwala filtrować niektóre linie w buforach za pomocą tagów lub wyrażeń
regularnych dla przedrostków i zawartości linii.
Filtrowane linie są tylko ukrywane, nie usuwane, można je zobaczyć wyłączając
filtry (domyślnie key[alt-=] zmienia stan filtrów).

[[filter_irc_join_part_quit]]
=== Jak mogę filtrować wiadomości o wejściu/opuszczeniu/wyjściu na kanałach IRC?

Za pomocą inteligentnych filtrów (zachowuje wejścia/opuszczenia/wyjścia od osób
piszących niedawno):

----
/set irc.look.smart_filter on
/filter add irc_smart * irc_smart_filter *
----

Za pomocą globalnego filtru (ukrywa *wszystkie* wejścia/opuszczenia/wyjścia):

----
/filter add joinquit * irc_join,irc_part,irc_quit *
----

[NOTE]
Więcej informacji: `/help filter` i `/help irc.look.smart_filter`

[[filter_irc_join_channel_messages]]
=== Jak mogę filtrować wyświetlane wiadomości podczas wejścia na kanał IRC?

W wersjach WeeChat ≥ 0.4.1, możesz wybrać to, jakie wiadomości są wyświetlane
a jakie nie podczas wchodzenia na kanał, za pomocą opcji 'irc.look.display_join_message'
(więcej informacji można znaleźć wykonując `/help irc.look.display_join_message`).

W celu ukrycia wiadomości (ale zachowując je w buforze), możesz je filtrować
używając tagu (na przykład 'irc_329' dla daty utworzenia kanału). zobacz
`/help filter` w celu uzyskania pomocy z filtrami.

[[filter_voice_messages]]
=== Jak mogę filtrować informacje o przyznaniu voice (np na serwerze Bitlbee)?

Filtrowanie wiadomości o przyznaniu voice nie jest proste, ponieważ może on
zostać nadany wraz z innymi atrybutami w jednej wiadomości IRC.

Zapewne chcesz to zrobić, ponieważ Bitlbee używa voice do wskazania nieobecnych
użytkowników, oraz jesteś zasypywany takimi wiadomościami. Możesz to zmienić oraz
pozwolić WeeChat używać specjalnego koloru dla nieobecnych nicków.

Dla Bitlbee ≥ 3, należy wykonać na kanale '&bitlbee':

----
channel set show_users online,away
----

Dla starszych wersji Bitlbee, należy wykonać na kanale '&bitlbee':

----
set away_devoice false
----

Aby dowiedzieć się jak sprawdzić nieobecność w WeeChat, spójrz na pytanie o
<<color_away_nicks,nieobecnych osobach>>.

Jeśli napewno chcesz filtrować wiadomości o statusie voice, możesz użyć tej komendy,
nie jest ona jednak doskonała (działa tylko jeśli pierwszy z modyfikowanych trybów to voice):

----
/filter add hidevoices * irc_mode (\+|\-)v
----

[[color_away_nicks]]
=== Jak mogę zobaczyć kto jest aktualnie nieobecny ?

Należy ustawić opcję 'irc.server_default.away_check' na wartość większą od zera
(minuty pomiędzy sprawdzaniem czy nick jest nieobecny).

Możesz ustawić opcję 'irc.server_default.away_check_max_nicks' w celu ustalenia
sprawdzania nieobecności dla małych kanałów.

Na przykład, aby sprawdzać nieobecność nicków co 5, dla kanałów z maksymalnie 25
osobami:

----
/set irc.server_default.away_check 5
/set irc.server_default.away_check_max_nicks 25
----

[NOTE]
Dla WeeChat ≤ 0.3.3, opcje te to 'irc.network.away_check' oraz
'irc.network.away_check_max_nicks'.

[[highlight_notification]]
=== Jak mogę zostać powiadomiony, jeśli ktoś będzie chciał przyciągnąć moją uwagę na kanale?

// TRANSLATION MISSING
With WeeChat ≥ 1.0, there is a default trigger "beep" which sends a 'BEL' to
the terminal on a highlight or private message. Thus you can configure your
terminal (or multiplexer like screen/tmux) to run a command or play a sound
when a 'BEL' occurs.

// TRANSLATION MISSING
Or you can add a command in "beep" trigger:

----
/set trigger.trigger.beep.command "/print -beep;/exec -bg /ścieżka/do/komendy argumenty"
----

// TRANSLATION MISSING
With an older WeeChat, you can use a script like 'beep.pl' or 'launcher.pl'.

Dla 'launcher.pl', należ przeprowadzić konfigurację:

----
/set plugins.var.perl.launcher.signal.weechat_highlight "/ścieżka/do/komendy argumenty"
----

Inne podobne skrypty:

----
/script search notify
----

[[irc_target_buffer]]
=== Jak mogę zmienić docelowy bufor dla komendy w połączonym buforze (jak bufor z serwerami)?

Domyślna kombinacja to key[ctrl-x] (komenda: `/input switch_active_buffer`).

[[plugins_scripts]]
== Pluginy / skrypty

[[openbsd_plugins]]
=== Używam OpenBSD, WeeChat nie ładuje żadnych pluginów, co jest nie tak?

Pod  OpenBSD, nazwy wtyczek kończą się ".so.0.0" (".so" dla Linuksa).

Musisz ustawić:

----
/set weechat.plugin.extension ".so.0.0"
/plugin autoload
----

[[install_scripts]]
=== Jak mogę instalować skrypty? Czy są one kompatybilne z innymi klientami IRC?

Możesz użyć komendy `/script` do instalowania i zarządzania skryptami
(zobacz `/help script` po więcej informacji).

Skrypty nie są kompatybilne z innymi klientami IRC.

[[settings]]
== Ustawienia

[[memory_usage]]
=== Jak mogę zmusić WeeChat do zużywania mniejszej ilości pamięci?

W celu zmniejszenia używanej pamięci możesz zastosować się do poniższych rad:

* używać najnowsze stabilnej wersji (powinna mieć mniej wycieków pamięci
  niż starsze wersje)
* nie ładuj nieużywanych pluginów, np: aspell, fifo, logger, perl, python,
  ruby, lua, tcl, guile, xfer (używana do DCC)
* ładować tylko naprawdę używane skrypty
* nie ładuj certyfikatów jeśli SSL *NIE* jest używany: ustaw pusty ciąg w opcji
  'weechat.network.gnutls_ca_file'
* zmniejsz wartość dla opcji 'weechat.history.max_buffer_lines_number' lub ustaw
  wartość opcji 'weechat.history.max_buffer_lines_minutes'
* zmniejszyć wartość opcji 'weechat.history.max_commands'

[[cpu_usage]]
=== Jak mogę zmusić WeeChat do zużywania mniejszej mocy CPU?

Możesz skorzystać z tych samych porad jak dla  <<memory_usage,memory>>, oraz tych:

* schowaj pasek "nicklist": `/bar hide nicklist`
* usuń wyświetlanie sekund w czasie na pasku statusu:
  `/set weechat.look.item_time_format "%H:%M"` (domyślna wartość)
* ustaw zmienną 'TZ' (na przykład: `export TZ="Europe/Warsaw"`), w celu zmniejszenia
  częstotliwości czytania pliku '/etc/localtime'

[[development]]
== Rozwój

[[bug_task_patch]]
=== Jak zgłaszać błędy, prosić o nowe możliwości lub wysyłać patche?

Zobacz: http://weechat.org/dev/support

[[gdb_error_threads]]
=== Kiedy uruchamiam WeeChat pod gdb dostaję komunikat o wątkach, co mogę z tym zrobić?

Podczas uruchamiania WeeChat pod gdb, można spotkać się z takim błędem:

----
$ gdb /scieżka/do/weechat
(gdb) run
[Thread debugging using libthread_db enabled]
Cannot find new threads: generic error
----

Żeby to naprawić, można użyć takiej komendy(należy zmienić ścieżki do libpthread oraz
WeeChat na właściwe dla naszego systemu):

----
$ LD_PRELOAD=/lib/libpthread.so.0 gdb /ścieżka/do/weechat
(gdb) run
----

[[supported_os]]
=== Jaka jest lista platform wspieranych przez WeeChat? Czy będzie przeportowany na inne systemy operacyjne?

Pełną listę można znaleźć na stronie: http://weechat.org/download

Robimy co w naszej mocy, aby WeeChat działał na tylu platformach ile to tylko
możliwe. Mile widziana jest pomoc w testowaniu dla systemów, których nie mamy.

[[help_developers]]
=== Chcę pomóc programistą WeeChat. Co mogę zrobić?

Jest wiele zadań do zrobienia (testowanie, kod, dokumentacja, ...)

Skontaktuj się z nami na IRC lub mailowo, szczegóły:
http://weechat.org/dev/support

[[donate]]
=== Czy mogę dać pieniądze albo inne rzeczy deweloperom WeeChat?

Tak możesz dać nam pieniądze, aby wspomóc rozwój.
Szczegóły na http://weechat.org/about/donate
