= weechat-headless(1)
:doctype: manpage
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: pl
:man manual: WeeChat Manual
:man source: WeeChat {revnumber}

== NAZWA

weechat-headless - rozszerzalny klient rozmów (wersja headless)

== SKŁADNIA

[verse]
*weechat-headless* [-a|--no-connect] [--daemon] [-d|--dir <path>] [-t|--temp-dir] [-p|--no-plugin] [-P|--plugins <wtyczki>] [-r|--run-command <komenda>] [-s|--no-script] [--upgrade] [wtyczka:opcja...]
*weechat-headless* [-c|--colors]
*weechat-headless* [-h|--help]
*weechat-headless* [-l|--license]
*weechat-headless* [-v|--version]

== OPIS

WeeChat (Wee Enhanced Environment for Chat) to darmowy klient rozmów, szybki
i lekki, przeznaczony dla wielu systemów operacyjnych.
Posiada dużo opcji konfiguracyjnych i dodatkowych wtyczek.

Komenda *weechat-headless* uruchamia WeeChat w trybie headless (bez interfejsu).
Może być używana do testów lub do uruchamiania WeeChat w trybie demona za pomocą
opcji "--daemon".

== OPCJE

include::cmdline_options.pl.adoc[]

== OPCJE WTYCZEK

include::man_plugin_options.pl.adoc[]

== PLIKI

include::man_files.pl.adoc[]

== Zobacz również

*weechat*(1)

== AUTORZY

Autorem tej strony pomocy {author}.

Tłumaczenie Krzysztof Korościk.

== PRAWA AUTORSKIE

include::man_copyright.pl.adoc[]

== WSPARCIE / ZGŁASZANIE BŁĘDÓW

W celu uzyskania pomocy, lub zgłoszenia błędu zajrzyj na: https://weechat.org/about/support
