= WeeChat FAQ (Frequently Asked Questions)
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: ru
:toc: left
:toclevels: 2
:sectnums:
:sectnumlevels: 2
:docinfo1:

Переводчики:

* German Youdin <hozztie@gmail.com>, 2021

Этот документ написан для WeeChat версий ≥ 0.3.0, но желательно использовать
с последней стабильной версией WeeChat.

toc::[]


[[general]]
== Общие

[[weechat_name]]
=== Откуда произошло название "WeeChat"?

"Wee" - это рекурсивная аббревиатура, обозначающая "Wee Enhanced Environment". (Wee Улучшенная Среда)
Таким образом, полное название - "Wee Enhanced Environment for Chat".

"Wee" также означает "очень маленький" (и да, есть другое значение, но это не
относится к WeeChat!).

[[why_choose_weechat]]
=== Почему мне следует выбрать WeeChat? Ведь X-Chat и Irssi тоже хороши...

Потому что WeeChat очень легкий и обладает инновационными функциями.

Более подробная информация на странице функций WeeChat: https://weechat.org/about/features

[[compilation_install]]
== Компиляция / установка

[[gui]]
=== Я слышал о многих GUI для WeeChat. Как я могу их скомпилировать/использовать?

Доступны некоторые удаленные GUI, см. страницу удаленных интерфейсов:
https://weechat.org/about/interfaces

[[compile_git]]
=== Почему я не могу скомпилировать WeeChat после клонирования репозитория git?

Рекомендуемый способ компиляции WeeChat c
link:weechat_user.ru.html#compile_with_cmake[CMake].

Если вы компилируете с link:weechat_user.ru.html#compile_with_autotools[autotools]
(а не с CMake), убедитесь, что у вас установлена последняя версия autoconf и automake.

Другой способ - установить «пакет разработки», который требует меньше зависимостей.
Этот пакет собирается почти каждый день с использованием репозитория git. Обратите внимание,
что этот пакет может не точно соответствовать базе git и что он менее удобен,
чем клонирование git для установки обновлений.

[[compile_macos]]
=== Как установить WeeChat на macOS?

Рекомендуется использовать https://brew.sh/[Homebrew], вам может помочь команда:

----
brew info weechat
----

Вы можете установить WeeChat с помощью этой команды:

----
brew install weechat
----

[[lost]]
=== Я запустил WeeChat, но я запутался, что мне делать?

Для получения справки наберите `/help`. Чтобы получить справку о команде, введите `/help команда`.
link:weechat_user.ru.html#key_bindings[Клавиши] и
link:weechat_user.ru.html#commands_and_options[команды] перечислены в документации.

Новым пользователям рекомендуется прочитать
link:weechat_quickstart.ru.html[Краткое руководство по началу работы].

[[display]]
== Отображение

[[charset]]
=== Я не вижу некоторых символов с акцентами, что мне делать?

Это обычная проблема с множеством причин, пожалуйста, внимательно прочтите
и проверьте *ВСЕ* решения ниже.

* Убедитесь, что weechat слинкован с libncursesw (предупреждение: необходимо в большинстве
  дистрибутивов, но не во всех): `ldd /путь/к/weechat`.
* Убедитесь, что плагин "charset" загружен с помощью команды `/plugin` (если это не так,
  то вам, вероятно, понадобится пакет "weechat-plugins").
* Проверьте вывод команды `/charset` (в основном буфере). Вы должны увидеть
  _ISO-XXXXXX_ или _UTF-8_ для кодировки терминала. Если вы видите ANSI_X3.4-1968_ или
  другие значения, вероятно, кодировка в вашем терминале неверна. +
  Чтобы исправить вашу локаль, проверьте установленные локали с помощью `locale -a` и установите
  соответствующее значение в $LANG, например: `+export LANG=ru_RU.UTF-8+`.
* Установите глобальную кодировку для декодирования сообщений, например:
  `/set charset.default.decode "ISO-8859-15"`.
* Если вы используете локаль UTF-8:
** Убедитесь, что ваш терминал поддерживает UTF-8 (для UTF-8 рекомендуется использовать терминал
   rxvt-unicode).
** Если вы используете screen, убедитесь, что он работает в режиме UTF-8
   ("`defutf8 on`" в ~/.screenrc или `screen -U` для запуска screen).
* Проверьте, отключён ли параметр
  link:weechat_user.ru.html#option_weechat.look.eat_newline_glitch[_weechat.look.eat_newline_glitch_]
  (этот параметр может привести к ошибкам отображения).

[NOTE]
Для WeeChat рекомендуется использовать локаль UTF-8. Если вы используете ISO или другую
локаль, убедитесь, что *все* ваши настройки (терминал, экран, ..) соответствуют ISO,
а *не* UTF-8.

[[unicode_chars]]
=== Некоторые символы юникода отображаются в терминале, но не отображается в WeeChat, почему?

Это может быть вызвано ошибкой libc в функции _wcwidth_, которая должна быть исправлена
в glibc 2.22 (возможно, еще не доступна в вашем дистрибутиве).

Существует обходной путь использования фиксированной функции _wcwidth_:
https://blog.nytsoi.net/2015/05/04/emoji-support-for-weechat

См. этот отчет об ошибке для получения дополнительной информации:
https://github.com/weechat/weechat/issues/79

[[bars_background]]
=== Панели, такие как заголовок и статус, не заполнены полностью, почему?

Это может быть вызвано неправильным значением переменной TERM в вашей оболочке (посмотрите на
вывод `echo $TERM` в вашем терминале).

В зависимости от того, где вы запускаете WeeChat, у вас должно быть:

* Если WeeChat работает локально или на удаленной машине без screen или tmux, это
  зависит от используемого терминала: _xterm_, _xterm-256color_, _rxvt-unicode_,
  _rxvt-256color_ и т.д.
* Если WeeChat работает под управлением screen, у вас должен быть _screen_ или _screen-256color_.
* Если WeeChat работает под управлением tmux, у вас должны быть _tmux_, _tmux-256color_,
  _screen_ или _screen-256color_.

Если необходимо, исправьте вашу переменную TERM: `export TERM ="xxx"`.

[[screen_weird_chars]]
=== Когда я использую weechat под screen/tmux, у меня появляются странные случайные символы, как мне это исправить?

Это может быть вызвано неправильным значением переменной TERM в вашей оболочке (посмотрите на
вывод `echo $TERM` в вашем терминале, *вне screen/tmux*). +
Например, _xterm-color_ может отображать такие странные символы, вместо него вы можете использовать _xterm_,
что нормально (как и многие другие значения). +
Если необходимо, исправьте вашу переменную TERM: `export TERM ="xxx"`.

Если вы используете gnome-terminal, убедитесь, что для параметра
"Ambiguous-width characters" в меню Preferences/Profile/Compatibility
установлено значение `narrow`.

[[macos_display_broken]]
=== Я скомпилировал WeeChat под macOS и везде на экране вижу "(null)", что не так?

Если вы сами скомпилировали ncursesw, попробуйте использовать стандартный ncurses (который
поставляется с системой).

Кроме того, под macOS рекомендуется установить WeeChat с менеджером пакетов Homebrew.

[[buffer_vs_window]]
=== Я слышал про "буферы" и "окна", какая между ними разница?

_buffer_ состоит из чисел, имён, отображаемых строк (и некоторых других данных).

_window_ - это область экрана, в которой отображается буфер. Экран можно разделить
на несколько окон.

В каждом окне отображается один буфер или набор объединенных буферов.
Буфер может быть скрыт (не отображаться в окне) или отображаться в одном или нескольких окнах.

[[buffers_list]]
=== Как вывести список буферов слева?

В WeeChat ≥ 1.8, плагин link:weechat_user.ru.html#buflist_plugin[buflist]
загружен и включен по умолчанию.

В более старой версии вы можете установить скрипт _buffers.pl_:

----
/script install buffers.pl
----

Чтобы ограничить размер панели (замените "buflist" на "buffers", если вы используете скрипт
_buffers.pl_):

----
/set weechat.bar.buflist.size_max 15
----

Чтобы переместить панель вниз:

----
/set weechat.bar.buflist.position bottom
----

Прокрутка панели: если мышь включена (клавиша: kbd:[Alt+m]), вы можете прокручивать
панель колесиком мыши.

Клавиши по умолчанию для прокрутки панели _buflist_: kbd:[F1] (или kbd:[Ctrl+F1]), kbd:[F2]
(или kbd:[Ctrl+F2]), kbd:[Alt+F1] и kbd:[Alt+F2].

Для скрипта _buffers.pl_ вы можете определить клавиши, аналогичные существующим клавишам
для прокрутки никлиста. +
Например, чтобы использовать kbd:[F1], kbd:[F2], kbd:[Alt+F1] и kbd:[Alt+F2]:

----
/key bind meta-OP /bar scroll buffers * -100%
/key bind meta-OQ /bar scroll buffers * +100%
/key bind meta-meta-OP /bar scroll buffers * b
/key bind meta-meta-OQ /bar scroll buffers * e
----

[NOTE]
Клавиши "meta-OP" и "meta-OQ" могут отличаться в вашем терминале. Чтобы найти код
клавиши, нажмите kbd:[Alt+k], затем клавишу.

[[customize_buflist]]
=== Как я могу настроить список буферов, например, цвет активного буфера?

Вы можете просмотреть все параметры buflist с помощью команды:

----
/fset buflist
----

Фон активного буфера по умолчанию синий, вы же можете изменить его,
например, на `красный`:

----
/set buflist.format.buffer_current "${color:,red}${format_buffer}"
----

[NOTE]
Перед названием цвета "красный" стоит запятая, потому что он используется в качестве фона,
а не цвета текста. +
Вы также можете использовать любой числовой цвет вместо `красного`,
например `237` для темно-серого.

The buflist plugin provides lot of options that you can customize, please read
the help on each option.

Также есть вики-страница с примерами расширенной конфигурации buflist:
https://github.com/weechat/weechat/wiki/buflist

[[customize_prefix]]
=== How can I reduce length of nicks or remove nick alignment in chat area?

Чтобы уменьшить максимальную длину ников в области чата:

----
/set weechat.look.prefix_align_max 15
----

To remove nick alignment:

----
/set weechat.look.prefix_align none
----

[[status_hotlist]]
=== Что означает [H: 3(1,8), 2(4)] в строке состояния?

This is called the "hotlist", a list of buffers with the number of unread
messages, by order: highlights, private messages, messages, other messages
(like join/part). +
The number of "unread message" is the number of new messages displayed/received
since you visited the buffer.

В примере `[H: 3(1,8), 2(4)]` есть:

* 1 упоминание и 8 непрочитанных сообщений в буфере #3,
* 4 непрочитанных сообщений в буфере #2.

Цвет буфера/счётчика зависит от типа сообщения, цвета по умолчанию:

* упоминания: `lightmagenta` / `magenta`
* личные сообщения: `lightgreen` / `green`
* сообщения: `yellow` / `brown`
* другие сообщения: `default` / `default` (цвет текста в терминале)

Эти цвета можно изменить с помощью параметров __weechat.color.status_data_*__
(буферы) и __weechat.color.status_count_*__ (счетчики). +
Другие параметры списка избранного можно изменить с помощью параметров __weechat.look.hotlist_*__.

See link:weechat_user.en.html#screen_layout[User's guide / Screen layout] for
more info about the hotlist.

[[input_bar_size]]
=== Как использовать командную строку с более чем одной строкой?

Параметр _size_ на панели ввода может быть установлен на значение выше 1 (для фиксированного
размера размер по умолчанию равен 1) или 0 для динамического размера, а затем параметр _size_max_
установит максимальный размер (0 = без ограничений).

Пример с динамическим размером:

----
/set weechat.bar.input.size 0
----

Максимальный размер 2:

----
/set weechat.bar.input.size_max 2
----

[[one_input_root_bar]]
=== Is it possible to display only one input bar for all windows (after split)?

Yes, you will have to create a bar with type "root" (with an item to know in
which window you are), then delete current input bar.

Например:

----
/bar add rootinput root bottom 1 0 [buffer_name]+[input_prompt]+(away),[input_search],[input_paste],input_text
/bar del input
----

Если вас это не устроит, просто удалите новую панель, WeeChat автоматически
создаст панель "input" по умолчанию, если элемент "input_text" не используется
ни в одной панели:

----
/bar del rootinput
----

[[terminal_copy_paste]]
=== How can I copy/paste text without pasting nicklist?

With WeeChat ≥ 1.0, you can use the bare display (default key: kbd:[Alt+l] (`L`)),
which will show just the contents of the currently selected window,
without any formatting.

You can use a terminal with rectangular selection (like rxvt-unicode,
konsole, gnome-terminal, etc.). Key is usually kbd:[Ctrl] + kbd:[Alt] + mouse
selection.

Другое решение - переместить список ников вверх или вниз, например:

----
/set weechat.bar.nicklist.position top
----

[[urls]]
=== Как мне выделять длинные URL-адреса (более одной строки)?

С WeeChat ≥ 1.0 вы можете использовать простой дисплей (клавиша по умолчанию: kbd:[Alt+l] (`L`)).

Чтобы упростить открытие URL-адресов, вы можете:

* переместить никлист наверх:

----
/set weechat.bar.nicklist.position top
----

* disable alignment for multiline words (WeeChat ≥ 1.7):

----
/set weechat.look.align_multiline_words off
----

* or for all wrapped lines:

----
/set weechat.look.align_end_of_lines time
----

With WeeChat ≥ 0.3.6, you can enable option "eat_newline_glitch", so that
new line char is not added at the end of each line displayed (it will not break
URL selection):

----
/set weechat.look.eat_newline_glitch on
----

[IMPORTANT]
Этот параметр может вызвать ошибки отображения. Если у вас возникла такая проблема, вы должны
отключить этот параметр.

Другое решение - использовать скрипт:

----
/script search url
----

[[change_locale_without_quit]]
=== Я хочу изменить язык сообщений WeeChat, но возможно ли это сделать, не выходя из WeeChat?

Конечно, это возможно:

----
/set env LANG en_US.UTF-8
/upgrade
----

[[timezone]]
=== Как я могу изменить часовой пояс?

В WeeChat нет возможности изменить часовой пояс, переменная окружения
`TZ` должна иметь соответствующее значение.

В файле инициализации оболочки или в командной строке перед запуском WeeChat:

----
export TZ=America/New_York
----

In WeeChat, the new value is immediately used:

----
/set env TZ America/New_York
----

[[use_256_colors]]
=== Как я могу использовать 256 цветов в WeeChat?

256 цветов поддерживаются WeeChat ≥ 0.3.4.

Сначала проверьте правильность переменной среды _TERM_, рекомендуемые значения:

* в screen: _screen-256color_
* в tmux: _screen-256color_ or _tmux-256color_
* в остальных случаях: _xterm-256color_, _rxvt-256color_, _putty-256color_, ...

[NOTE]
Возможно, вам придется установить пакет ncurses-term, чтобы использовать эти значения
в переменной _TERM_.

Если вы используете screen, вы можете добавить эту строку в свой _~/.screenrc_:

----
term screen-256color
----

Если ваша переменная _TERM_ имеет неправильное значение и окно WeeChat уже запущено,
вы можете изменить его с помощью этих двух команд (с WeeChat ≥ 1.0):

----
/set env TERM screen-256color
/upgrade
----

Для версии 0.3.4 вы должны использовать команду `/color` для добавления новых цветов.

Для версий ≥ 0.3.5 вы можете использовать любой номер цвета в параметрах (необязательно: вы
можете добавить алиасы цветов с помощью команды `/color`).

Пожалуйста, прочтите link:weechat_user.ru.html#colors[Руководство пользователя / Цвета] для
получения дополнительной информации о работе с цветами.

[[search_text]]
=== Как я могу искать текст в буфере (например, /lastlog в irssi)?

Клавиша по умолчанию: kbd:[Ctrl+r] (команда: `+/текст_для_поиска+`)
И перейти к выделенным: kbd:[Alt+p] / kbd:[Alt+n].

См. link:weechat_user.ru.html#key_bindings[Руководство пользователя / Привязки клавиш] для
получения дополнительной информации об этой функции.

[[terminal_focus]]
=== How can I execute commands when terminal gets/loses focus

You must enable the focus events with a special code sent to terminal..

*Важно*:

* You must use a modern xterm-compatible terminal.
* Additionally, it seems to be important that your value of the TERM variable
  equals to _xterm_ or _xterm-256color_.
* If you use tmux, you must additionally enable focus events by adding
  `set -g focus-events on` to your _.tmux.conf_ file.
* Это *не* работает под screen.

To send the code when WeeChat is starting:

----
/set weechat.startup.command_after_plugins "/print -stdout \033[?1004h\n"
----

And then you bind two keys for the focus (replace the `/print` commands by the
commands of your choice):

----
/key bind meta2-I /print -core focus
/key bind meta2-O /print -core unfocus
----

For example to mark buffers as read when the terminal loses the focus:

----
/key bind meta2-O /input set_unread
----

[[screen_paste]]
=== When WeeChat is running in screen, pasting text in another screen window adds ~0 and ~1 around text, why?

This is caused by the bracketed paste option which is enabled by default, and
not properly handled by screen in other windows.

You can just disable bracketed paste mode:

----
/set weechat.look.paste_bracketed off
----

[[small_terminal]]
=== How can I customize display for very small terminal size (like 80x25), to not waste space?

Вы можете удалить боковые панели (buflist и nicklist), изменить формат времени, чтобы
отображались только часы и минуты, отключить выравнивание сообщений и установить символ
для префикса/суффикса ника:

----
/set buflist.look.enabled off
/bar hide nicklist
/set weechat.look.buffer_time_format "%H:%M"
/set weechat.look.prefix_align none
/set weechat.look.align_end_of_lines prefix
/set weechat.look.nick_suffix ">"
/set weechat.look.nick_prefix "<"
----

Терминал 80x25, конфигурация по умолчанию:

....
┌────────────────────────────────────────────────────────────────────────────────┐
│1.local     │Welcome on WeeChat channel!                                        │
│  weechat   │16:27:16        --> | FlashCode (~flashcode@localhost)  │@FlashCode│
│2.  #weechat│                    | has joined #weechat               │ bob      │
│            │16:27:16         -- | Mode #weechat [+nt] by hades.arpa │          │
│            │16:27:16         -- | Channel #weechat: 1 nick (1 op, 0 │          │
│            │                    | voices, 0 normals)                │          │
│            │16:27:18         -- | Channel created on Sun, 22 Mar    │          │
│            │                    | 2020 16:27:16                     │          │
│            │17:02:28        --> | bob (~bob_user@localhost) has     │          │
│            │                    | joined #weechat                   │          │
│            │17:03:12 @FlashCode | hi bob, you're the first user     │          │
│            │                    | here, welcome on the WeeChat      │          │
│            │                    | support channel!                  │          │
│            │17:03:33        bob | hi FlashCode                      │          │
│            │                                                        │          │
│            │                                                        │          │
│            │                                                        │          │
│            │                                                        │          │
│            │                                                        │          │
│            │                                                        │          │
│            │                                                        │          │
│            │                                                        │          │
│            │                                                        │          │
│            │[17:04] [2] [irc/local] 2:#weechat(+nt){2}                         │
│            │[@FlashCode(i)] █                                                  │
└────────────────────────────────────────────────────────────────────────────────┘
....

Терминал 80x25, после изменений:

....
┌────────────────────────────────────────────────────────────────────────────────┐
│Welcome on WeeChat channel!                                                     │
│16:27 --> FlashCode (~flashcode@localhost) has joined #weechat                  │
│16:27 -- Mode #weechat [+nt] by hades.arpa                                      │
│16:27 -- Channel #weechat: 1 nick (1 op, 0 voices, 0 normals)                   │
│16:27 -- Channel created on Sun, 22 Mar 2020 16:27:16                           │
│17:02 --> bob (~bob_user@localhost) has joined #weechat                         │
│17:03 <@FlashCode> hi bob, you're the first user here, welcome on the WeeChat   │
│      support channel!                                                          │
│17:03 <bob> hi FlashCode                                                        │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│[17:04] [2] [irc/local] 2:#weechat(+nt){2}                                      │
│[@FlashCode(i)] █                                                               │
└────────────────────────────────────────────────────────────────────────────────┘
....

[[key_bindings]]
== Привязки клавиш

[[meta_keys]]
=== Некоторые мета-клавиши (alt + клавиша) не работают, почему?

Если вы используете некоторые терминалы, такие как xterm или uxterm, некоторые мета-клавиши
не работают по умолчанию. Вы можете добавить строку в файл _~/.Xresources_:

* Для xterm:
----
XTerm*metaSendsEscape: true
----
* Для uxterm:
----
UXTerm*metaSendsEscape: true
----

А затем перезагрузите ресурсы (`xrdb -override ~/.Xresources`) или перезапустите X.

Если вы используете приложение macOS Terminal, включите параметр "Use option as meta key"
в меню Settings/Keyboard, после чего вы можете использовать клавишу
kbd:[Option] как мета-клавишу.

[[customize_key_bindings]]
=== Как я могу настроить привязки клавиш?

Привязки клавиш настраиваются с помощью команды `/key`.

Клавиша по умолчанию kbd:[Alt+k] позволяет получить код клавиши и вставить его в командную строку.

[[jump_to_buffer_11_or_higher]]
=== Какая клавиша нужна для перехода к буферу 11 (или большему числу)?

Сочетание клавиш kbd:[Alt+j], а затем 2 цифры, например kbd:[Alt+j], kbd:[1],
kbd:[1] для перехода к буферу 11.

Вы можете привязать клавишу, например:

----
/key bind meta-q /buffer *11
----

Список ключей по умолчанию находится в
link:weechat_user.ru.html#key_bindings[Руководство пользователя / Привязки клавиш].

Чтобы перейти к буферам с номером ≥ 100, вы можете определить триггер, а затем
использовать такие команды, как `/123`, для перехода к буферу #123:

----
/trigger add numberjump modifier "2000|input_text_for_buffer" "${tg_string} =~ ^/[0-9]+$" "=\/([0-9]+)=/buffer *${re:1}=" "" "" "none"
----

[[global_history]]
=== Как использовать глобальную историю (вместо истории буфера) с клавишами вверх и вниз?

Вы можете привязать клавиши вверх и вниз к глобальной истории (клавиши по умолчанию для
глобальной истории - kbd:[Ctrl+↑] и kbd:[Ctrl+↓]).

Например:

----
/key bind meta2-A /input history_global_previous
/key bind meta2-B /input history_global_next
----

[NOTE]
Клавиши "meta2-A" и "meta2-B" могут отличаться в вашем терминале. Чтобы найти код
клавиши, нажмите kbd:[Alt+k], затем клавишу.

[[mouse]]
== Мышь

[[mouse_not_working]]
=== Мышь вообще не работает, что делать?

Мышь поддерживается WeeChat ≥ 0.3.6.

Сначала попробуйте включить мышь:

----
/mouse enable
----

Если мышь по-прежнему не работает, проверьте переменную TERM в вашей оболочке (посмотрите вывод
`echo $TERM` в вашем терминале).
Согласно используемому terminfo, мышь может не поддерживаться.

Вы можете проверить поддержку мыши в терминале:

----
$ printf '\033[?1002h'
----

Затем нажмите на первый символ терминала (вверху слева). Вы должны увидеть " !!#!!".

Чтобы отключить мышь в терминале:

----
$ printf '\033[?1002l'
----

[[mouse_coords]]
=== Mouse does nothing for X or Y greater than 94 (or 222), why?

Некоторые терминалы отправляют только символы ISO для координат мыши, поэтому это не
работает для X/Y больше 94 (или 222).

Вы должны использовать терминал, который поддерживает координаты UTF-8 для мыши,
например rxvt-unicode.

[[mouse_select_paste]]
=== Как я могу выбрать или вставить текст в терминал, когда в WeeChat включена мышь?

When mouse is enabled in WeeChat, you can use kbd:[Shift] modifier to select or
click in terminal, as if the mouse was disabled (on some terminals like iTerm,
you have to use kbd:[Alt] instead of kbd:[Shift]).

[[irc]]
== IRC

[[irc_ssl_connection]]
=== У меня проблемы с подключением к серверу с использованием SSL, что мне делать?

Если вы используете macOS, вы должны установить `openssl` из Homebrew.
Файл CA будет загружен с использованием сертификатов из системной цепочки ключей.

В WeeChat ≤ 3.1 вы можете указать путь к системным сертификатам:

----
/set weechat.network.gnutls_ca_file "/usr/local/etc/openssl/cert.pem"
----

If you see errors about gnutls handshake, you can try to use a smaller
Diffie-Hellman key (default is 2048):

----
/set irc.server.example.ssl_dhkey_size 1024
----

Если вы видите ошибки сертификата, вы можете отключить "ssl_verify" (будьте осторожны,
от этого соединение будет менее безопасным):

----
/set irc.server.example.ssl_verify off
----

Если у сервера недействительный сертификат и вы знаете, каким должен быть сертификат,
вы можете указать отпечаток пальца (SHA-512, SHA-256 или SHA-1):

----
/set irc.server.example.ssl_fingerprint 0c06e399d3c3597511dc8550848bfd2a502f0ce19883b728b73f6b7e8604243b
----

[[irc_ssl_handshake_error]]
=== При подключении к серверу с SSL я вижу только ошибку "TLS handshake failed", что мне делать?

You can try a different priority string (WeeChat ≥ 0.3.5 only), replace "xxx"
by your server name:

----
/set irc.server.xxx.ssl_priorities "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.0:+VERS-SSL3.0:%COMPAT"
----

[[irc_ssl_libera]]
=== Как я могу подключиться к серверу libera с помощью SSL?

Для WeeChat ≤ 3.1 установите для параметра _weechat.network.gnutls_ca_file_ файл
с сертификатами:

----
/set weechat.network.gnutls_ca_file "/etc/ssl/certs/ca-certificates.crt"
----

Примечание: если вы используете macOS с установленным homebrew openssl, вы можете:

----
/set weechat.network.gnutls_ca_file "/usr/local/etc/openssl/cert.pem"
----

[NOTE]
Убедитесь, что у вас есть этот файл в вашей системе (обычно предоставляется пакетом
"ca-Certificates").

Установите порт сервера, SSL, затем подключитесь:

----
/set irc.server.libera.addresses "irc.libera.chat/6697"
/set irc.server.libera.ssl on
/connect libera
----

[[irc_oauth]]
=== Как подключиться к серверу, требующему "oauth"?

Некоторым серверам, таким как _twitch_, для подключения требуется oauth.

Oauth - это просто пароль со значением "oauth:XXXX".

Вы можете добавить такой сервер и подключиться с помощью следующих команд (замените имя
и адрес соответствующими значениями):

----
/server add name irc.server.org -password=oauth:XXXX
/connect name
----

[[irc_sasl]]
=== How can I be identified before joining channels?

If the server supports SASL, you should use that instead of sending the
command for nickserv authentication, for example:

----
/set irc.server.libera.sasl_username "mynick"
/set irc.server.libera.sasl_password "xxxxxxx"
----

If the server does not support SASL, you can add a delay (between command and
join of channels):

----
/set irc.server.libera.command_delay 5
----

[[edit_autojoin]]
=== Как я могу добавить/удалить каналы из параметра автосоединения?

Вы можете использовать команду `/set` для редактирования списка каналов автосоединения,
например, для сервера "libera":

----
/set irc.server.libera.autojoin [TAB]
----

[NOTE]
You can complete the name and value of option with the kbd:[Tab] key
(or kbd:[Shift+Tab] for partial completion, useful for the name). +
Таким образом, вам не нужно набирать весь список каналов.

Вы также можете использовать команду `/fset` для редактирования списка каналов:

----
/fset autojoin
----

Другое решение - использовать скрипт:

----
/script search autojoin
----

[[ignore_vs_filter]]
=== В чем разница между командами /ignore и /filter?

Команда `/ignore` - это команда IRC, поэтому она применяется только для буферов IRC
(серверов и каналов).
Это позволяет вам игнорировать некоторые ники или имена хостов пользователей для сервера или канала
(команда не применяется к содержимому сообщений).
Соответствующие сообщения удаляются плагином IRC перед отображением (поэтому вы
никогда их не увидите и не сможете восстановить, удалив игнорирование).

Команда `/filter` - это основная команда WeeChat, поэтому она применяется к любому буферу.
Он позволяет фильтровать некоторые строки в буферах с помощью тегов или регулярных выражений
для префикса и содержимого строки.
Отфильтрованные строки только скрываются, а не удаляются, и вы можете увидеть их,
если отключите фильтры (по умолчанию клавиша kbd:[Alt+=] переключает фильтры).

[[filter_irc_join_part_quit]]
=== How can I filter join/part/quit messages on IRC channels?

With smart filter (keep join/part/quit from users who spoke recently):

----
/set irc.look.smart_filter on
/filter add irc_smart * irc_smart_filter *
----

With a global filter (hide *all* join/part/quit):

----
/filter add joinquit * irc_join,irc_part,irc_quit *
----

[NOTE]
Для справки: `/help filter`, `+/help irc.look.smart_filter+`и см.
links:weechat_user.ru.html#irc_smart_filter_join_part_quit[Руководство пользователя / Умный фильтр для сообщений о join/part/quit].

[[filter_irc_join_channel_messages]]
=== Как я могу отфильтровать некоторые сообщения, отображаемые, когда я присоединяюсь к каналу IRC?

В WeeChat ≥ 0.4.1 вы можете выбрать, какие сообщения будут отображаться
при присоединении к каналу, с помощью параметра _irc.look.display_join_message_
(см. `+/help irc.look.display_join_message+` для дополнительной информации).

Чтобы скрыть сообщения (но сохранить их в буфере), вы можете отфильтровать их с помощью тега
(например, _irc_329_ для даты создания канала). См. `/help filter` для получения справки
по фильтрам.

[[filter_voice_messages]]
=== How can I filter voice messages (eg on Bitlbee server)?

It's not easy to filter voice messages, because voice mode can be set with other
modes in same IRC message.

If you want to do that, it's probably because Bitlbee is using voice to show
away users, and you are flooded with voice messages. Therefore, you can change
that and let WeeChat use a special color for away nicks in nicklist.

For Bitlbee ≥ 3, issue this on control channel _&bitlbee_:

----
channel set show_users online,away
----

For older version of Bitlbee, issue this on control channel _&bitlbee_:

----
set away_devoice false
----

For checking away nicks in WeeChat, see question about
<<color_away_nicks,away nicks>>.

If you really want to filter voice messages, you can use this command, but this
is not perfect (will work only if first mode changed is voice):

----
/filter add hidevoices * irc_mode (\+|\-)v
----

[[color_away_nicks]]
=== How can I see away nicks in nicklist?

You have to set option _irc.server_default.away_check_ to a positive value
(minutes between each check of away nicks).

You can set option _irc.server_default.away_check_max_nicks_ to limit away check
on small channels only.

Например, если вы хотите проверять ники каждые 5 минут для каналов с максимум 25 никами:

----
/set irc.server_default.away_check 5
/set irc.server_default.away_check_max_nicks 25
----

[NOTE]
Для WeeChat ≤ 0.3.3 доступны следующие варианты: _irc.network.away_check_ и
_irc.network.away_check_max_nicks_.

[[highlight_notification]]
=== Как я могу быть уведомлён, когда кто-то упоминает меня на канале?

В WeeChat ≥ 1.0 по умолчанию используется "звуковой сигнал", который отправляет _BEL_ на
терминал при упоминании или личном сообщении. Таким образом, вы можете настроить свой
терминал (или мультиплексор, например screen/tmux) на запуск команды или воспроизведение
звука при возникновении _BEL_.

Или вы можете добавить команду в триггер "beep":

----
/set trigger.trigger.beep.command "/print -beep;/exec -bg /путь/к/команде аргументы"
----

Со старым WeeChat вы можете использовать скрипт, например _beep.pl_ или _launcher.pl_.

For _launcher.pl_, you have to setup a command:

----
/set plugins.var.perl.launcher.signal.weechat_highlight "/путь/к/команде аргументы"
----

Другие скрипты на эту тему:

----
/script search notify
----

[[disable_highlights_for_specific_nicks]]
=== How can I disable highlights for specific nicks?

With WeeChat ≥ 0.3.4 you can use the
link:weechat_user.en.html#max_hotlist_level_nicks[hotlist_max_level_nicks_add]
buffer property to set the max hotlist level for some nicks, per buffer,
or per group of buffers (like IRC servers).


Чтобы отключить только упоминания, вам нужно установить его на 2:

----
/buffer set hotlist_max_level_nicks_add joe:2,mike:2
----

Однако это свойство буфера не сохраняется в конфигурации.
Чтобы автоматически повторно применить эти свойства буфера, вам понадобится скрипт
_buffer_autoset.py_:

----
/script install buffer_autoset.py
----

Например, если вы хотите навсегда исключить упоминания от ника "mike" из #weechat
на IRC-сервере libera:

----
/buffer_autoset add irc.libera.#weechat hotlist_max_level_nicks_add mike:2
----

Или же вместо этого применить его ко всему серверу libera:

----
/buffer_autoset add irc.libera hotlist_max_level_nicks_add mike:2
----

Дополнительные примеры см. в разделе `+/help buffer_autoset+`.

[[irc_target_buffer]]
=== How can I change target buffer for commands on merged buffers (like buffer with servers)?

Сочетание клавиш по умолчанию: kbd:[Ctrl+x] (команда: `+/input switch_active_buffer+`).

[[plugins_scripts]]
== Плагины / скрипты

[[openbsd_plugins]]
=== Я использую OpenBSD, а WeeChat не загружает никаких плагинов, что не так?

В OpenBSD имена файлов плагинов заканчиваются на ".so.0.0" (".so" для Linux).

Вы должны настроить это:

----
/set weechat.plugin.extension ".so.0.0"
/plugin autoload
----

[[install_scripts]]
=== Как установить скрипты? Совместимы ли скрипты с другими IRC-клиентами?

В WeeChat ≥ 0.3.9 вы можете использовать команду `/script` для установки и управления
скриптов (см. справку в `/help script`). Для более старых версий есть weeget.py и script.pl.

Скрипты несовместимы с другими IRC-клиентами.

[[scripts_update]]
=== Команда "/script update" не может считывать скрипты, как это исправить?

Сначала проверьте вопросы о SSL-соединении в этом FAQ.

Если все ещё не работает, попробуйте вручную удалить файл скрипта (в вашей оболочке):

----
$ rm ~/.cache/weechat/script/plugins.xml.gz
----

[NOTE]
Для WeeChat ≤ 3.1 путь должен быть: _~/.weechat/script/plugins.xml.gz_.

И снова обновите скрипты в WeeChat:

----
/script update
----

Если вы по-прежнему получаете ошибку, вы должны отключить автоматическое обновление файла
в WeeChat и загрузить файл вручную вне WeeChat (это означает, что вам придется вручную обновить
файл самостоятельно, чтобы получать обновления):

* в WeeChat:

----
/set script.scripts.cache_expire -1
----

* в вашей оболочке с установленным curl:

----
$ cd ~/.cache/weechat/script
$ curl -O https://weechat.org/files/plugins.xml.gz
----

[[spell_dictionaries]]
=== Я установил словари aspell в свою систему, как я могу использовать их без перезапуска WeeChat?

Вам необходимо перезагрузить плагин spell:

----
/plugin reload spell
----

[NOTE]
В WeeChat ≤ 2.4 плагин для "spell" был назван "aspell", поэтому команда выглядит так:
`/plugin reload aspell`.

[[settings]]
== Настройки

[[editing_config_files]]
=== Могу ли я редактировать файлы конфигурации (*.conf) вручную?

Можете, но это *НЕ* рекомендуется.

В WeeChat рекомендуется использовать команду `/set`:

* You can complete the name and value of option with kbd:[Tab] key
  (or kbd:[Shift+Tab] for partial completion, useful for the name).
* The value is checked, a message is displayed in case of error.
* The value is used immediately, you don't need to restart anything.

Если вы всё же хотите редактировать файлы вручную, будьте осторожны:

* Если вы укажете недопустимое значение для параметра, WeeChat отобразит ошибку при загрузке
  и отклонит значение (будет использоваться значение по умолчанию для параметра).
* Если WeeChat запущен, вам придется ввести команду `/reload`, и если некоторые настройки были
  изменены, но не сохранены с помощью `/save`, вы потеряете их.

[[memory_usage]]
=== Как настроить WeeChat так, чтобы она потребляла меньше памяти?

Вы можете попробовать следующие советы, чтобы использовать меньше памяти:

* Используйте последнюю стабильную версию (предполагается, что в ней меньше утечек памяти,
  чем в более старых версиях).
* Не загружайте плагины, если вы их не используете, например: buflist, fifo, logger,
  perl, python, ruby, lua, tcl, guile, javascript, php, spell, xfer (используется для DCC).
  См. `/help weechat.plugin.autoload`.
* Загружайте только те скрипты, которые вам действительно нужны.
* Не загружайте системные сертификаты, если SSL *НЕ* используется: отключите эту опцию:
  _weechat.network.gnutls_ca_system_.
* Уменьшите значение параметра _weechat.history.max_buffer_lines_number_ или установите
  значение параметра _weechat.history.max_buffer_lines_minutes_.
* Уменьшите значение опции _weechat.history.max_commands_.

[[cpu_usage]]
=== Как я могу настроить WeeChat, чтобы она использовала меньше ЦП?

Вы можете следовать тем же советам, что и для <<memory_usage,памяти>>, а также следующим:

* Скрыть панель ников: `/bar hide nicklist`.
* Убрать отображение секунд в строке состояния времени:
  `+/set weechat.look.item_time_format "%H:%M"+` (это значение по умолчанию).
* Отключить проверку орфографических ошибок в реальном времени в командной строке (если
  вы ее включили): `+/set spell.check.real_time off+`.
* Установите переменную _TZ_ (например: `export TZ ="Europe/Paris"`), чтобы предотвратить
  частый доступ к файлу _/etc/localtime_.

[[security]]
=== Я параноик по поводу безопасности, какие настройки я могу изменить, чтобы повысить безопасность?

Отключить IRC-part и quit сообщения:

----
/set irc.server_default.msg_part ""
/set irc.server_default.msg_quit ""
----

Отключить ответы на все запросы CTCP:

----
/set irc.ctcp.clientinfo ""
/set irc.ctcp.finger ""
/set irc.ctcp.source ""
/set irc.ctcp.time ""
/set irc.ctcp.userinfo ""
/set irc.ctcp.version ""
/set irc.ctcp.ping ""
----

Выгрузите и отключите автозагрузку плагина "xfer" (используется для IRC DCC):

----
/plugin unload xfer
/set weechat.plugin.autoload "*,!xfer"
----

Определите кодовую фразу и используйте защищенные данные везде, где это возможно,
для конфиденциальных данных, таких как пароли: см. `/help secure` и `/ help` о параметрах
(если вы можете использовать защищенные данные, это написано в справке).
См. также ссылку: weechat_user.ru.html#secured_data[Руководство пользователя / Защищенные данные].

Например:

----
/secure passphrase xxxxxxxxxx
/secure set libera_username username
/secure set libera_password xxxxxxxx
/set irc.server.libera.sasl_username "${sec.data.libera_username}"
/set irc.server.libera.sasl_password "${sec.data.libera_password}"
----

[[sharing_config_files]]
=== Я хочу поделиться своей конфигурацией WeeChat, какими файлами я должен поделиться?

Вы можете предоставить общий доступ к файлам конфигурации _*.сonf_, за исключением
файла _sec.conf_, который содержит ваши пароли, зашифрованные вашей кодовой фразой.

Некоторые другие файлы могут содержать конфиденциальную информацию, например пароли
(если они не хранятся в _sec.conf_ с помощью команды `/secure`).

See the link:weechat_user.ru.html#files_and_directories[User's guide / Files and directories]
for more information about configuration files.
См. link:weechat_user.ru.html#files_and_directories[Руководство пользователя / Файлы и каталоги]
для получения дополнительной информации о файлах конфигурации.

[[development]]
== Разработка

[[bug_task_patch]]
=== Как мне сообщать об ошибках, запрашивать новые функции или отправлять исправления?

См.: https://weechat.org/about/support

[[gdb_error_threads]]
=== Когда я запускаю WeeChat под gdb, возникает ошибка потоков, что мне делать?

Когда вы запускаете WeeChat под gdb, у вас может быть такая ошибка:

----
$ gdb /путь/к/weechat
(gdb) run
[Thread debugging using libthread_db enabled]
Cannot find new threads: generic error
----

Чтобы исправить это, вы можете запустить gdb с помощью этой команды (замените путь к
libpthread и WeeChat на пути в вашей системе):

----
$ LD_PRELOAD=/lib/libpthread.so.0 gdb /путь/к/weechat
(gdb) run
----

[[supported_os]]
=== Какой список поддерживаемых платформ для WeeChat? Будет ли он перенесен на другие операционные системы?

WeeChat отлично работает в большинстве дистрибутивов Linux/BSD, GNU/Hurd, Mac OS и Windows
(Cygwin и WSL).

Мы делаем все возможное, чтобы работать на как можно большем количестве платформ. Помощь
приветствуется для некоторых ОС, которых у нас нет, для тестирования WeeChat.

[[help_developers]]
=== Я хочу помочь разработчикам WeeChat. Что я могу сделать?

Есть много задач, которые нужно выполнить (тестирование, код, документация и т.д.)

Свяжитесь с нами через IRC или по почте, посмотрите страницу поддержки:
https://weechat.org/about/support

[[donate]]
=== Могу ли я отдать деньги или другие вещи разработчикам WeeChat?

Вы можете дать нам деньги, чтобы помочь развитию.
Подробности на https://weechat.org/donate
