= weechat(1)
:doctype: manpage
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: ru
// TRANSLATION MISSING
:man manual: WeeChat Manual
:man source: WeeChat {revnumber}

== НАЗВАНИЕ

weechat - расширяемый чат-клиент

== ОБЗОР

[verse]
*weechat* [-a|--no-connect] [-d|--dir <путь>] [-p|--no-plugin] [-r|--run-command <команда>] [-s|--no-script] [--upgrade] [<плагин>:<параметр>...]
*weechat* [-c|--colors]
*weechat* [-h|--help]
*weechat* [-l|--license]
*weechat* [-v|--version]

*weechat-headless* [-a|--no-connect] [--daemon] [-d|--dir <path>] [-p|--no-plugin] [-r|--run-command <command>] [-s|--no-script] [--upgrade] [plugin:option...]

== ОПИСАНИЕ

WeeChat (Wee Enhanced Environment for Chat) это свободный чат-клиент - быстрый и легкий,
он подходит для большинства операционных систем.
Его легко настроить, кроме того, вы можете расширить его функицонал при помощи скриптов.

// TRANSLATION MISSING
The command *weechat-headless* runs WeeChat in a headless mode (no interface).
It can be used for tests or to daemonize WeeChat with the option "--daemon".

== ПАРАМЕТРЫ

include::cmdline_options.ru.adoc[]

== ПАРАМЕТРЫ ПЛАГИНОВ

Полное описание параметров плагинов доступно в документации по плагинам в
https://weechat.org/doc[Руководстве пользователя WeeChat].

С помощью плагина irc можно присоединиться ко временному серверу, используя URL вроде:

    irc[6][s]://[[nickname][:password]@]server[:port][/#channel1[,#channel2...]]

Присоединиться к IRC-каналу поддержки пользователей WeeChat с псевдонимом "mynick":

    irc://mynick@chat.freenode.net/#weechat

IPv6-адрес можно заключить в квадратные скобки, чтобы указать порт. Например:

    irc://mynick@[2001:db8:0:85a3::ac1f:8001]:6668/#test

== ФАЙЛЫ

$HOME/.weechat/weechat.conf::
    главный файл конфигурации WeeChat

$HOME/.weechat/plugins.conf::
    файл конфигурации плагинов

$HOME/.weechat/sec.conf::
    файл конфигурации с защищаемыми данными

$HOME/.weechat/alias.conf::
    файл конфигурации для плагина _alias_

$HOME/.weechat/aspell.conf::
    файл конфигурации для плагина _aspell_

$HOME/.weechat/buflist.conf::
    файл конфигурации для плагина _buflist_

$HOME/.weechat/charset.conf::
    файл конфигурации для плагина _charset_

$HOME/.weechat/exec.conf::
    файл конфигурации для плагина _exec_

$HOME/.weechat/fifo.conf::
    файл конфигурации для плагина _fifo_

$HOME/.weechat/fset.conf::
    файл конфигурации для плагина _fset_

$HOME/.weechat/guile.conf::
    файл конфигурации для плагина _guile_

$HOME/.weechat/irc.conf::
    файл конфигурации для плагина _irc_

$HOME/.weechat/javascript.conf::
    файл конфигурации для плагина _javascript_

$HOME/.weechat/logger.conf::
    файл конфигурации для плагина _logger_

$HOME/.weechat/lua.conf::
    файл конфигурации для плагина _lua_

$HOME/.weechat/perl.conf::
    файл конфигурации для плагина _perl_

$HOME/.weechat/php.conf::
    файл конфигурации для плагина _php_

$HOME/.weechat/python.conf::
    файл конфигурации для плагина _python_

$HOME/.weechat/relay.conf::
    файл конфигурации для плагина _relay_

$HOME/.weechat/ruby.conf::
    файл конфигурации для плагина _ruby_

$HOME/.weechat/script.conf::
    файл конфигурации для плагина _script_

$HOME/.weechat/tcl.conf::
    файл конфигурации для плагина _tcl_

$HOME/.weechat/trigger.conf::
    файл конфигурации для плагина _trigger_

$HOME/.weechat/xfer.conf::
    файл конфигурации для плагина _xref_

$HOME/.weechat/weechat.log::
    лог-файл WeeChat

== АВТОРЫ

Эта man-страница написана {author}.

Перевод: Alexander Turenko.

== КОПИРАЙТ

WeeChat написан Sébastien Helleu и другими участниками (полный список находится
в файле AUTHORS.adoc).

Copyright (C) 2003-2018 {author}

WeeChat is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

Подробную информацию можно найти в файле COPYING.

Веб: https://weechat.org/

== ПОДДЕРЖКА / СООБЩЕНИЯ ОБ ОШИБКАХ

Получить помощь или сообщить об ошибке: https://weechat.org/dev/support
