set(PROJECT_NAME "WeeChat")
set(PROJECT_VER_MAJOR "1")
set(PROJECT_VER_MINOR "0-rc1")
set(PROJECT_ASCII_LOGO "  ___       __         ______________        _____ \\n  __ |     / /___________  ____/__  /_______ __  /_\\n  __ | /| / /_  _ \\\\  _ \\\\  /    __  __ \\\\  __ `/  __/\\n  __ |/ |/ / /  __/  __/ /___  _  / / / /_/ // /_  \\n  ____/|__/  \\\\___/\\\\___/\\\\____/  /_/ /_/\\\\__,_/ \\\\__/")
set(PROJECT_URL "http://weechat.org/")
set(PROJECT_URL_DOWNLOAD "http://weechat.org/download")
set(PROJECT_COPYRIGHT "(C) 2003-2014")
set(PROJECT_LICENSE "GPL3")
set(PROJECT_LICENSE_TEXT "${PROJECT_NAME} is free software; you can redistribute it and/or modify\\nit under the terms of the GNU General Public License as published by\\nthe Free Software Foundation; either version 3 of the License, or\\n(at your option) any later version.\\n\\n${PROJECT_NAME} is distributed in the hope that it will be useful,\\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\\nGNU General Public License for more details.\\n\\nYou should have received a copy of the GNU General Public License\\nalong with ${PROJECT_NAME}.  If not, see <http://www.gnu.org/licenses/>.")
set(PROJECT_AUTHOR "Sébastien Helleu")
set(PROJECT_AUTHOR_EMAIL "flashcode@flashtux.org")
