= Reporting WeeChat issues
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: en


== Report bugs

First, some basic things:

* Use only English to communicate with developers.
* If you can, please check if the problem has been fixed in development version
  (if you are using a stable release or old version).
* Report only one bug or feature request per issue.

=== Required info

Please give some info:

* The *version* of WeeChat: output of `/v` in WeeChat, for example:
  `WeeChat 1.0-dev (git: v0.4.3-475-gb174b3c)`. +
  If WeeChat does not start at all, give the version displayed by
  `weechat --help` (or the version installed with your package manager).
* The operating system, including distribution name (for Linux) and its version
  (examples: Linux Debian Wheezy, FreeBSD 10.0, Windows/Cygwin 64-bit, ...).
* If possible, please include a reproducible example: explain the steps which
  led you to the problem. +
  It's even better if you can reproduce the problem with a new config (and no
  scripts loaded): try `weechat --dir /tmp/weechat` and check if you have the
  problem here.

=== Use of scripts

If you are using scripts, they can cause problems/crashes. To check if the
problem is related to one script, try to unload them one by one (using
command `/script unload <name>`).

If you think the problem comes from a specific script, please report the issue
in the https://github.com/weechat/scripts[scripts git repository].

=== Report a crash

If you are reporting a crash, please attach the backtrace from gdb (look at
http://weechat.org/files/doc/devel/weechat_user.en.html#report_crashes[user's guide]
for more info).

Most of times, the WeeChat crash log file (`weechat_crash_YYYYMMDD_xxx.log`) is
*not useful* to fix the bug, so please report this file *ONLY* if a developer
asks you to send it (and be careful, this file can contain personal data like
passwords).

== Feature requests

WeeChat is under active development, so your idea may already have been
implemented, or scheduled for a future version (you can check in
http://weechat.org/dev/[roadmap]).

Before submitting a feature request, it's better to discuss about it in IRC
(server: 'chat.freenode.net', channel '#weechat').

== Contributing

If you want to fix a bug or add a new feature, it's always a good idea to
discuss about it in IRC.

And you can look at http://weechat.org/files/doc/devel/weechat_dev.en.html[developer's guide] for coding rules
(styles, naming convention, and other useful info).
