= weechat(1)
:doctype: manpage
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: de
:man manual: WeeChat Manual
:man source: WeeChat {revnumber}

== NAME

weechat - der erweiterbare Chat Client

== SYNOPSIS

[verse]
*weechat* [-a|--no-connect] [-d|--dir <path>] [-p|--no-plugin] [-r|--run-command <command>] [-s|--no-script] [--upgrade] [plugin:option...]
*weechat* [-c|--colors]
*weechat* [-h|--help]
*weechat* [-l|--license]
*weechat* [-v|--version]

*weechat-headless* [-a|--no-connect] [--daemon] [-d|--dir <path>] [-p|--no-plugin] [-r|--run-command <command>] [-s|--no-script] [--upgrade] [plugin:option...]

== BESCHREIBUNG

WeeChat (Wee Enhanced Environment for Chat) ist ein freier, schneller und
schlanker Chat-Client der für unterschiedliche Betriebssysteme entwickelt wird.
Durch Skripten ist das Hauptprogramm äußerst flexibel und erweiterbar.

// TRANSLATION MISSING
The command *weechat-headless* runs WeeChat in a headless mode (no interface).
It can be used for tests or to daemonize WeeChat with the option "--daemon".

== OPTIONEN

include::cmdline_options.de.adoc[]

== OPTIONEN von ERWEITERUNGEN

Um eine vollständige Dokumentation der Optionen zu erhalten, siehe
https://weechat.org/doc[WeeChat user's guide].

Mittels der IRC Erweiterung kann man sich zu einen temporären Server verbinden lassen,
indem man eine URL verwendet:

    irc[6][s]://[[nickname][:password]@]server[:port][/#channel1[,#channel2...]]

Um dem WeeChat IRC Support-Channel, mit dem Nick "mynick", beizutreten:

    irc://mynick@chat.freenode.net/#weechat

Um eine IPv6 Adresse zu nutzen, muss diese in eckige Klammern gesetzt werden:

    irc://mynick@[2001:db8:0:85a3::ac1f:8001]:6668/#test

== DATEIEN

$HOME/.weechat/weechat.conf::
    WeeChats Konfigurationsdatei

$HOME/.weechat/plugins.conf::
    Konfigurationsdatei für Erweiterungen

$HOME/.weechat/sec.conf::
    Konfigurationsdatei mit schutzwürdigen Daten

$HOME/.weechat/alias.conf::
    Konfigurationsdatei für _alias_ Erweiterung

$HOME/.weechat/aspell.conf::
    Konfigurationsdatei für _aspell_ Erweiterung

$HOME/.weechat/buflist.conf::
    Konfigurationsdatei für _buflist_ Erweiterung

$HOME/.weechat/charset.conf::
    Konfigurationsdatei für _charset_ Erweiterung

$HOME/.weechat/exec.conf::
    Konfigurationsdatei für _exec_ Erweiterung

$HOME/.weechat/fifo.conf::
    Konfigurationsdatei für _fifo_ Erweiterung

$HOME/.weechat/fset.conf::
    Konfigurationsdatei für _fset_ Erweiterung

$HOME/.weechat/guile.conf::
    Konfigurationsdatei für _guile_ Erweiterung

$HOME/.weechat/irc.conf::
    Konfigurationsdatei für _irc_ Erweiterung

$HOME/.weechat/javascript.conf::
    Konfigurationsdatei für _javascript_ Erweiterung

$HOME/.weechat/logger.conf::
    Konfigurationsdatei für _logger_ Erweiterung

$HOME/.weechat/lua.conf::
    Konfigurationsdatei für _lua_ Erweiterung

$HOME/.weechat/perl.conf::
    Konfigurationsdatei für _perl_ Erweiterung

$HOME/.weechat/php.conf::
    Konfigurationsdatei für _php_ Erweiterung

$HOME/.weechat/python.conf::
    Konfigurationsdatei für _python_ Erweiterung

$HOME/.weechat/relay.conf::
    Konfigurationsdatei für _relay_ Erweiterung

$HOME/.weechat/ruby.conf::
    Konfigurationsdatei für _ruby_ Erweiterung

$HOME/.weechat/script.conf::
    Konfigurationsdatei für _script_ Erweiterung

$HOME/.weechat/tcl.conf::
    Konfigurationsdatei für _tcl_ Erweiterung

$HOME/.weechat/trigger.conf::
    Konfigurationsdatei für _trigger_ Erweiterung

$HOME/.weechat/xfer.conf::
    Konfigurationsdatei für _xfer_ Erweiterung

$HOME/.weechat/weechat.log::
    WeeChat Protokolldatei

== AUTOREN

Diese manpage wurde von {author} geschrieben.

Übersetzt von Nils Görs.

== COPYRIGHT

WeeChat wird programmiert von Sébastien Helleu und weiteren Beteiligten (eine vollständige Auflistung
findet man in der AUTHORS.adoc Datei).

Copyright (C) 2003-2018 {author}

WeeChat is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

Please read the COPYING file for more information.

Web: https://weechat.org/

== SUPPORT / FEHLER MELDEN

für Hilfe oder um einen Fehler zu melden: https://weechat.org/dev/support
