= weechat-headless(1)
:doctype: manpage
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: de
:man manual: WeeChat Manual
:man source: WeeChat {revnumber}

== NAME

weechat-headless - der erweiterbare Chat Client (headless version)

== SYNOPSIS

[verse]
*weechat-headless* [-a|--no-connect] [--daemon] [-d|--dir <path>] [-p|--no-plugin] [-r|--run-command <command>] [-s|--no-script] [--upgrade] [plugin:option...]
*weechat-headless* [-c|--colors]
*weechat-headless* [-h|--help]
*weechat-headless* [-l|--license]
*weechat-headless* [-v|--version]

== BESCHREIBUNG

WeeChat (Wee Enhanced Environment for Chat) ist ein freier, schneller und
schlanker Chat-Client der für unterschiedliche Betriebssysteme entwickelt wird.
Durch Skripten ist das Hauptprogramm äußerst flexibel und erweiterbar.

Mit dem Befehl *weechat-headless* kann man WeeChat ohne Benutzeroberfläche ausführen.
Dies kann zu Testzwecken oder dazu genutzt werden um WeeChat in einem Deamon-Modus
zu starten. Dazu nutzt man die Option "--daemon".

== OPTIONEN

include::cmdline_options.de.adoc[]

== OPTIONEN von ERWEITERUNGEN

include::man_plugin_options.de.adoc[]

== DATEIEN

include::man_files.de.adoc[]

== siehe auch

*weechat*(1)

== AUTOREN

Diese manpage wurde von {author} geschrieben.

Übersetzt von Nils Görs.

== COPYRIGHT

include::man_copyright.de.adoc[]

== SUPPORT / FEHLER MELDEN

für Hilfe oder um einen Fehler zu melden: https://weechat.org/dev/support
