\input texinfo  @c -*-texinfo-*-
@c %**start of header
@setfilename weechat_doc_pt.info
@settitle WeeChat - Um cliente de IRC rapido, leve e extencivel
@c %**end of header

@c WeeChat documentation (vers@~ao partuguesa)
@c
@c Copyright (c) 2005 by FlashCode <flashcode@flashtux.org>
@c
@c This manual is free software; you can redistribute it and/or modify
@c it under the terms of the GNU General Public License as published by
@c the Free Software Foundation; either version 2 of the License, or
@c (at your option) any later version.
@c
@c This manual is distributed in the hope that it will be useful,
@c but WITHOUT ANY WARRANTY; without even the implied warranty of
@c MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
@c GNU General Public License for more details.
@c
@c You should have received a copy of the GNU General Public License
@c along with this program; if not, write to the Free Software
@c Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

@c pdf : texi2pdf weechat_doc_pt.texi
@c html: makeinfo --html --no-split --number-sections weechat_doc_pt.texi

@c tex
@c \overfullrule=0pt
@c end tex

@documentlanguage pt

@titlepage

@title WeeChat - Guia do Utilizador
@subtitle Cliente de IRC rapido, leve e extencivel
@subtitle Documenta@,{c}@~ao do WeeChat v0.1.0-cvs - 23 de Janeiro de 2005

@image{weechat_image}

@author FlashCode <@email{flashcode@@flashtux.org, flashcode AT flashtux.org}>

@page

Este manual documenta o cliente de IRC WeeChat, ele faz parte do WeeChat.@*
@*
A ultima versão deste documento pode ser descarregada de :@*
@uref{http://weechat.flashtux.org/doc.php}@*
@*
Copyright @copyright{} 2005 FlashCode
<@email{flashcode@@flashtux.org, flashcode AT flashtux.org}>@*
@*
Este documento pode ser utilizado sobre os termos da Licen@,{c}a P@'ublica geral GNU (GNU General Public
License) vers@~ao 2 ou superior.

@end titlepage

@everyheading @thischapter @| @|
@everyfooting @thistitle @| @| Pagina @thispage

@contents

@node Top, Introducao, (dir), (dir)
@menu
* Introducao:: Descri@,{c}@~ao do WeeChat
* Instalacao:: Instala@,{c}@~ao do WeeChat
* Utilizacao:: Utiliza@,{c}@~ao do WeeChat
* Extencoes:: Exten@,{c}@~oes do Weechat
* Autores/Suporte:: Contactar os autores e obter suporte
@end menu


@c ******************************* Introducao *******************************

@node Introducao, Instalacao, Top, Top
@chapter Introdu@,{c}@~ao
@menu
* Descricao::
* Pre-requisitos::
@end menu

@node Descricao, Pre-requisitos, Introducao, Introducao
@section Descri@,{c}@~ao

O WeeChat (Wee Enhanced Environment for Chat) @'e um cliente de IRC livre, r@'apido e leve,
concebido para funcionar em diversos sistemas operativos.@*
@*
As suas caracter@'isticas prinicpais s@~ao as seguintes :
@itemize @minus
@item
liga@,{c}@~ao a m@'ultiplos servidores
@item
v@'arias interfaces : Curses, Gtk e Qt
@item
pequeno r@'apido e leve
@item
configuravel e extenc@'ivel com scripts
@item
compat@'ivel com RFCs 1459, 2810, 2811, 2812, e 2813
@item
multiplataforma (Gnu/Linux, *BSD, Windows e outros)
@item
100% GPL, Software Livre
@end itemize

@*
A p@'agina Web do Weechat @'e aqui :@*
@uref{http://weechat.flashtux.org}@*

@node Pre-requisitos, ,Descricao, Introducao
@section Pr@'e-requisitos

Para instalar o Weechat, vais @b{precisar} de ter :@*

@itemize @bullet
@item
Um sistema Gnu/Linux (com um compilador e outros utilit@'arios associados aos pacotes de c@'odigo fonte)
@item
Direitos de "root" (para instalar)
@item
Consoante a interface escolhida, uma das seguintes bibliotecas :
@itemize @minus
@item
Curses: a biblioteca ncurses,
@item
Gtk: *** interface n@~ao desenvolvida ***,
@item
Qt: *** interface n@~ao desenvolvida ***,
@end itemize
@end itemize


@c ******************************* Instalacao *******************************

@node Instalacao, Utilizacao, Introducao, Top
@chapter Instala@,{c}@~ao
@menu
* Binarios::
* Codigo Fonte::
* Codigo Fonte via CVS::
@end menu

@node Binarios, Codigo Fonte, Instalacao, Instalacao
@section Bin@'arios

Os pacotes bin@'arios est@'ao dispon@'iveis para as seguintes distribui@,{c}@~oes :
@itemize @bullet
@item
Debian (ou compat@'ivel)@*
Instala@,{c}@~ao : @kbd{dpkg -i /chemin/weechat_x.y.z-1_i386.deb}
@item
Mandrake/Redhat (ou outra distro compat@'ivel com RPMs)@*
Instala@,{c}@~ao : @kbd{rpm -i /chemin/weechat-x.y.z-1.i386.rpm}
@item
Gentoo@*
Instala@,{c}@~ao : @kbd{emerge weechat}
@item
*BSD (non disponible !)
@item
Slackware (n@~ao dispon@'ivel !)
@item
Windows (n@~ao dispon@'ivel !)
@end itemize

Onde x.y.z @'e a vers@~ao (por exemplo 0.0.1)
@*

@node Codigo Fonte, Codigo Fonte via CVS, Binarios, Instalacao
@section C@'odigo Fonte

Escreve simplesmente numa consola ou num terminal :@*
@kbd{./configure}@*
@kbd{make}@*
Nota: Para compilar certas interfaces, podes passar par@^ametros
ao ./configure, escreve @kbd{./configure --help} para veres as op@,{c}@~oes.@*

Obter os direitos do root e instalar o Weechat :@*
@kbd{su}@*
(escreve aqui a palavra-passe do superutilizador)@*
@kbd{make install}@*

@node Codigo Fonte via CVS, , Codigo Fonte, Instalacao
@section C@'odigo Fonte via CVS

Aten@,{c}@~ao: o c@'odigo fonte CVS est@'a reservado aos utilizadores avan@,{c}ados : o WeeChat pode n@~ao compilar ou ficar inst@'avel.@*
Considera-te avisado !@*

Para sacares o c@'odigo fonte via CVS, escreve estes comandos :@*
@kbd{cvs -d:pserver:anoncvs@@subversions.gnu.org:/cvsroot/weechat login}@*
@kbd{cvs -z3 -d:pserver:anoncvs@@subversions.gnu.org:/cvsroot/weechat co weechat}@*
(quando te pedirem a palavra-passe, primen simplesmente Enter)@*

Executa o script :@*
@kbd{./autogen.sh}@*

Segue agora as instru@,{c}@~oes para compilar o c@'odigo fonte - @xref{Codigo Fonte}.


@c ******************************* Utilizacao ********************************

@node Utilizacao, Extencoes, Instalacao, Top
@chapter Utiliza@,{c}@~ao

@menu
* Invocar o WeeChat::
* Recursos de teclado::
* Comandos do WeeChat::
@end menu

@node Invocar o WeeChat, Recursos de teclado, Utilizacao, Utilizacao
@section Invocar o WeeChat

@subsection Par@^ametros de linha de comandos

@table @code
@item -c, --config
Mostrar da lima dos config da exposi@,{c}@~ao (lista das op@,{c}@~oes)
@item -h, --help
Mostrar a ajuda@*
@item -l, --license
Mostrar a licen@,{c}a do WeeChat@*
@item -v, --version
Mostrar a vers@~ao do WeeChat@*
@end table

@subsection Invocar o WeeChat

Escreve simplesmente este comando para invoceres o WeeChat :@*
@kbd{weechat-curses} (para a interface em Curses)@*
ou @kbd{weechat-gtk} (para a interface em Gtk)@*
ou @kbd{weechat-qt} (para a interface em Qt)@*

Logo que lan@,{c}ares o WeeChat pela primeira vez, um ficheiro de configura@,{c}@~ao
por defeito @'e criado, com as configura@,{c}@~oes por defeito.@*
O ficheiro de configura@,{c}@~ao por defeito @'e : ~/.weechat/weechat.rc@*

Podes editar esse ficheiro para configurar o WeeChat @`a tua maneira, man tamb@'em podes modificar os par@^ametros dentro do WeeChat utilizando o comando @kbd{/set} - @xref{Comandos do WeeChat}.

@node Recursos de teclado, Comandos do WeeChat, Invocar o WeeChat, Utilizacao
@section Recursos de teclado

@table @kbd
@item Seta esquerda / Seta direita
Ir um caractere para traz / para a frente na linha de comando@*
@*
@item Ctrl + Seta esquerda / Ctrl + Seta Direita
Ir uma palavra para traz / para a frente na linha de comando@*
@*
@item Home / Ctrl + A
Ir para o in@'icio da linha de comando@*
@*
@item End / Ctrl + E
Ir para o fim da linha de comando@*
@*
@item Backspace / Delete
Apagar o caractere anterior / seguinte na linha de comando@*
@*
@item Ctrl + Backspace / Ctrl + W
Apagar a palavra anterior na linha de comando
@*
@item Tab
Completar o comando ou o nick (@kbd{Tab} novamente : encontrar a pr@'oxima sugest@~ao)@*
@*
@item Qualquer caractere
Inserir o caractere na linha de comando, no s@'itio do cursor@*
@*
@item Enter
Executa o comando ou envia a mensagem@*
@*
@item Seta para cima / Seta para baixo
Repetir os ultimos comandos/mensagens@*
@*
@item PageUp / PageDown
Navegar no hist@'orico da janela@*
@*
@item F6 / F7
Ir para a janela anterior/seguinte@*
@*
@item F8
Comute @`a janela seguinte@*
@*
@item F10
Apagar a @'ultima mensagem da barra do info@*
@*
@item Ctrl + L
Redesenhe a janela inteira@*
@*
@item Alt + Seta da esquerda / Alt + Seta da direita
Identico a F6 / F7@*
@*
@item Alt + A
Comute ao amortecedor seguinte com atividade (com prioridade:  destaque, mensagem, outra)@*
@*
@item Alt + D
Exposi@,{c}@~ao DCC atual@*
@*
@item Alt + R
Hotlist desobstru@'ido (notifica@,{c}@~ao da atividade em outros amortecedores)@*
@*
@item Alt + S
Comute ao amortecedor do servidor@*
@*
@item Alt + X
Comute @`a primeira canaleta do servidor seguinte (ou do amortecedor do servidor se nenhuma canaleta for aberta)@*
@*
@item Alt + d@'igito (1-9)
Comute ao amortecedor pelo n@'umero@*
@*
@end table

@node Comandos do WeeChat, , Recursos de teclado, Utilizacao
@section Comandos do WeeChat

N@~AO ESCRITO !


@c ******************************* Extencoes *********************************

@node Extencoes, Autores/Suporte, Utilizacao, Top
@chapter Exten@,{c}@~oes

@menu
* Scripts Perl::
* Scripts Python::
* Scripts Ruby::
@end menu

@node Scripts Perl, Scripts Python, Extencoes, Extencoes
@section Scripts Perl

@subsection Carregar/Descarregar Scripts Perl

Os Scripts Perl s@~ao carregados e descarregados com o comando @command{/perl}.
(escreve @kbd{/help perl} dentro do WeeChat para obteres ajuda acerca do comando).@*

@emph{Exemplos:}@*
@itemize @bullet
@item
Carregar um Script Perl: @kbd{/perl load /tmp/sample.pl}@*
@item
Descarregar todos os Scripts Perl: @kbd{/perl unload}@*
@item
Listar todos os Scripts Perl: @kbd{/perl}@*
@end itemize

@subsection Interface WeeChat / Perl

@itemize @bullet
@item
@command{IRC::register ( nome, vers@~ao, fun@,{c}@~ao_de_shutdown, descri@,{c}@~ao );}@*
@*
Esta @'e a primeira fun@,{c}@~ao a invocar num Script Perl.@*
Todos os Scripts Perl para o Weechat devem invocar esta fun@,{c}@~ao.@*

@emph{Argumentos:}
@itemize @minus
@item @option{nome}: nome @'unico que indentifique o script (cada Script Perl deve ter um @'unico nome)
@item @option{vers@~ao}: vers@~ao do script
@item @option{fun@,{c}@~ao_de_shutdown}: fun@,{c}@~ao Perl invocada quando o script é descarregado (par@^ametro opcional, se deixado em branco significa que nada deve ser chamado)
@item @option{descri@,{c}@~ao}: breve descri@,{c}@~ao do script.
@end itemize
@*
@emph{Exemplo:}@*
@code{IRC::register ("sample", "1.0", "sample_end", "Sample script!");}@*
@*

@item
@command{IRC::print ( mensagem );}@*
@*
Imprimne uma mensagem na janela actual (canal ou servidor).@*

@emph{Argumentos:}
@itemize @minus
@item @option{mensagem}: mensagem a mostrar
@end itemize
@*
@emph{Exemplo:}@*
@code{IRC::print ("mensagem");}@*
@*

@item
@command{IRC::print_with_channel ( canal, [servidor,] mensagem );}@*
@*
Imprimne uma mensagem na canal.@*

@emph{Argumentos:}
@itemize @minus
@item @option{canal}: nome da canal
@item @option{servidor}: nome interno da servidor
@item @option{mensagem}: mensagem a mostrar
@end itemize
@*
@emph{Exemplos:}@*
@code{IRC::print_with_channel ("#weechat", "freenode", "mensagem");}@*
@code{IRC::print_with_channel ("#weechat", "mensagem");}@*
@*

@item
@command{IRC::print_infobar ( atrasa, mensagem );}@*
@*
Imprimne uma mensagem na barra do info.@*

@emph{Argumentos:}
@itemize @minus
@item @option{atrasa}: depois que isto atrasa (nos segundos), a mensagem estar@'a apagada
(se 0, mensagem n@~ao forem apagados).
@item @option{mensagem}: mensagem a mostrar
@end itemize
@*
@emph{Exemplo:}@*
@code{IRC::print_infobar (5, "mensagem");}@*
@*

@item
@command{IRC::add_message_handler ( nome, fun@,{c}@~ao );}@*
@*
Anexa uma fun@,{c}@~ao Perl a uma mensagem de IRC.@*
A fun@,{c}@~ao ser@'a invocada de cada vez que a mensagem IRC for recebida.@*

@emph{Argumentos:}
@itemize @minus
@item @option{nome}: nome da mensagem IRC@*
Para conheceres uma lista de mensagens de IRC, por favor lê o RFC 1459 e/ou o 2812:@*
RFC 1459: @uref{ftp://ftp.rfc-editor.org/in-notes/rfc1459.txt}@*
RFC 2812: @uref{ftp://ftp.rfc-editor.org/in-notes/rfc2812.txt}
@item @option{fun@,{c}@~ao}: fun@,{c}@~ao Perl invocada quando a mensagem é recebida
@end itemize
@*
@emph{Exemplo:}@*
@code{IRC::add_message_handler ("privmsg", my_function);}@*
@code{sub my_function}@*
@code{@{ }@*
@code{@ @ @ @ ($null, $channel, $message) = split ":",@@_[0],3;}@*
@code{@ @ @ @ ($hostmask, $null, $channel) = split " ", $channel;}@*
@code{@ @ @ @ IRC::print ("host=$hostmask, chan=$channel, msg=$message\n");}@*
@code{@} }@*
@*

@item
@command{IRC::add_command_handler ( nome, fun@,{c}@~ao );}@*
@*
Cria um novo comando do Weechat, ligado a uma fun@,{c}@~ao Perl.@*
A fun@,{c}@~ao ser@'a chamada quando o utilizador a invocar utilizando @command{/nome}@*

@emph{Argumentos:}
@itemize @minus
@item @option{nome}: nome do novo comando@*
Este nome pode pertencer a um comando já existente, o qual ser@'a sobreposto pela fun@,{c}@~ao Perl. Tem cuidado quando fizeres isto: os comandos originais não estar@~ao acessiveis antes de teres descarregado o Script Perl.
@item @option{fun@,{c}@~ao}: fun@,{c}@~ao Perl ligada ao comando
@end itemize
@*
@emph{Exemplo:}@*
@code{IRC::add_command_handler ("command", my_command);}@*
@code{sub my_command}@*
@code{@{ }@*
@code{@ @ @ @ IRC::print("Argumentos: ".@@_[0]);}@*
@code{@ @ @ @ return 0;}@*
@code{@} }@*
@*

@item
@command{IRC::get_info ( [servidor,] nome );}@*
@*
Comece o v@'ario info sobre WeeChat, servidor ou usu@'ario.@*

@emph{Argumentos:}
@itemize @minus
@item @option{servidor}: nome interno da servidor
@item @option{nome}: nome do info a recuperar:
@itemize @minus
@item @option{0 ou version}: comece a vers@~ao de WeeChat
@item @option{1 ou nick}: comece o nickname
@item @option{2 ou channel}: comece o nome da canal
@item @option{3 ou server}: comece o nome do servidor
@item @option{4 ou weechatdir}: comece a WeeChat o diret@'orio home
@item @option{5 ou away}: comece a bandeira ausente para o servidor
@end itemize
@end itemize
@*
@emph{Exemplos:}@*
@code{$version = get_info("version");}@*
@code{$nick = get_info("freenode", "nick");}@*
@*

@end itemize

@node Scripts Python, Scripts Ruby, Scripts Perl, Extencoes
@section Scripts Python

N@~AO DESENVOLVIDO!

@node Scripts Ruby, , Scripts Python, Extencoes
@section Scripts Ruby

N@~AO DESENVOLVIDO!


@c **************************** Autores/Suporte *****************************

@node Autores/Suporte, , Extencoes, Top
@chapter Autores / Suporte

@ifhtml
@menu
* Autores::
* Obter Suporte::
* Copyright::
@end menu
@end ifhtml
@ifnothtml
@menu
* Autores::
* Obter Suporte::
@end menu
@end ifnothtml

@node Autores, Obter Suporte, Autores/Suporte, Autores/Suporte
@section Autores

O WeeChat @'e desenvolvido por :@*

@itemize @bullet
@item 
FlashCode
<@email{flashcode@@flashtux.org, flashcode AT flashtux.org}>
@item
Bounga
<@email{bounga@@altern.org, bounga AT altern.org}>
@item
Xahlexx
<@email{xahlexx@@tuxfamily.org, xahlexx AT tuxfamily.org}>

@end itemize

@ifhtml
@node Obter Suporte, Copyright, Autores, Autores/Suporte
@end ifhtml
@ifnothtml
@node Obter Suporte, , Autores, Autores/Suporte
@end ifnothtml
@section Obter Suporte

Antes de pedires suporte, agradecemos se leres toda a documenta@,{c}@~ao e a FAQ.@*
(a documenta@,{c}@~ao @'e este documento que est@'as a ler, se n@~ao leste tudo at@'e aqui, est@'a na hora de come@,{c}ares do in@'icio !)@*

@itemize @bullet
@item
Suporte por IRC:@*
- servidor : @b{irc.freenode.net}@*
- canal : @b{#weechat}@*@*
@item
Forum do WeeChat : @uref{http://forums.flashtux.org}@*@*
@item
Suporte por lista de correio-e :@*
- para te inscreveres/desinscreveres :@*@uref{http://mail.nongnu.org/mailman/listinfo/weechat-support}.@*
- para enviares uma mensagem para a lista :@*@email{weechat-support@@nongnu.org}.@*

Os arquivos da lista est@~ao aqui :@*
@uref{http://mail.nongnu.org/archive/html/weechat-support}@*@*
@item
Para mais detalhes, v@^e tamb@'em a p@'agina de suporte do WeeChat :@*
@uref{http://weechat.flashtux.org/support.php}

@end itemize

@ifhtml
@node Copyright, , Obter Suporte, Autores/Suporte
@section Copyright

Este manual documenta o cliente de IRC WeeChat, Ele faz parte do WeeChat.@*

Copyright @copyright{} 2005 FlashCode
<@email{flashcode@@flashtux.org, flashcode AT flashtux.org}>@*
Tradu@,{c}@~ao portuguesa de Jo@~ao Jer@'onimo <@email{j_j_b_o@@sapo.pt, j_j_b_o AT sapo.pt}>@*
@*
A utiliza@,{c}@~ao deste documento @'e regida pela GNU General Public
License vers@~ao 2 ou posterior.@*

@end ifhtml

@bye

