= Guide pour scripts WeeChat
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: fr
:toc-title: Table des matières

Ce manuel documente le client de messagerie instantanée WeeChat, il fait
partie de WeeChat.

La dernière version de ce document peut être téléchargée sur
https://weechat.org/doc/[cette page ^↗^^].

[[introduction]]
== Introduction

WeeChat (Wee Enhanced Environment for Chat) est un client de discussion libre,
rapide et léger, conçu pour différents systèmes d'exploitation.

Ce manuel documente la façon d'écrire des scripts pour WeeChat, en utilisant
l'un des langages de script supportés :

* Python
* Perl
* Ruby
* Lua
* Tcl
* Guile (Scheme)
* JavaScript
* PHP

[NOTE]
La majorité des exemples de cette documentation sont écrits en Python, mais
l'API est la même pour les autres langages.

[[scripts_in_weechat]]
== Scripts dans WeeChat

[[weechat_architecture]]
=== Architecture de WeeChat

WeeChat tourne dans un seul thread, et ceci est valable pour les scripts
également.

Le code d'un script est exécuté :

* lorsque le script est chargé : typiquement un appel à la
  <<register_function,fonction register>>
* lorsque la fonction de rappel d'un "hook" est appelée par WeeChat
  (voir le chapitre <<hooks,Hooks>>).

Lorsque le code du script est exécuté, WeeChat attend la fin de l'exécution
avant de continuer. Par conséquent, le script ne doit *PAS* faire d'opérations
bloquantes comme des appels réseau sans utiliser une fonction API dédiée
telle que `+hook_process+`.

[IMPORTANT]
Un script ne doit *JAMAIS* faire de "fork" ou créer des threads sans utiliser
une fonction dédiée de l'API, cela pourrait provoquer un crash de WeeChat. +
Si quelque chose doit être lancé en arrière-plan, la fonction `+hook_process+`
peut être utilisée. Voir l'exemple dans le chapitre
<<hook_process,Lancer un processus en tâche de fond>> et la documentation sur
la fonction `+hook_process+` dans la
link:weechat_plugin_api.fr.html#_hook_process[Référence API extension WeeChat ^↗^^].

[[languages_specificities]]
=== Spécificités des langages

[[language_python]]
==== Python

[[python_module]]
===== Module

WeeChat définit un module `weechat` qui doit être importé avec `import weechat`. +
Un "stub" Python pour l'API WeeChat est disponible dans le dépôt :
https://raw.githubusercontent.com/weechat/weechat/master/src/plugins/python/weechat.pyi[weechat.pyi ^↗^^].

[[python_functions]]
===== Fonctions

Les fonctions sont appelées avec `+weechat.xxx(arg1, arg2, ...)+`.

Les fonctions `+print*+` se nomment `+prnt*+` en python (car `print` était un
mot clé réservé en Python 2).

[[python_strings]]
===== Chaînes reçues dans les fonctions de rappel

En Python 3 et avec WeeChat ≥ 2.7, les chaînes reçues dans les fonctions de
rappel ont le type `str` si la chaîne a des données valides UTF-8 (ce qui est
le cas le plus courant) ou `bytes` si la chaîne n'est pas valide UTF-8. Donc la
fonction de rappel doit prendre en compte ce type si des données non valides
UTF-8 peuvent être reçues.

Des données invalides UTF-8 peuvent être reçues dans ces cas, donc la fonction
de rappel peut recevoir une chaîne de type `str` ou `bytes` (cette liste n'est
pas exhaustive) :

[width="100%",cols="3m,3m,3m,8",options="header"]
|===
| Fonction API | Paramètres | Exemples | Description

| hook_modifier
| irc_in_yyy
| pass:[irc_in_privmsg] +
  pass:[irc_in_notice]
| Un message reçu dans l'extension IRC, avant qu'il ne soit décodé vers UTF-8. +
  +
  Il est recommandé d'utiliser plutôt le modificateur `+irc_in2_yyy+`, la chaîne
  reçue sera toujours valide UTF-8. +
  Voir la fonction `+hook_modifier+` dans la
  link:weechat_plugin_api.fr.html#_hook_modifier[Référence API extension WeeChat ^↗^^].

| hook_signal
| xxx,irc_out_yyy +
  xxx,irc_outtags_yyy
| pass:[*,irc_out_privmsg] +
  pass:[*,irc_out_notice] +
  pass:[*,irc_outtags_privmsg] +
  pass:[*,irc_outtags_notice]
| Un message envoyé par l'extension IRC, après encodage vers le jeu de caractères
  `encode` défini par l'utilisateur (si différent de `UTF-8`, qui est la valeur
  par défaut). +
  +
  Il est recommandé d'utiliser plutôt le signal `+xxx,irc_out1_yyy+`, la chaîne
  reçue sera toujours valide UTF-8. +
  Voir la fonction `+hook_signal+` dans la
  link:weechat_plugin_api.fr.html#_hook_signal[Référence API extension WeeChat ^↗^^].

| hook_process +
  hook_process_hashtable
| -
| -
| La sortie de la commande, envoyée à la fonction de rappel, peut contenir des
  données invalides UTF-8.

|===

[[language_perl]]
==== Perl

[[perl_functions]]
===== Fonctions

Les fonctions sont appelées par `+weechat::xxx(arg1, arg2, ...);+`.

[[language_ruby]]
==== Ruby

[[ruby_init]]
===== Initialisation

Vous devez définir _weechat_init_ et appeler _register_ dedans.

[[ruby_functions]]
===== Fonctions

Les fonctions sont appelées par `+Weechat.xxx(arg1, arg2, ...)+`.

En raison d'une limitation de Ruby (15 paramètres maximum par fonction), la
fonction `+Weechat.config_new_option+` reçoit les fonctions de rappel dans un
tableau de 6 chaînes de caractères (3 fonctions de rappel + 3 chaînes de
données), donc un appel à cette fonction ressemble à ceci :

[source,ruby]
----
Weechat.config_new_option(config, section, "name", "string", "description of option", "", 0, 0,
                          "value", "value", 0, ["check_cb", "", "change_cb", "", "delete_cb", ""])
----

Et la fonction `+Weechat.bar_new+` reçoit les couleurs dans un tableau de 4
chaînes de caractères (color_fg, color_delim, color_bg, color_bg_inactive),
donc un appel à cette fonction ressemble à ceci :

[source,ruby]
----
Weechat.bar_new("name", "off", "0", "window", "", "left", "vertical", "vertical", "0", "0",
                ["default", "default", "default", "default"], "0", "items")
----

[[language_lua]]
==== Lua

[[lua_functions]]
===== Fonctions

Les fonctions sont appelées par `+weechat.xxx(arg1, arg2, ...)+`.

[[language_tcl]]
==== Tcl

[[tcl_functions]]
===== Fonctions

Les fonctions sont appelées par `+weechat::xxx arg1 arg2 ...+`.

[[tcl_null]]
===== Null values

Puisque Tcl n'a que des types "string", il n'y a pas de type "null" à passer
comme paramètre lorsqu'une fonction accepte des valeurs "null" ou pour recevoir
comme paramètre dans une fonction de rappel. Pour y remédier, l'API WeeChat
définit la constante `$::weechat::WEECHAT_NULL` qui agit comme une valeur
"null". Cette constante est définie avec la valeur
`\uFFFF\uFFFF\uFFFFWEECHAT_NULL\uFFFF\uFFFF\uFFFF`, donc il est très peu probable
qu'elle apparaisse involontairement.

Vous pouvez passer cette constante lorsqu'une fonction accepte "null" comme
paramètre et vous la recevrez comment valeur d'un paramètre de fonction de rappel
si la valeur du paramètre est "null". Pour voir quelles fonctions acceptent des
valeurs "null" et passent des valeurs "null" aux fonctions de rappel, regardez
les prototypes Python dans la
link:weechat_plugin_api.fr.html[Référence API extension WeeChat ^↗^^].

[[language_guile]]
==== Guile (Scheme)

[[guile_functions]]
===== Fonctions

Les fonctions sont appelées par `+(weechat:xxx arg1 arg2 ...)+`.

Les fonctions suivantes prennent une liste de paramètres en entrée (au lieu de
plusieurs paramètres pour les autres fonctions), car le nombre de paramètres
excède la limite de Guile :

* config_new_section
* config_new_option
* bar_new

[[language_javascript]]
==== JavaScript

[[javascript_functions]]
===== Fonctions

Les fonctions sont appelées par `+weechat.xxx(arg1, arg2, ...);+`.

[[language_php]]
==== PHP

[[php_functions]]
===== Fonctions

Les fonctions sont appelées par `+weechat_xxx(arg1, arg2, ...);+`.

[[register_function]]
=== Fonction register

Tous les scripts WeeChat doivent s'enregistrer ("register") auprès de WeeChat,
et cela doit être la première fonction WeeChat appelée dans le script.

Prototype (Python) :

[source,python]
----
def register(name: str, author: str, version: str, license: str, description: str, shutdown_function: str, charset: str) -> int: ...
----

Paramètres :

* _name_ : chaîne, nom interne du script
* _author_ : chaîne, nom de l'auteur
* _version_ : chaîne, version du script
* _license_ : chaîne, licence du script
* _description_ : chaîne, description courte du script
* _shutdown_function_ : chaîne, nom de la fonction appelée lorsque le script
  est déchargé (peut être une chaîne vide)
* _charset_ : chaîne, jeu de caractères du script (si votre script est UTF-8,
  vous pouvez utiliser une valeur vide ici, car UTF-8 est le jeu de caractères
  par défaut)

Exemple, pour chaque langage :

* Python :

[source,python]
----
import weechat

weechat.register("test_python", "FlashCode", "1.0", "GPL3", "Script de test", "", "")
weechat.prnt("", "Bonjour, du script python !")
----

* Perl :

[source,perl]
----
weechat::register("test_perl", "FlashCode", "1.0", "GPL3", "Script de test", "", "");
weechat::print("", "Bonjour, du script perl !");
----

* Ruby :

[source,ruby]
----
def weechat_init
  Weechat.register("test_ruby", "FlashCode", "1.0", "GPL3", "Script de test", "", "")
  Weechat.print("", "Bonjour, du script ruby !")
  return Weechat::WEECHAT_RC_OK
end
----

* Lua :

[source,lua]
----
weechat.register("test_lua", "FlashCode", "1.0", "GPL3", "Script de test", "", "")
weechat.print("", "Bonjour, du script lua !")
----

* Tcl :

[source,tcl]
----
weechat::register "test_tcl" "FlashCode" "1.0" "GPL3" "Script de test" "" ""
weechat::print "" "Bonjour, du script tcl !"
----

* Guile (Scheme) :

[source,lisp]
----
(weechat:register "test_scheme" "FlashCode" "1.0" "GPL3" "Script de test" "" "")
(weechat:print "" "Bonjour, du script scheme !")
----

* JavaScript :

[source,javascript]
----
weechat.register("test_js", "FlashCode", "1.0", "GPL3", "Script de test", "", "");
weechat.print("", "Bonjour, du script javascript !");
----

* PHP :

[source,php]
----
weechat_register('test_php', 'FlashCode', '1.0', 'GPL3', 'Script de test', '', '');
weechat_print('', 'Bonjour, du script PHP !');
----

[[load_script]]
=== Chargement du script

Il est recommandé d'utiliser l'extension "script" pour charger les scripts,
par exemple :

----
/script load script.py
/script load script.pl
/script load script.rb
/script load script.lua
/script load script.tcl
/script load script.scm
/script load script.js
/script load script.php
----

Chaque langage a également sa propre commande :

----
/python load script.py
/perl load script.pl
/ruby load script.rb
/lua load script.lua
/tcl load script.tcl
/guile load script.scm
/javascript load script.js
/php load script.php
----

Vous pouvez faire un lien dans le répertoire _langage/autoload_ pour charger
automatiquement le script quand WeeChat démarre.

Par exemple en Python :

----
$ cd ~/.local/share/weechat/python/autoload
$ ln -s ../script.py
----

[NOTE]
Lors de l'installation d'un script avec la commande `/script install` le lien
dans le répertoire _autoload_ est automatiquement créé.

[[differences_with_c_api]]
== Différences avec l'API C

L'API script est quasiment identique à l'API C.
Vous pouvez consulter la link:weechat_plugin_api.fr.html[Référence API extension WeeChat ^↗^^]
pour le détail de chaque fonction de l'API : prototype, paramètres, valeurs
de retour, exemples.

Il est important de bien faire la différence entre une _extension_ et un
_script_ : une _extension_ est un fichier binaire compilé et chargé avec la
commande `/plugin`, tandis qu'un _script_ est un fichier texte chargé par une
extension comme _python_ par la commande `/python`.

Quand votre script _test.py_ appelle une fonction de l'API WeeChat, le chemin
est le suivant :

....
               ┌──────────────────────┐        ╔══════════════════╗
               │   extension python   │        ║  WeeChat "core"  ║
               ├────────────┬─────────┤        ╟─────────┐        ║
test.py ─────► │ API script │  API C  │ ─────► ║  API C  │        ║
               └────────────┴─────────┘        ╚═════════╧════════╝
....

Quand WeeChat appelle une fonction de rappel dans votre script _test.py_, le chemin
est inversé :

....
╔══════════════════╗        ┌──────────────────────┐
║  WeeChat "core"  ║        │   extension python   │
║        ┌─────────╢        ├─────────┬────────────┤
║        │  API C  ║ ─────► │  API C  │ API script │ ─────► test.py
╚════════╧═════════╝        └─────────┴────────────┘
....

[[pointers]]
=== Pointeurs

Comme vous le savez probablement, il n'y a pas vraiment de "pointeurs" dans les
scripts. Donc quand les fonctions de l'API retournent un pointeur, il est
converti en chaîne pour le script.

Par exemple, si une fonction retourne le pointeur 0x1234ab56, le script recevra
la chaîne "0x1234ab56".

Et quand une fonction de l'API attend un pointeur dans ses paramètres, le
script doit envoyer cette valeur sous forme de chaîne. L'extension C la
convertira en pointeur réel avant d'appeler la fonction de l'API C.

Une chaîne vide ou "0x0" sont autorisées, cela signifie le pointeur NULL en C.
Par exemple, pour afficher un message sur le tampon core (tampon principal
WeeChat), vous pouvez faire :

[source,python]
----
weechat.prnt("", "bonjour !")
----

[WARNING]
Dans beaucoup de fonctions, pour des raisons de vitesse, WeeChat ne vérifie pas
si votre pointeur est correct ou pas. Il est de votre responsabilité de
vérifier que vous donnez un pointeur valide, sinon vous pourriez voir un joli
rapport de crash ;)

[[callbacks]]
=== Fonctions de rappel

Toutes les fonction de rappel WeeChat doivent retourner WEECHAT_RC_OK ou
WEECHAT_RC_ERROR (l'exception est la fonction de rappel du modificateur, qui
retourne une chaîne de caractères).

Les fonctions de rappel C utilisent des paramètres "callback_pointer" et
"callback_data", qui sont des pointeurs. Dans l'API script, il y a seulement
"callback_data" (ou "data"), et il s'agit d'une chaîne de caractères au lieu
d'un pointeur.

Exemple de fonction de rappel, pour chaque langage :

* Python :

[source,python]
----
def timer_cb(data, remaining_calls):
    weechat.prnt("", "timer! data=%s" % data)
    return weechat.WEECHAT_RC_OK

weechat.hook_timer(1000, 0, 1, "timer_cb", "test")
----

* Perl :

[source,perl]
----
sub timer_cb {
    my ($data, $remaining_calls) = @_;
    weechat::print("", "timer! data=$data");
    return weechat::WEECHAT_RC_OK;
}

weechat::hook_timer(1000, 0, 1, "timer_cb", "test");
----

* Ruby :

[source,ruby]
----
def timer_cb(data, remaining_calls)
  Weechat.print("", "timer! data=#{data}");
  return Weechat::WEECHAT_RC_OK
end

Weechat.hook_timer(1000, 0, 1, "timer_cb", "test");
----

* Lua :

[source,lua]
----
function timer_cb(data, remaining_calls)
    weechat.print("", "timer! data="..data)
    return weechat.WEECHAT_RC_OK
end

weechat.hook_timer(1000, 0, 1, "timer_cb", "test")
----

* Tcl :

[source,tcl]
----
proc timer_cb { data remaining_calls } {
    weechat::print {} "timer! data=$data"
    return $::weechat::WEECHAT_RC_OK
}

weechat::hook_timer 1000 0 1 timer_cb test
----

* Guile (Scheme) :

[source,lisp]
----
(define (timer_cb data remaining_calls)
  (weechat:print "" (string-append "timer! data=" data))
  weechat:WEECHAT_RC_OK
)

(weechat:hook_timer 1000 0 1 "timer_cb" "test")
----

* JavaScript :

[source,javascript]
----
function timer_cb(data, remaining_calls) {
    weechat.print("", "timer! data=" + data);
    return weechat.WEECHAT_RC_OK;
}

weechat.hook_timer(1000, 0, 1, "timer_cb", "test");
----

* PHP :

[source,php]
----
$timer_cb = function ($data, $remaining_calls) {
    weechat_print('', 'timer! data=' . $data);
    return WEECHAT_RC_OK;
};

weechat_hook_timer(1000, 0, 1, $timer_cb, 'test');
----

[[script_api]]
== API script

Pour plus d'informations sur les fonctions de l'API, merci de consulter la
link:weechat_plugin_api.fr.html[Référence API extension WeeChat ^↗^^].

[[script_api_functions]]
=== Fonctions

Liste des fonctions de l'API script :

[width="100%",cols="1,5",options="header"]
|===
| Catégorie | Fonctions

| général
| register

| extensions
| plugin_get_name

| chaînes
| charset_set +
  iconv_to_internal +
  iconv_from_internal +
  gettext +
  ngettext +
  strlen_screen +
  string_match +
  string_match_list +
  string_has_highlight +
  string_has_highlight_regex +
  string_mask_to_regex +
  string_format_size +
  string_parse_size +
  string_color_code_size +
  string_remove_color +
  string_is_command_char +
  string_input_for_buffer +
  string_eval_expression +
  string_eval_path_home

| répertoires
| mkdir_home +
  mkdir +
  mkdir_parents

| listes triées
| list_new +
  list_add +
  list_search +
  list_search_pos +
  list_casesearch +
  list_casesearch_pos +
  list_get +
  list_set +
  list_next +
  list_prev +
  list_string +
  list_size +
  list_remove +
  list_remove_all +
  list_free

| fichiers de configuration
| config_new +
  config_new_section +
  config_search_section +
  config_new_option +
  config_search_option +
  config_string_to_boolean +
  config_option_reset +
  config_option_set +
  config_option_set_null +
  config_option_unset +
  config_option_rename +
  config_option_is_null +
  config_option_default_is_null +
  config_boolean +
  config_boolean_default +
  config_integer +
  config_integer_default +
  config_string +
  config_string_default +
  config_color +
  config_color_default +
  config_write_option +
  config_write_line +
  config_write +
  config_read +
  config_reload +
  config_option_free +
  config_section_free_options +
  config_section_free +
  config_free +
  config_get +
  config_get_plugin +
  config_is_set_plugin +
  config_set_plugin +
  config_set_desc_plugin +
  config_unset_plugin

| associations de touches
| key_bind +
  key_unbind

| affichage
| prefix +
  color +
  print (pour python : prnt) +
  print_date_tags (pour python : prnt_date_tags) +
  print_y (pour python : prnt_y) +
  print_y_date_tags (pour python : prnt_y_date_tags) +
  log_print

| hooks
| hook_command +
  hook_command_run +
  hook_timer +
  hook_fd +
  hook_process +
  hook_process_hashtable +
  hook_connect +
  hook_line +
  hook_print +
  hook_signal +
  hook_signal_send +
  hook_hsignal +
  hook_hsignal_send +
  hook_config +
  hook_completion +
  hook_modifier +
  hook_modifier_exec +
  hook_info +
  hook_info_hashtable +
  hook_infolist +
  hook_focus +
  hook_set +
  unhook +
  unhook_all

| tampons
| buffer_new +
  buffer_new_props +
  current_buffer +
  buffer_search +
  buffer_search_main +
  buffer_clear +
  buffer_close +
  buffer_merge +
  buffer_unmerge +
  buffer_get_integer +
  buffer_get_string +
  buffer_get_pointer +
  buffer_set +
  buffer_string_replace_local_var +
  buffer_match_list

| fenêtres
| current_window +
  window_search_with_buffer +
  window_get_integer +
  window_get_string +
  window_get_pointer +
  window_set_title

| liste des pseudos
| nicklist_add_group +
  nicklist_search_group +
  nicklist_add_nick +
  nicklist_search_nick +
  nicklist_remove_group +
  nicklist_remove_nick +
  nicklist_remove_all +
  nicklist_group_get_integer +
  nicklist_group_get_string +
  nicklist_group_get_pointer +
  nicklist_group_set +
  nicklist_nick_get_integer +
  nicklist_nick_get_string +
  nicklist_nick_get_pointer +
  nicklist_nick_set

| barres
| bar_item_search +
  bar_item_new +
  bar_item_update +
  bar_item_remove +
  bar_search +
  bar_new +
  bar_set +
  bar_update +
  bar_remove

| commandes
| command +
  command_options

| complétion
| completion_new +
  completion_search +
  completion_get_string +
  completion_list_add +
  completion_free

| infos
| info_get +
  info_get_hashtable

| infolists
| infolist_new +
  infolist_new_item +
  infolist_new_var_integer +
  infolist_new_var_string +
  infolist_new_var_pointer +
  infolist_new_var_time +
  infolist_get +
  infolist_next +
  infolist_prev +
  infolist_reset_item_cursor +
  infolist_search_var +
  infolist_fields +
  infolist_integer +
  infolist_string +
  infolist_pointer +
  infolist_time +
  infolist_free

| hdata
| hdata_get +
  hdata_get_var_offset +
  hdata_get_var_type_string +
  hdata_get_var_array_size +
  hdata_get_var_array_size_string +
  hdata_get_var_hdata +
  hdata_get_list +
  hdata_check_pointer +
  hdata_move +
  hdata_search +
  hdata_char +
  hdata_integer +
  hdata_long +
  hdata_string +
  hdata_pointer +
  hdata_time +
  hdata_hashtable +
  hdata_compare +
  hdata_update +
  hdata_get_string

| mise à jour
| upgrade_new +
  upgrade_write_object +
  upgrade_read +
  upgrade_close
|===

[[script_api_constants]]
=== Constantes

Liste des constantes de l'API script :

[width="100%",cols="1,5",options="header"]
|===

| Catégorie | Constantes

| codes retour
| `WEECHAT_RC_OK` (entier) +
  `WEECHAT_RC_OK_EAT` (entier) +
  `WEECHAT_RC_ERROR` (entier)

| fichiers de configuration
| `WEECHAT_CONFIG_READ_OK` (entier) +
  `WEECHAT_CONFIG_READ_MEMORY_ERROR` (entier) +
  `WEECHAT_CONFIG_READ_FILE_NOT_FOUND` (entier) +
  `WEECHAT_CONFIG_WRITE_OK` (entier) +
  `WEECHAT_CONFIG_WRITE_ERROR` (entier) +
  `WEECHAT_CONFIG_WRITE_MEMORY_ERROR` (entier) +
  `WEECHAT_CONFIG_OPTION_SET_OK_CHANGED` (entier) +
  `WEECHAT_CONFIG_OPTION_SET_OK_SAME_VALUE` (entier) +
  `WEECHAT_CONFIG_OPTION_SET_ERROR` (entier) +
  `WEECHAT_CONFIG_OPTION_SET_OPTION_NOT_FOUND` (entier) +
  `WEECHAT_CONFIG_OPTION_UNSET_OK_NO_RESET` (entier) +
  `WEECHAT_CONFIG_OPTION_UNSET_OK_RESET` (entier) +
  `WEECHAT_CONFIG_OPTION_UNSET_OK_REMOVED` (entier) +
  `WEECHAT_CONFIG_OPTION_UNSET_ERROR` (entier)

| listes triées
| `WEECHAT_LIST_POS_SORT` (chaîne) +
  `WEECHAT_LIST_POS_BEGINNING` (chaîne) +
  `WEECHAT_LIST_POS_END` (chaîne)

| hotlist
| `WEECHAT_HOTLIST_LOW` (chaîne) +
  `WEECHAT_HOTLIST_MESSAGE` (chaîne) +
  `WEECHAT_HOTLIST_PRIVATE` (chaîne) +
  `WEECHAT_HOTLIST_HIGHLIGHT` (chaîne)

| hook process
| `WEECHAT_HOOK_PROCESS_RUNNING` (entier) +
  `WEECHAT_HOOK_PROCESS_ERROR` (entier)

| hook connect
| `WEECHAT_HOOK_CONNECT_OK` (entier) +
  `WEECHAT_HOOK_CONNECT_ADDRESS_NOT_FOUND` (entier) +
  `WEECHAT_HOOK_CONNECT_IP_ADDRESS_NOT_FOUND` (entier) +
  `WEECHAT_HOOK_CONNECT_CONNECTION_REFUSED` (entier) +
  `WEECHAT_HOOK_CONNECT_PROXY_ERROR` (entier) +
  `WEECHAT_HOOK_CONNECT_LOCAL_HOSTNAME_ERROR` (entier) +
  `WEECHAT_HOOK_CONNECT_GNUTLS_INIT_ERROR` (entier) +
  `WEECHAT_HOOK_CONNECT_GNUTLS_HANDSHAKE_ERROR` (entier) +
  `WEECHAT_HOOK_CONNECT_MEMORY_ERROR` (entier) +
  `WEECHAT_HOOK_CONNECT_TIMEOUT` (entier) +
  `WEECHAT_HOOK_CONNECT_SOCKET_ERROR` (entier)

| hook signal
| `WEECHAT_HOOK_SIGNAL_STRING` (chaîne) +
  `WEECHAT_HOOK_SIGNAL_INT` (chaîne) +
  `WEECHAT_HOOK_SIGNAL_POINTER` (chaîne)
|===

[[common_tasks]]
== Tâches courantes

Ce chapitre montre quelques tâches courantes, avec des exemples.
Seule une partie de l'API est utilisée ici, pour une référence complète, voir la
link:weechat_plugin_api.fr.html[Référence API extension WeeChat ^↗^^].

[[buffers]]
=== Tampons

[[buffers_display_messages]]
==== Afficher des messages

Une chaîne vide est souvent utilisée pour travailler avec le tampon core WeeChat.
Pour les autres tampons, vous devez passer un pointeur (sous forme de chaîne,
voir <<pointers,pointeurs>>).

Exemples :

[source,python]
----
# afficher "bonjour" sur le tampon core
weechat.prnt("", "bonjour")

# afficher "bonjour" sur le tampon core, mais ne pas l'écrire dans le fichier de log
# (version ≥ 0.3.3 seulement)
weechat.prnt_date_tags("", 0, "no_log", "bonjour")

# afficher le préfixe "==>" et le message "bonjour" sur le tampon courant
# (le préfixe et le message doivent être séparés par une tabulation)
weechat.prnt(weechat.current_buffer(), "==>\tbonjour")

# afficher un message d'erreur sur le tampon core (avec le préfixe d'erreur)
weechat.prnt("", "%smauvais paramètres" % weechat.prefix("error"))

# afficher un message avec de la couleur sur le tampon core
weechat.prnt("", "texte %sjaune sur bleu" % weechat.color("yellow,blue"))

# chercher un tampon et afficher un message
# (le nom complet d'un tampon est extension.nom, par exemple : "irc.libera.#weechat")
buffer = weechat.buffer_search("irc", "libera.#weechat")
weechat.prnt(buffer, "message sur le canal #weechat")

# autre solution pour chercher un tampon IRC (meilleure)
# (notez que le serveur et le canal sont séparés par une virgule)
buffer = weechat.info_get("irc_buffer", "libera,#weechat")
weechat.prnt(buffer, "message sur le canal #weechat")
----

[NOTE]
La fonction d'affichage est appelée `prnt` en Python et `print` dans les autres
langages.

[[buffers_send_text]]
==== Envoyer du texte au tampon

Vous pouvez envoyer du texte ou une commande à un tampon. C'est exactement comme
si vous tapiez le texte sur la ligne de commande et que vous pressiez [Enter].

Exemples :

[source,python]
----
# exécuter la commande "/help" sur le tampon courant (le résultat est sur le tampon core)
weechat.command("", "/help")

# envoyer "bonjour" au canal IRC #weechat (les utilisateurs sur le canal verront le message)
buffer = weechat.info_get("irc_buffer", "libera,#weechat")
weechat.command(buffer, "bonjour")
----

[[buffers_new]]
==== Créer un nouveau tampon

Vous pouvez créer un nouveau tampon dans votre script, et l'utiliser pour
afficher des messages.

Deux fonctions de rappel peuvent être appelés (ils sont optionnels) : une pour
les données en entrée (quand vous tapez du texte et pressez [Enter] sur le
tampon), l'autre est appelée lorsque le tampon est fermé (par exemple avec
`/buffer close`).

Exemple :

[source,python]
----
# fonction de rappel pour les données reçues en entrée
def buffer_input_cb(data, buffer, input_data):
    # ...
    return weechat.WEECHAT_RC_OK

# fonction de rappel appelée lorsque le tampon est fermé
def buffer_close_cb(data, buffer):
    # ...
    return weechat.WEECHAT_RC_OK

# créer le tampon
buffer = weechat.buffer_new("montampon", "buffer_input_cb", "", "buffer_close_cb", "")

# définir le titre
weechat.buffer_set(buffer, "title", "Ceci est le titre du tampon.")

# désactiver l'enregistrement (log), en définissant la variable locale "no_log" à "1"
weechat.buffer_set(buffer, "localvar_set_no_log", "1")
----

[[buffers_properties]]
==== Propriétés du tampon

Vous pouvez lire des propriétés du tampon, sous forme de chaîne, entier ou
pointeur.

Exemples :

[source,python]
----
buffer = weechat.current_buffer()

number = weechat.buffer_get_integer(buffer, "number")
name = weechat.buffer_get_string(buffer, "name")
short_name = weechat.buffer_get_string(buffer, "short_name")
----

Il est possible d'ajouter, lire ou supprimer des variables locales dans le
tampon :

[source,python]
----
# ajouter une variable locale
weechat.buffer_set(buffer, "localvar_set_myvar", "my_value")

# lire une variable locale
myvar = weechat.buffer_get_string(buffer, "localvar_myvar")

# supprimer une variable locale
weechat.buffer_set(buffer, "localvar_del_myvar", "")
----

Pour voir les variables locales d'un tampon, exécutez cette commande dans
WeeChat :

----
/buffer listvar
----

[[hooks]]
=== Hooks

[[hook_command]]
==== Ajouter une nouvelle commande

Ajoutez une nouvelle commande avec `+hook_command+`. Vous pouvez utiliser une
complétion personnalisée pour compléter les paramètres de votre commande.

Exemple :

[source,python]
----
def my_command_cb(data, buffer, args):
    # ...
    return weechat.WEECHAT_RC_OK

hook = weechat.hook_command("monfiltre", "description de mon filtre",
    "[list] | [enable|disable|toggle [name]] | [add name plugin.buffer tags regex] | [del name|-all]",
    "description des paramètres...",
    "list"
    " || enable %(filters_names)"
    " || disable %(filters_names)"
    " || toggle %(filters_names)"
    " || add %(filters_names) %(buffers_plugins_names)|*"
    " || del %(filters_names)|-all",
    "my_command_cb", "")
----

Puis sous WeeChat :

----
/help monfiltre

/monfiltre paramètres...
----

[[hook_timer]]
==== Ajouter un minuteur

Ajoutez un minuteur avec `+hook_timer+`.

Exemple :

[source,python]
----
def timer_cb(data, remaining_calls):
    # ...
    return weechat.WEECHAT_RC_OK

# minuteur appelé chaque minute quand la seconde est 00
weechat.hook_timer(60 * 1000, 60, 0, "timer_cb", "")
----

[[hook_process]]
==== Lancer un processus en tâche de fond

Vous pouvez lancer un processus en tâche de fond avec `+hook_process+`. Votre
fonction de rappel sera appelée quand des données seront prêtes. Elle peut être
appelée plusieurs fois.

Pour le dernier appel à votre fonction de rappel, _return_code_ est positionné
à 0 ou une valeur positive, il s'agit du code retour de la commande.

Exemple :

[source,python]
----
def my_process_cb(data, command, return_code, out, err):
    if return_code == weechat.WEECHAT_HOOK_PROCESS_ERROR:
        weechat.prnt("", "Erreur avec la commande '%s'" % command)
        return weechat.WEECHAT_RC_OK
    if return_code >= 0:
        weechat.prnt("", "return_code = %d" % return_code)
    if out:
        weechat.prnt("", "stdout: %s" % out)
    if err:
        weechat.prnt("", "stderr: %s" % err)
    return weechat.WEECHAT_RC_OK

weechat.hook_process("/bin/ls -l /etc", 10 * 1000, "my_process_cb", "")
----

Vous pouvez aussi appeler directement une fonction du script qui fait un appel
bloquant, au lieu d'une commande externe :

[source,python]
----
def get_status(data):
    # faire quelque chose de bloquant...
    # ...
    return "ceci est le résultat"

def my_process_cb(data, command, return_code, out, err):
    if return_code == weechat.WEECHAT_HOOK_PROCESS_ERROR:
        weechat.prnt("", "Error with command '%s'" % command)
        return weechat.WEECHAT_RC_OK
    if return_code >= 0:
        weechat.prnt("", "return_code = %d" % return_code)
    if out:
        weechat.prnt("", "stdout: %s" % out)
    if err:
        weechat.prnt("", "stderr: %s" % err)
    return weechat.WEECHAT_RC_OK

hook = weechat.hook_process("func:get_status", 5000, "my_process_cb", "")
----

[[url_transfer]]
==== Transfert d'URL

_Nouveau dans la version 0.3.7._

Pour télécharger une URL (ou poster vers une URL), vous devez utiliser la
fonction `+hook_process+`, ou `+hook_process_hashtable+` si vous avez besoin
d'options pour le transfert d'URL.

Exemple de transfert d'URL sans option : la page HTML sera reçue comme "out"
dans la fonction de rappel (sortie standard du processus) :

[source,python]
----
# Afficher la dernière version stable de WeeChat.
weechat_latest_version = ""

def weechat_process_cb(data, command, return_code, out, err):
    global weechat_latest_version
    if out:
        weechat_latest_version += out
    if return_code >= 0:
        weechat.prnt("", "Dernière version de WeeChat : %s" % weechat_latest_version)
    return weechat.WEECHAT_RC_OK

weechat.hook_process("url:https://weechat.org/dev/info/stable/",
                     30 * 1000, "weechat_process_cb", "")
----

[TIP]
Toutes les infos disponibles à propos de WeeChat sont sur
https://weechat.org/dev/info/[cette page ^↗^^].

Exemple de transfert d'URL avec une option : télécharger le dernier paquet de
développement WeeChat dans le fichier _/tmp/weechat-devel.tar.gz_ :

[source,python]
----
def my_process_cb(data, command, return_code, out, err):
    if return_code >= 0:
        weechat.prnt("", "Fin du transfert (code retour = %d)" % return_code)
    return weechat.WEECHAT_RC_OK

weechat.hook_process_hashtable("url:https://weechat.org/files/src/weechat-devel.tar.gz",
                               {"file_out": "/tmp/weechat-devel.tar.gz"},
                               30 * 1000, "my_process_cb", "")
----

Pour plus d'information sur le transfert d'URL et les options disponibles, voir
les fonctions `+hook_process+` et `+hook_process_hashtable+` dans la
link:weechat_plugin_api.fr.html#_hook_process[Référence API extension WeeChat ^↗^^].

[[config_options]]
=== Config / options

[[config_options_set_script]]
==== Définir des options pour le script

La fonction `+config_is_set_plugin+` est utilisée pour vérifier si une option est
définie ou pas, et `+config_set_plugin+` pour définir une option.

Exemple :

[source,python]
----
script_options = {
    "option1": "valeur1",
    "option2": "valeur2",
    "option3": "valeur3",
}
for option, default_value in script_options.items():
    if not weechat.config_is_set_plugin(option):
        weechat.config_set_plugin(option, default_value)
----

[[config_options_detect_changes]]
==== Détecter des changements

Vous devez utiliser `+hook_config+` pour être notifié si l'utilisateur modifie
certaines options du script.

Exemple :

[source,python]
----
SCRIPT_NAME = "monscript"

# ...

def config_cb(data, option, value):
    """Callback appelé lorsqu'une option du script est modifiée."""
    # par exemple, relire toutes les options du script dans des variables du script...
    # ...
    return weechat.WEECHAT_RC_OK

# ...

weechat.hook_config("plugins.var.python." + SCRIPT_NAME + ".*", "config_cb", "")
# pour les autres langages, remplacez "python" par le langage (perl/ruby/lua/tcl/guile/javascript)
----

[[config_options_weechat]]
==== Lire les options WeeChat

La fonction `+config_get+` retourne un pointeur vers une option. Ensuite, en
fonction du type de l'option, il faut appeler `+config_string+`, `+config_boolean+`,
`+config_integer+` ou `+config_color+`.

[source,python]
----
# chaîne
weechat.prnt("", "la valeur de l'option weechat.look.item_time_format est : %s"
                 % (weechat.config_string(weechat.config_get("weechat.look.item_time_format"))))

# booléen
weechat.prnt("", "la valeur de l'option weechat.look.day_change est : %d"
                 % (weechat.config_boolean(weechat.config_get("weechat.look.day_change"))))

# entier
weechat.prnt("", "la valeur de l'option weechat.look.scroll_page_percent est : %d"
                 % (weechat.config_integer(weechat.config_get("weechat.look.scroll_page_percent"))))

# couleur
weechat.prnt("", "la valeur de l'option weechat.color.chat_delimiters est : %s"
                 % (weechat.config_color(weechat.config_get("weechat.color.chat_delimiters"))))
----

[[irc]]
=== IRC

[[irc_catch_messages]]
==== Intercepter des messages

L'extension IRC envoie quatre signaux pour un message reçu (`xxx` est le nom
interne du serveur IRC, `yyy` est le nom de la commande IRC comme JOIN, QUIT,
PRIVMSG, 301, ..) :

xxx,irc_in_yyy::
    signal envoyé avant traitement du message, uniquement si le message n'est
    *pas* ignoré

xxx,irc_in2_yyy::
    signal envoyé après traitement du message, uniquement si le message n'est
    *pas* ignoré

xxx,irc_raw_in_yyy::
    signal envoyé avant traitement du message, même si le message est ignoré

xxx,irc_raw_in2_yyy::
    signal envoyé après traitement du message, même si le message est ignoré

[source,python]
----
def join_cb(data, signal, signal_data):
    # signal est par exemple : "libera,irc_in2_join"
    # signal_data est le message IRC, par exemple : ":nick!user@host JOIN :#canal"
    server = signal.split(",")[0]
    msg = weechat.info_get_hashtable("irc_message_parse", {"message": signal_data})
    buffer = weechat.info_get("irc_buffer", "%s,%s" % (server, msg["channel"]))
    if buffer:
        weechat.prnt(buffer, "%s (%s) a rejoint ce canal !" % (msg["nick"], msg["host"]))
    return weechat.WEECHAT_RC_OK

# il est pratique ici d'utiliser "*" comme serveur, pour intercepter les
# messages JOIN de tous les serveurs IRC
weechat.hook_signal("*,irc_in2_join", "join_cb", "")
----

[[irc_modify_messages]]
==== Modifier des messages

L'extension IRC envoie deux modificateurs pour un message reçu ("xxx" est la
commande IRC), de sorte que vous puissiez le modifier :

irc_in_xxx::
    modificateur envoyé avant le décodage du jeu de caractères : à utiliser avec
    précaution, la chaîne peut contenir des données invalides UTF-8 ; à utiliser
    seulement pour les opérations de bas niveau sur le message

irc_in2_xxx::
    modificateur envoyé après décodage du jeu de caractères, donc la chaîne
    reçue est toujours valide UTF-8 (*recommendé*)

[source,python]
----
def modifier_cb(data, modifier, modifier_data, string):
    # ajouter le nom du serveur à tous les messages reçus
    # (ok ce n'est pas très utile, mais c'est juste un exemple !)
    return "%s %s" % (string, modifier_data)

weechat.hook_modifier("irc_in2_privmsg", "modifier_cb", "")
----

[WARNING]
Un message mal formé peut provoquer un plantage de WeeChat ou de sérieux
problèmes !

[[irc_message_parse]]
==== Analyser un message

_Nouveau dans la version 0.3.4._

Vous pouvez analyser un message IRC avec l'info_hashtable appelée
"irc_message_parse".

Le résultat est une table de hachage avec les clés suivantes
(les exemples de valeurs sont construits avec ce message :
`+@time=2015-06-27T16:40:35.000Z :nick!user@host PRIVMSG #weechat :hello!+`) :

[width="100%",cols="3,^2,10,7",options="header"]
|===
| Clé | Depuis WeeChat ^(1)^ | Description | Exemple

| tags | 0.4.0
| Les étiquettes dans le message (peut être vide).
| `+time=2015-06-27T16:40:35.000Z+`

| tag_xxx | 3.3
| Valeur de l'étiquette "xxx" sans les échappements (une clé par étiquette).
| `+2015-06-27T16:40:35.000Z+`

| message_without_tags | 0.4.0
| Le message sans les étiquettes (la même chose que le message s'il n'y a pas
  d'étiquettes).
| `+:nick!user@host PRIVMSG #weechat :hello!+`

| nick | 0.3.4
| Le pseudo d'origine.
| `+nick+`

| user | 2.7
| L'utilisateur d'origine.
| `+user+`

| host | 0.3.4
| L'hôte d'origine (incluant le pseudo).
| `+nick!user@host+`

| command | 0.3.4
| La commande (_PRIVMSG_, _NOTICE_, ...).
| `+PRIVMSG+`

| channel | 0.3.4
| Le canal cible.
| `+#weechat+`

| arguments | 0.3.4
| Les paramètres de la commande (incluant le canal).
| `+#weechat :hello!+`

| text | 1.3
| Le texte (par exemple un message utilisateur).
| `+hello!+`

| paramN | 3.4
| Paramètre de commande (de 1 à N).
| `+#weechat+`

| num_params | 3.4
| Nombre de paramètres de commande.
| `+2+`

| pos_command | 1.3
| La position de _command_ dans le message ("-1" si _command_ n'a pas été trouvé).
| `+47+`

| pos_arguments | 1.3
| La position de _arguments_ dans le message ("-1" si _arguments_ n'a pas été trouvé).
| `+55+`

| pos_channel | 1.3
| La position de _channel_ dans le message ("-1" si _channel_ n'a pas été trouvé).
| `+55+`

| pos_text | 1.3
| La position de _text_ dans le message ("-1" si _text_ n'a pas été trouvé).
| `+65+`
|===

[NOTE]
^(1)^ La clé a été introduite dans cette version de WeeChat.

[source,python]
----
dict = weechat.info_get_hashtable(
    "irc_message_parse",
    {"message": "@time=2015-06-27T16:40:35.000Z;tag2=value\\sspace :nick!user@host PRIVMSG #weechat :hello!"})

# dict == {
#     "tags": "time=2015-06-27T16:40:35.000Z;tag2=value\\sspace",
#     "tag_time": "2015-06-27T16:40:35.000Z",
#     "tag_tag2": "value space",
#     "message_without_tags": ":nick!user@host PRIVMSG #weechat :hello!",
#     "nick": "nick",
#     "user": "user",
#     "host": "nick!user@host",
#     "command": "PRIVMSG",
#     "channel": "#weechat",
#     "arguments": "#weechat :hello!",
#     "text": "hello!",
#     "param1": "#weechat",
#     "param2": "hello!",
#     "num_params": "2",
#     "pos_command": "65",
#     "pos_arguments": "73",
#     "pos_channel": "73",
#     "pos_text": "83",
# }
----

[[infos]]
=== Infos

[[infos_weechat_version]]
==== Version de WeeChat

Le meilleur moyen de vérifier la version est de demander "version_number" et de
faire une comparaison entre nombre entiers avec la version hexadécimale de la
version.

Exemple :

[source,python]
----
version = weechat.info_get("version_number", "") or 0
if int(version) >= 0x00030200:
    weechat.prnt("", "C'est WeeChat 0.3.2 ou plus récent")
else:
    weechat.prnt("", "C'est WeeChat 0.3.1 ou plus ancien")
----

[NOTE]
Les versions ≤ 0.3.1.1 retournent une chaîne vide pour
_info_get("version_number")_, donc vous devez vérifier que la valeur de retour
n'est *pas* vide.

Pour obtenir la version sous forme de chaîne :

[source,python]
----
# ceci affichera par exemple "Version 0.3.2"
weechat.prnt("", "Version %s" % weechat.info_get("version", ""))
----

[[infos_other]]
==== Autres infos

[source,python]
----
# répertoire de config WeeChat, par exemple : "/home/user/.config/weechat"
weechat.prnt("", "Répertoire de config WeeChat : %s" % weechat.info_get("weechat_config_dir", ""))

# inactivité clavier
weechat.prnt("", "Inactivité depuis %s secondes" % weechat.info_get("inactivity", ""))
----

[[infolists]]
=== Infolists

[[infolists_read]]
==== Lire une infolist

Vous pouvez lire une infolist construite par WeeChat ou d'autres extensions.

Exemple :

[source,python]
----
# lecture de l'infolist "buffer", pour avoir la liste des tampons
infolist = weechat.infolist_get("buffer", "", "")
if infolist:
    while weechat.infolist_next(infolist):
        name = weechat.infolist_string(infolist, "name")
        weechat.prnt("", "buffer: %s" % name)
    weechat.infolist_free(infolist)
----

[IMPORTANT]
N'oubliez pas d'appeler `+infolist_free+` pour libérer la mémoire utilisée par
l'infolist, car WeeChat ne libère par automatiquement cette mémoire.
