\input texinfo  @c -*-texinfo-*-
@c %**start of header
@setfilename weechat_doc_fr.info
@settitle WeeChat - Client IRC rapide, leger et extensible
@c %**end of header

@c WeeChat documentation (french version)
@c
@c Copyright (c) 2005 by FlashCode <flashcode@flashtux.org>
@c
@c This manual is free software; you can redistribute it and/or modify
@c it under the terms of the GNU General Public License as published by
@c the Free Software Foundation; either version 2 of the License, or
@c (at your option) any later version.
@c
@c This manual is distributed in the hope that it will be useful,
@c but WITHOUT ANY WARRANTY; without even the implied warranty of
@c MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
@c GNU General Public License for more details.
@c
@c You should have received a copy of the GNU General Public License
@c along with this program; if not, write to the Free Software
@c Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

@c pdf : texi2pdf weechat_doc_fr.texi
@c html: makeinfo --html --no-split --number-sections weechat_doc_fr.texi

@c tex
@c \overfullrule=0pt
@c end tex

@documentlanguage fr

@titlepage

@title WeeChat - Guide utilisateur
@subtitle Client IRC rapide, l@'eger et extensible
@subtitle Documentation pour WeeChat v0.1.1-cvs - 10 Mars 2005

@image{weechat_image}

@author FlashCode <@email{flashcode@@flashtux.org, flashcode AT flashtux.org}>

@page

Ce manuel documente le client IRC WeeChat, il fait partie de WeeChat.@*
@*
La derni@`ere version de ce document peut @^etre t@'el@'echarg@'ee sur cette page :@*
@uref{http://weechat.flashtux.org/doc.php}@*
@*
Copyright @copyright{} 2005 FlashCode
<@email{flashcode@@flashtux.org, flashcode AT flashtux.org}>@*
@*
Ce document peut @^etre utilis@'e sous les termes de la licence GNU General Public
License version 2 ou plus.

@end titlepage

@everyheading @thischapter @| @|
@everyfooting @thistitle @| @| Page @thispage

@contents

@node Top, Introduction, (dir), (dir)
@menu
* Introduction:: Description de WeeChat
* Installation:: Installation de WeeChat
* Utilisation:: Utilisation de WeeChat
* Extensions:: Extensions de WeeChat
* Auteurs / Support:: Contacter les auteurs et obtenir du support
@end menu


@c ******************************* Introduction *******************************

@node Introduction, Installation, Top, Top
@chapter Introduction
@menu
* Description::
* Pre-requis::
@end menu

@node Description, Pre-requis, Introduction, Introduction
@section Description

WeeChat (Wee Enhanced Environment for Chat) est un client IRC libre, rapide et l@'eger,
concu pour diff@'erents syst@`emes d'exploitation.@*
@*
Ses principales caract@'eristiques sont les suivantes :
@itemize @minus
@item
connexion multi-serveurs
@item
plusieurs interfaces : Curses, Gtk et Qt
@item
petit, rapide et l@'eger
@item
param@'etrable et extensible avec des scripts
@item
conforme aux RFCs 1459, 2810, 2811, 2812, et 2813
@item
multi-plateformes (Gnu/Linux, *BSD, Windows et d'autres syst@`emes)
@item
100% GPL, logiciel libre
@end itemize

@*
La page d'accueil de WeeChat est ici :@*
@uref{http://weechat.flashtux.org}@*

@node Pre-requis, , Description, Introduction
@section Pr@'e-requis

Pour installer WeeChat, vous @b{devez} avoir :@*

@itemize @bullet
@item
Un syst@`eme Gnu/Linux (avec le compilateur et les outils associ@'es pour le paquet des sources)
@item
Droits "root" (pour installer WeeChat)
@item
Selon l'interface, une des biblioth@`eques suivantes :
@itemize @minus
@item
Curses: la librairie ncurses,
@item
Gtk: *** interface non d@'evelopp@'ee ***,
@item
Qt: *** interface non d@'evelopp@'ee ***,
@end itemize
@end itemize


@c ******************************* Installation *******************************

@node Installation, Utilisation, Introduction, Top
@chapter Installation

@menu
* Paquet binaire::
* Paquet source::
* Sources CVS::
@end menu

@node Paquet binaire, Paquet source, Installation, Installation
@section Paquet binaire

Les paquets binaires sont disponibles pour les distributions suivantes :
@itemize @bullet
@item
Debian (ou toute distribution compatible Debian)@*
Pour installer : @kbd{dpkg -i /chemin/weechat_x.y.z-1_i386.deb}
@item
Mandrake/Redhat (ou toute distribution compatible avec les RPM)@*
Pour installer : @kbd{rpm -i /chemin/weechat-x.y.z-1.i386.rpm}
@item
Gentoo@*
Pour installer : @kbd{emerge weechat}
@item
*BSD (non disponible !)
@item
Slackware (non disponible !)
@item
Windows (non disponible !)
@end itemize

o@`u x.y.z est la version (par exemple 0.0.1)
@*

@node Paquet source, Sources CVS, Paquet binaire, Installation
@section Paquet source

Tapez simplement dans une console ou un terminal :@*
@kbd{./configure}@*
@kbd{make}@*
Note: pour ne construire que certaines interfaces, vous pouvez passer des param@`etres
@`a ./configure, tapez @kbd{./configure --help} pour de l'aide sur ces options.@*

Obtenez les droits root et installez WeeChat :@*
@kbd{su}@*
(entrez le mot de passe de root)@*
@kbd{make install}@*

@node Sources CVS, , Paquet source, Installation
@section Sources CVS

Attention: les sources CVS sont r@'eserv@'es aux utilisateurs avanc@'es : il se peut
que WeeChat ne compile pas et qu'il soit tr@`s instable.
Vous @^etes pr@'evenus !@*

Pour r@'ecup@'erer les sources CVS, tapez ces commandes :@*
@kbd{cvs -d:pserver:anoncvs@@subversions.gnu.org:/cvsroot/weechat login}@*
@kbd{cvs -z3 -d:pserver:anoncvs@@subversions.gnu.org:/cvsroot/weechat co weechat}@*
(lorsqu'un mot de passe est demand@'e, tapez simplement sur Entr@'ee)@*

Ex@'ecutez ce script :@*
@kbd{./autogen.sh}@*

Suivez alors les instructions du paquet sources - @xref{Paquet source}.


@c ******************************* Utilisation ********************************

@node Utilisation, Extensions, Installation, Top
@chapter Utilisation

@menu
* Lancer WeeChat::
* Fichier de configuration::
* Raccourcis clavier::
* Commandes WeeChat::
@end menu

@node Lancer WeeChat, Fichier de configuration, Utilisation, Utilisation
@section Lancer WeeChat

@subsection Param@`etres de ligne de commande

@table @code
@item -c, --config
Afficher l'aide sur le fichier de config (liste des options)@*
@item -h, --help
Afficher l'aide@*
@item -l, --license
Afficher la licence de WeeChat@*
@item -v, --version
Afficher la version de WeeChat@*
@end table

@subsection Lancer WeeChat

Tapez simplement cette commande pour lancer WeeChat :@*
@kbd{weechat-curses} (pour l'interface Curses)@*
ou @kbd{weechat-gtk} (pour l'interface Gtk)@*
ou @kbd{weechat-qt} (pour l'interface Qt)@*

Lorsque vous lancez WeeChat pour la premi@`ere fois, un fichier de configuration
par d@'efaut est cr@'e@'e, avec les options par d@'efaut.@*
Le fichier de configuration par d@'efaut est : ~/.weechat/weechat.rc@*

Vous pouvez @'editer ce fichier pour configurer WeeChat @`a votre convenance, ou
vous pouvez modifier les param@`etres dans WeeChat avec la commande @kbd{/set} - @xref{Commandes WeeChat}.

@node Fichier de configuration, Raccourcis clavier, Lancer WeeChat, Utilisation
@section Fichier de configuration

Liste des options du fichier de configuration :@*

@table @kbd

@end table

Les couleurs pour l'interface Curses sont :@*
@itemize @minus
@item
@kbd{default}: couleur par d@'efaut (transparent pour le fond)
@item
@kbd{black}: noir
@item
@kbd{red}: rouge fonc@'e
@item
@kbd{lightred}: rouge clair
@item
@kbd{green}: vert fonc@'e
@item
@kbd{lightgreen}: vert clair
@item
@kbd{brown}: marron
@item
@kbd{yellow}: jaune
@item
@kbd{blue}: bleu fonc@'e
@item
@kbd{lightblue}: bleu clair
@item
@kbd{magenta}: violet fonc@'e
@item
@kbd{lightmagenta}: violet clair
@item
@kbd{cyan}: cyan fonc@'e
@item
@kbd{lightcyan}: cyan clair
@item
@kbd{white}: blanc
@end itemize

@node Raccourcis clavier, Commandes WeeChat, Fichier de configuration, Utilisation
@section Raccourcis clavier

@table @kbd
@item Fl@`eche gauche / Fl@`eche droite
Aller au caract@`ere pr@'ec@'edent / suivant sur la ligne de commande@*
@*
@item Ctrl + fl@`eche gauche / Ctrl + fl@`eche droite
Aller au mot pr@'ec@'edent / suivant sur la ligne de commande@*
@*
@item Home / Ctrl + A
Aller au d@'ebut de la ligne de commande@*
@*
@item End / Ctrl + E
Aller @`a la fin de la ligne de commande@*
@*
@item Backspace / Delete
Effacer le mot pr@'ec@'edent / suivant sur la ligne de commande@*
@*
@item Ctrl + Backspace / Ctrl + W
Effacer le mot pr@'ec@'edent sur la ligne de commande@*
@*
@item Tab
Compl@'eter la commande ou le pseudo (@kbd{Tab} @`a nouveau : trouver la compl@'etion suivante)@*
@*
@item Tout caract@`ere
Ins@'erer le caract@`ere @`a la position du curseur sur la ligne de commande@*
@*
@item Entr@'ee
Ex@'ecuter la commande ou envoyer le message@*
@*
@item Fl@`eche haut / Fl@`eche bas
Rappeler les derni@`eres commandes/messages@*
@*
@item PageUp / PageDown
Afficher l'historique du tampon@*
@*
@item F5 / F6
Aller au tampon pr@'ec@'edent / suivant@*
@*
@item F7 / F8
Aller @`a la fen@^etre pr@'ec@'edente / suivante@*
@*
@item F10
Effacer le dernier message de la barre d'infos@*
@*
@item Ctrl + L
R@'eaffiche toute la fen@^etre@*
@*
@item Alt + fl@`eche gauche / Alt + fl@`eche droite
Identique @`a F5 / F6@*
@*
@item Alt + A
Sauter au tampon avec activit@'e (avec priorit@'e: highlight, message, autre)@*
@*
@item Alt + D
Afficher les DCC en cours@*
@*
@item Alt + R
Vide la hotlist (notification d'activité sur les autres tampons)@*
@*
@item Alt + S
Sauter au tampon du serveur@*
@*
@item Alt + X
Sauter au premier canal du serveur suivant (ou tampon du serveur si aucun canal ouvert)@*
@*
@item Alt + chiffre (1-9)
Sauter au tampon avec ce num@'ero@*
@*
@end table

@node Commandes WeeChat, , Raccourcis clavier, Utilisation
@section Commandes WeeChat

Commandes internes WeeChat :@*

@table @kbd

@item alias  [nom_alias [commande [param@`etres]]
@*
cr@'eer un alias pour une commande@*
@*
nom_alias: nom de l'alias@*
commande: nom de la commande (commande WeeChat ou IRC, sans le premier '/')@*
param@`etres: param@`etres pour la commande@*
@*
@item buffer  [action | nombre]
@*
g@`ere les buffers@*
@*
action: action @`a effectuer:@*
  move: d@'eplacer le tampon dans la liste (peut @^etre relatif, par exemple -1)@*
  close: fermer le tampon (pour un canal: @'equivalent @`a /part sans message de fin)@*
  list: liste les tampons ouverts (pas de param@`etre affiche cette liste)@*
  notify: fixer le niveau de notification (0=jamais, 1=highlight, 2=1+msg, 3=2+join/part)@*
nombre: sauter au tampon qui a ce num@'ero@*
@*
@item clear  [-all]
@*
affacer la/les fen@^etre(s)@*
@*
-all: effacer toutes les fen@^etres@*
@*
@item connect  [nom_serveur]
@*
se connecter @`a un serveur@*
@*
nom_serveur: nom du serveur pour se connecter@*
@*
@item disconnect  [nom_serveur]
@*
se d@'econnecter d'un serveur@*
@*
nom_serveur: nom du serveur pour se d@'econnecter@*
@*
@item debug  dump
@*
affiche des messages de debuggage@*
@*
dump: affiche les variables m@'emoire WeeChat dans le fichier log (les m@^emes messages sont affich@'es lorsque WeeChat plante)@*
@*
@item help  [commande]
@*
afficher l'aide sur les commandes@*
@*
commande: nom d'une commande WeeChat ou IRC@*
@*
@item perl  [load fichier] | [autoload] | [unload]
@*
liste/charge/d@'echarge des scripts Perl@*
@*
fichier: script Perl (fichier) @`a charger@*
Sans param@`etre, la commande /perl liste tous les scripts Perl charg@'es.@*
@*
@item server  [nom_serveur] | [nom_serveur nom/IP port [-auto | -noauto] [-pwd mot_de_passe] [-nicks pseudo1 [pseudo2 [pseudo3]]] [-username nom_utilisateur] [-realname nom_r@'eel] [-command commande] [-autojoin canal[,canal]] ] | [del nom_serveur]
@*
liste, ajoute ou retire des serveurs@*
@*
nom_serveur: nom du serveur, pour usage interne et affichage@*
nom/IP: nom ou adresse IP du serveur@*
port: port pour le serveur (nombre entier)@*
mot_de_passe: mot de passe pour le serveur@*
pseudo1: premier pseudo pour le serveur@*
pseudo2: pseudo alternatif pour le serveur@*
pseudo3: second pseudo alternatif pour le serveur@*
nom_utilisateur: nom d'utilisateur@*
nom_r@'eel: nom r@'eel de l'utilisateur@*
@*
@item save  [fichier]
@*
sauvegarder la configuration sur disque@*
@*
fichier: fichier pour sauvegarder la configuration@*
@*
@item set  [option[=valeur]]
@*
modifier des param@`etres de configuration@*
@*
option: nom d'une option@*
valeur: valeur pour l'option@*
@*
@item unalias  nom_alias
@*
supprimer un alias@*
@*
nom_alias: nom de l'alias @`a supprimer@*
@*
@item window  [list | splith | splitv | [merge [down | up | left | right | all]]]
@*
gestion des fen@^etres@*
@*
list: liste les fen@^etres ouvertes (pas de param@`etre affiche cette liste)@*
splith: @'eclate la fen@^etre en deux horizontalement@*
splitv: @'eclate la fen@^etre en deux verticalement@*
merge: fusionne la fen@^etre avec une autre@*
@*

@end table

Commandes IRC :@*

@table @kbd

@item admin  [cible]
@*
trouver les informations sur l'administrateur du serveur@*
@*
cible: serveur@*
@*
@item away  [-all] [message]
@*
basculer le statut absent@*
@*
-all: basculer le statut absent sur tous les serveurs connect@'es@*
message: message pour l'absence (si pas de message donn@'e, le statut d'absence est supprim@'e)@*
@*
@item ctcp  pseudo type
@*
envoyer un message ctcp@*
@*
pseudo: utilisateur pour envoyer le ctcp@*
type: "action" ou "version"@*
@*
@item dcc  action [pseudo [fichier]]
@*
d@'emarre le DCC (fichier ou discussion) ou ferme une discussion@*
@*
action: 'send' (envoi de fichier) ou 'chat' (discussion) ou 'close' (fermeture discussion)@*
pseudo: pseudo pour envoyer le fichier ou discuter@*
fichier: nom du fichier (sur la machine locale)@*
@*
@item deop  pseudo [pseudo]
@*
retire le statut d'op@'erateur du canal @`a/aux nick(s)@*
@*
@item devoice  pseudo [pseudo]
@*
retire la voix du/des pseudo(s)@*
@*
@item die
@*
arr@^eter le serveur@*
@*
@item info  [cible]
@*
voir les informations d@'ecrivant le serveur@*
@*
cible: nom du serveur@*
@*
@item invite  pseudo canal
@*
inviter un utilisateur sur un canal@*
@*
pseudo: utilisateur @`a inviter@*
channel: canal pour l'invitation@*
@*
@item ison  pseudo [pseudo ...]
@*
v@'erifier si un utilisateur est actuellement sur IRC@*
@*
pseudo: pseudo@*
@*
@item join  canal[,canal] [cl@'e[,cl@'e]]
@*
joindre un canal@*
@*
canal: nom du canal @`a rejoindre@*
cl@'e: cl@'e pour rejoindre le canal@*
@*
@item kick  [canal] pseudo [commentaire]
@*
retirer par la force un utilisateur d'un canal@*
@*
canal: canal o@`u l'utilisateur se trouve@*
pseudo: utilisateur @`a @'eliminer@*
commentaire: commentaire pour l'@'elimination@*
@*
@item kill  pseudo commentaire
@*
fermer la connexion client-serveur@*
@*
pseudo: utilisateur@*
commentaire: commentaire pour la mort@*
@*
@item links  [[serveur] masque_serveur]
@*
lister tous les noms de serveurs connus du serveur qui r@'epondent @`a la requ@^ete@*
@*
serveur: ce serveur doit r@'epondre @`a la requ@^ete@*
masque_serveur: liste des serveurs correspondant au masque@*
@*
@item list  [canal[,canall] [serveur]]
@*
lister les canaux et leur sujet@*
@*
canal: canal @`a lister@*
serveur: nom du serveur@*
@*
@item lusers  [masque [cible]]
@*
obtenir des statistiques sur la taille du r@'eseau IRC@*
@*
masque: serveurs qui correspondent au masque seulement@*
cible: serveur pour faire suivre la requ@^ete@*
@*
@item me  message
@*
envoyer une action ctcp au canal courant@*
@*
message: message @`a envoyer@*
@*
@item mode  @{ canal @{[+|-]|o|p|s|i|t|n|b|v@} [limite] [utilisateur] [masque de banissement] @} | @{ nick @{[+|-]|i|w|s|o@} @}
@*
changer le mode du canal ou de l'utilisateur@*
@*
modes de canaux :@*
  canal: nom du canal @`a modifier@*
  o: donner/reprendre le statut privil@'egi@'e d'op@'erateur@*
  p: indicateur de canal priv@'e@*
  s: indicateur de canal secret@*
  i: indicateur de canal avec invitation seulement@*
  t: le titre est modifiable seulement par un op@'erateur du canal@*
  n: aucun message au canal depuis l'ext@'erieur@*
  m: canal mod@'er@'e@*
  l: fixer la limite d'utilisateurs pour le canal@*
  b: param@'etrer un masque de banissement pour garder des utilisateurs dehors@*
  v: donner/reprendre la possibilit@'e de parler sur un canal mod@'er@'e@*
  k: d@'efinir une cl@'e (mot de passe) pour acc@'eder au canal@*
modes utilisateur :@*
  pseudo: utilisateur @`a modifier@*
  i: marquer un utilisateur comme invisible@*
  s: marquer un utilisateur pour recevoir les notices du serveur@*
  w: l'utilisateur re@,{c}oit les wallops@*
  o: drapeau op@'erateur@*
@*
@item motd  [cible]
@*
obtenir le message du jour@*
@*
cible: nom du serveur@*
@*
@item msg  cible[,cible] texte
@*
envoyer un message @`a un utilisateur ou canal@*
@*
cible: utilisateur ou canal (peut-@^etre un masque, '*' = canal courant)@*
texte: texte @`a envoyer@*
@*
@item names  [canal[,canal]]
@*
lister les utilisateurs sur des canaux@*
@*
canal: nom du canal@*
@*
@item nick  pseudo
@*
changer le pseudo courant@*
@*
pseudo: nouveau pseudo pour le serveur IRC courant@*
@*
@item notice  pseudo texte
@*
envoyer un message notice @`a un utilisateur@*
@*
pseudo: utilisateur cible pour la notice@*
texte: texte @`a envoyer@*
@*
@item op  pseudo [pseudo]
@*
donner le statut op@'erateur @`a un/des utilisateur(s)@*
@*
@item oper  utilisateur mot_de_passe
@*
obtenir le statut d'op@'erateur@*
@*
utilisateur/mot_de_passe: utilis@'e pour obtenir les privil@`eges sur le serveur IRC courant@*
@*
@item part  [canal[,canall] [message_de_fin]
@*
quitter un canal@*
@*
canal: canal @`a quitter@*
message_de_fin: message de fin (affich@'e aux autres utilisateurs)@*
@*
@item ping  serveur1 [serveur2]
@*
pinguer un serveur@*
@*
serveur1: serveur @`a pinguer@*
serveur2: faire suivre le ping @`a ce serveur@*
@*
@item pong  d@'emon [d@'emon2]
@*
r@'epondre @`a un message ping@*
@*
d@'emon: d@'emon qui a r@'epondu au message Ping@*
d@'emon2: faire suivre le message @`a ce d@'emon@*
@*
@item query  pseudo [texte]
@*
envoyer un message priv@'e @`a un utilisateur@*
@*
pseudo: utilisateur pour la conversation priv@'ee@*
texte: texte @`a envoyer@*
@*
@item quit  [message_de_fin]
@*
fermer toutes les connexions et quitter@*
@*
message_de_fin: message de fin (affich@'e aux autres utilisateurs)@*
@*
@item quote  donn@'ees
@*
envoyer des donn@'ees brutes au serveur sans analyse@*
@*
donn@'ees: donn@'ees brutes @`a envoyer@*
@*
@item rehash
@*
demander au serveur de recharger son fichier de config@*
@*
@item restart
@*
demander au serveur de red@'emarrer@*
@*
@item service  pseudo r@'eserv@'e distribution type r@'eserv@'e info
@*
enregister un nouveau service@*
@*
distribution: visibilit@'e du service@*
type: r@'eserv@'e pour une utilisation future@*
@*
@item servlist  [masque [type]]
@*
lister les services actuellement connect@'es au r@'eseau@*
@*
masque: lister seulement les services qui correspondent @`a ce masque@*
type: lister seulement les services de ce type@*
@*
@item squery  service texte
@*
envoyer un message @`a un service@*
@*
service: nom du service@*
texte: texte @`a envoyer@*
@*
@item squit  serveur commentaire
@*
d@'econnecter les liens vers un serveur@*
@*
serveur: nom du serveur@*
commentaire: commentaire pour quitter@*
@*
@item stats  [requ@^ete [serveur]]
@*
demander des statistiques sur le serveur@*
@*
requ@^ete: c/h/i/k/l/m/o/y/u (voir la RFC1459)@*
serveur: nom du serveur@*
@*
@item summon  utilisateur [cible [canal]]
@*
envoyer aux utilisateurs d'un serveur IRC un message leur demandant de rejoindre IRC@*
@*
utilisateur: nom d'utilisateur@*
cible: nom du serveur@*
canal: nom du canal@*
@*
@item time  [cible]
@*
demander l'heure locale de serveur@*
@*
cible: demander l'heure de ce serveur@*
@*
@item topic  [canal] [titre]
@*
recevoir/d@'efinir le titre du canal@*
@*
canal: nom du canal@*
titre: nouveau titre pour le canal (si le titre est "-delete" alors le titre est supprim@'e)@*
@*
@item trace  [cible]
@*
trouver le chemin jusqu'@`a un serveur sp@'ecifique@*
@*
cible: serveur@*
@*
@item userhost  pseudo [pseudo ...]
@*
retourne une liste d'informations sur des utilisateurs@*
@*
pseudo: pseudo@*
@*
@item users  [cible]
@*
liste des utilisateurs connect@'es au serveur@*
@*
cible: serveur@*
@*
@item version  [serveur | pseudo]
@*
retourne la version de l'utilisateur ou du serveur (courant ou sp@'ecifi@'e)@*
@*
serveur: nom du serveur@*
pseudo: utilisateur@*
@*
@item voice  pseudo [pseudo]
@*
donne la voix @`a/aux utilisateur(s)@*
@*
@item wallops  texte
@*
envoyer un message @`a tous les utilisateurs connect@'es qui ont activ@'e le mode utilisateur 'w' pour eux-m@^emes@*
@*
texte @`a envoyer@*
@*
@item who  [masque ["o"]]
@*
g@'en@`ere une requ@^ete qui retourne une liste d'information@*
@*
masque: information qui correspond @`a ce masque uniquement@*
o: seul les op@'erateurs sont retourn@'es correspondant au masque fourni@*
@*
@item whois  [serveur] pseudo[,pseudo]
@*
demande les informations sur le(s) utilisateur(s)@*
@*
serveur: nom du serveur@*
pseudo: utilisateur (peut @^etre un masque)@*
@*
@item whowas  pseudo [,pseudo [,pseudo ...]] [nombre [cible]]
@*
demander de l'information sur un nick qui n'existe plus@*
@*
pseudo: pseudo @`a chercher@*
nombre: nombre de r@'eponses @`a retourner (recherche compl@`ete si nombre n@'egatif)@*
cible: la r@'eponse doit correspondre @`a ce masque@*
@*

@end table


@c ******************************* Extensions *********************************

@node Extensions, Auteurs / Support, Utilisation, Top
@chapter Extensions

@menu
* Scripts Perl::
* Scripts Python::
* Scripts Ruby::
@end menu

@node Scripts Perl, Scripts Python, Extensions, Extensions
@section Scripts Perl

@subsection Charger/d@'echarger des scripts Perl

Les scripts Perl sont charg@'es et d@'echarg@'es avec la commande @command{/perl}
(tapez @kbd{/help perl} dans WeeChat pour obtenir de l'aide sur la commande).@*

@emph{Exemples :}@*
@itemize @bullet
@item
Charger un script Perl : @kbd{/perl load /tmp/essai.pl}@*
@item D@'echarger tous les scripts Perl : @kbd{/perl unload}@*
@item
Lister les scripts Perl charg@'es : @kbd{/perl}@*
@end itemize

@subsection Interface WeeChat / Perl

@itemize @bullet
@item
@command{IRC::register ( nom, version, fonction_de_fin, description );}@*
@*
C'est la premi@`ere fonction @`a appeler dans le script Perl.@*
Tout script Perl pour WeeChat doit appeler cette fonction.@*

@emph{Param@`etres :}
@itemize @minus
@item @option{nom}: nom unique pour identifier le script (chaque script doit
avoir un nom diff@'erent)
@item @option{version}: version du script
@item @option{fonction_de_fin}: fonction Perl appel@'ee quand le script est
d@'echarg@'e (param@`etre facultatif, une cha@^ine vide signifiant qu'il n'y a pas
de fonction @`a appeler)
@item @option{description}: description br@`eve du script.
@end itemize
@*
@emph{Exemple :}@*
@code{IRC::register ("essai", "1.0", "fin_essai", "Script d'essai !");}@*
@*

@item
@command{IRC::print ( message );}@*
@*
Affiche un message dans la fen@^etre courante (canal ou serveur).@*

@emph{Param@`etres :}
@itemize @minus
@item @option{message}: message @`a afficher
@end itemize
@*
@emph{Exemple :}@*
@code{IRC::print ("message");}@*
@*

@item
@command{IRC::print_with_channel ( canal, [serveur,] message );}@*
@*
Affiche un message dans un canal.@*

@emph{Param@`etres :}
@itemize @minus
@item @option{canal}: nom du canal
@item @option{serveur}: nom interne du serveur
@item @option{message}: message @`a afficher
@end itemize
@*
@emph{Exemples :}@*
@code{IRC::print_with_channel ("#weechat", "freenode", "message");}@*
@code{IRC::print_with_channel ("#weechat", "message");}@*
@*

@item
@command{IRC::print_infobar ( d@'elai, message );}@*
@*
Affiche un message dans la barre d'infos.@*

@emph{Param@`etres :}
@itemize @minus
@item @option{d@'elai}: d@'elai (en secondes) pendant lequel le message est affich@'e
(si 0, le message ne sera pas effac@'e).
@item @option{message}: message @`a afficher
@end itemize
@*
@emph{Exemple :}@*
@code{IRC::print_infobar (5, "message");}@*
@*

@item
@command{IRC::add_message_handler ( nom, fonction );}@*
@*
Attache une fonction Perl @`a un message IRC particulier.@*
La fonction sera appel@'ee @`a chaque fois que le message IRC sera re@,{c}u.@*

@emph{Param@`etres :}
@itemize @minus
@item @option{nom}: nom du message IRC pour lequel la fonction est appel@'ee@*
Pour conna@^itre la liste des messages IRC disponibles, merci de consulter les
RFC 1459 et/ou 2812 :@*
RFC 1459 : @uref{ftp://ftp.rfc-editor.org/in-notes/rfc1459.txt}@*
RFC 2812 : @uref{ftp://ftp.rfc-editor.org/in-notes/rfc2812.txt}
@item @option{fonction}: fonction Perl appel@'ee lorsque le message est re@,{c}u
@end itemize
@*
@emph{Exemple :}@*
@code{IRC::add_message_handler ("privmsg", ma_fonction);}@*
@code{sub ma_fonction}@*
@code{@{ }@*
@code{@ @ @ @ IRC::print ("serveur=$_[0]\n");}@*
@code{@ @ @ @ ($null, $canal, $message) = split ":",$_[1],3;}@*
@code{@ @ @ @ ($masque, $null, $canal) = split " ", $canal;}@*
@code{@ @ @ @ IRC::print ("masque=$masque, canal=$canal, message=$message\n");}@*
@code{@} }@*
@*

@item
@command{IRC::add_command_handler ( nom, fonction );}@*
@*
Cr@'e@'e une nouvelle commande WeeChat, associ@'ee @`a une fonction Perl.@*
La fonction sera appel@'ee lorsque l'utilisateur lancera la commande par @kbd{/nom}.@*

@emph{Param@`etres :}
@itemize @minus
@item @option{nom}: nom de la nouvelle commande@*
Il peut s'agir d'une commande existante, auquel cas celle-ci est @'ecras@'ee par
la fonction Perl. Soyez prudent en @'ecrasant les commandes WeeChat, car elles
ne seront plus accessibles tant que le script Perl sera charg@'e.
@item @option{fonction}: fonction Perl associ@'ee @`a la commande
@end itemize
@*
@emph{Exemple :}@*
@code{IRC::add_command_handler ("commande", ma_commande);}@*
@code{sub ma_commande}@*
@code{@{ }@*
@code{@ @ @ @ IRC::print("Serveur: $_[0], param@`etres: $_[1]\n");}@*
@code{@ @ @ @ return 0;}@*
@code{@} }@*
@*

@item
@command{IRC::get_info ( [serveur,] nom );}@*
@*
Obtenir des informations vari@'ees sur WeeChat, le serveur ou l'utilisateur.@*

@emph{Param@`etres :}
@itemize @minus
@item @option{serveur}: nom interne du serveur
@item @option{nom}: nom de l'info @`a obtenir :
@itemize @minus
@item @option{0 ou version}: obtenir la version de WeeChat
@item @option{1 ou nick}: obtenir le pseudo
@item @option{2 ou channel}: obtenir le nom du canal
@item @option{3 ou server}: obtenir le nom du serveur
@item @option{4 ou weechatdir}: obtenir le r@'epertoire maison de WeeChat
@item @option{5 ou away}: obtenir le drapeau "away" du serveur
@end itemize
@end itemize
@*
@emph{Exemples :}@*
@code{$version = get_info("version");}@*
@code{$nick = get_info("freenode", "nick");}@*
@*

@end itemize

@node Scripts Python, Scripts Ruby, Scripts Perl, Extensions
@section Scripts Python

Non d@'evelopp@'e !

@node Scripts Ruby, , Scripts Python, Extensions
@section Scripts Ruby

Non d@'evelopp@'e !

@c **************************** Auteurs / Support *****************************

@node Auteurs / Support, , Extensions, Top
@chapter Auteurs / Support

@ifhtml
@menu
* Auteurs::
* Obtenir du support::
* Copyright::
@end menu
@end ifhtml
@ifnothtml
@menu
* Auteurs::
* Obtenir du support::
@end menu
@end ifnothtml

@node Auteurs, Obtenir du support, Auteurs / Support, Auteurs / Support
@section Auteurs

WeeChat est d@'evelopp@'e par :@*

@itemize @bullet
@item 
FlashCode
<@email{flashcode@@flashtux.org, flashcode AT flashtux.org}>
@item
Bounga
<@email{bounga@@altern.org, bounga AT altern.org}>
@item
Xahlexx
<@email{xahlexx@@tuxfamily.org, xahlexx AT tuxfamily.org}>

@end itemize

@ifhtml
@node Obtenir du support, Copyright, Auteurs, Auteurs / Support
@end ifhtml
@ifnothtml
@node Obtenir du support, , Auteurs, Auteurs / Support
@end ifnothtml
@section Obtenir du support

Avant de faire appel au support, merci de lire la documentation et la
FAQ de WeeChat.@*
(la documentation est le document que vous @^etes en train de lire, si vous
n'avez pas tout lu jusqu'ici, il est encore temps de recommencer !)@*

@itemize @bullet
@item
Support par IRC:@*
- serveur : @b{irc.freenode.net}@*
- canal : @b{#weechat}@*@*
@item
Forum WeeChat : @uref{http://forums.flashtux.org}@*@*
@item
Support par la liste de diffusion :@*
- pour souscrire/d@'esinscrire :@*@uref{http://mail.nongnu.org/mailman/listinfo/weechat-support}.@*
- pour envoyer un mail @`a la liste de diffusion, envoyer @`a :@*@email{weechat-support@@nongnu.org}.@*

Les archives de la liste de diffusion sont ici :@*
@uref{http://mail.nongnu.org/archive/html/weechat-support}@*@*
@item
Voir la page support WeeChat pour plus de d@'etails :@*
@uref{http://weechat.flashtux.org/support.php}

@end itemize

@ifhtml
@node Copyright, , Obtenir du support, Auteurs / Support
@section Copyright

Ce manuel documente le client IRC WeeChat, il fait partie de WeeChat.@*

Copyright @copyright{} 2005 FlashCode
<@email{flashcode@@flashtux.org, flashcode AT flashtux.org}>@*
@*
Ce document peut @^etre utilis@'e sous les termes de la licence GNU General Public
License version 2 ou plus.
@end ifhtml

@bye
