.TH WEECHAT 1 "September 2012" "Sebastien Helleu"

.SH NAME
weechat-curses \- Wee Enhanced Environment for Chat (Curses version)

.SH SYNOPSIS
.B weechat-curses
.RI [ option... ]
.RI [ plugin:option... ]
.br

.SH DESCRIPTION
Fast, light and extensible chat client for many operating systems.
.br
Everything can be done with a keyboard. It is customizable and extensible with scripts.
.br
It is compliant with IRC RFCs 1459, 2810, 2811, 2812, and 2813.

.SH OPTIONS
.TP
.B \-a, \-\-no\-connect
.br
disable auto-connect to servers at startup
.TP
.B \-c, \-\-colors
.br
display default colors in terminal
.TP
.B \-d, \-\-dir <dir>
.br
set WeeChat home dir
.TP
.B \-h, \-\-help
.br
display summary of options
.TP
.B \-k, \-\-keys
.br
display default keys
.TP
.B \-l, \-\-license
.br
display program license
.TP
.B \-p, \-\-no\-plugin
.br
don't load any plugin at startup
.TP
.B \-r, \-\-run\-command
.br
run command(s) after startup (many commands can be separated by semicolons)
.TP
.B \-s, \-\-no\-script
.br
don't load any script at startup
.TP
.B \-v, \-\-version
.br
display WeeChat version

.SH PLUGIN OPTIONS
Options for plugins depend on plugins, you can look at plugins documentation on WeeChat website for more information.
.TP
For example, with irc plugin, you can connect to temporary server with an url like:
.B irc[6][s]://[[nickname][:password]@]server[:port][/#channel1[,#channel2...]]
.TP
To join WeeChat IRC channel support with nick "mynick":
irc://mynick@irc.freenode.net/#weechat
.TP
IPv6 address can be enclosed in brackets to add a port after address, for example:
irc://mynick@[2001:db8:0:85a3::ac1f:8001]:6668/#test

.SH FILES
.TP
.B $HOME/.weechat/weechat.conf
main WeeChat configuration file
.TP
.B $HOME/.weechat/plugins.conf
plugins configuration file
.TP
.B $HOME/.weechat/alias.conf
configuration file for alias plugin
.TP
.B $HOME/.weechat/aspell.conf
configuration file for aspell plugin
.TP
.B $HOME/.weechat/charset.conf
configuration file for charset plugin
.TP
.B $HOME/.weechat/irc.conf
configuration file for IRC plugin
.TP
.B $HOME/.weechat/logger.conf
configuration file for logger plugin
.TP
.B $HOME/.weechat/relay.conf
configuration file for relay plugin
.TP
.B $HOME/.weechat/rmodifier.conf
configuration file for rmodifier plugin
.TP
.B $HOME/.weechat/xfer.conf
configuration file for xfer plugin
.TP
.B $HOME/.weechat/weechat.log
WeeChat log file

.SH LICENSE
Copyright (C) 2003-2012 Sebastien Helleu <flashcode@flashtux.org>
.br
WeeChat is distributed under the GNU General Public License, version 3.
Please read the COPYING file for more information.

.SH BUGS
Please report bugs or feature requests at Savannah website:
.br
- Bugs:
.UR
http://savannah.nongnu.org/bugs/?group=weechat
.br
- Feature requests:
.UR
http://savannah.nongnu.org/task/?group=weechat

.SH AUTHOR
WeeChat is written by Sebastien Helleu <flashcode@flashtux.org>
.br
Web:
.UR
http://www.weechat.org/
