= WeeChat Quick Start Guide
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: es
:toc: left
:sectnums:
:docinfo1:


// TRANSLATION MISSING
Translators:

* Lázaro A. <uranio-235@myopera.com>, 2012


[[start]]
== Iniciar WeeChat

Es recomendable una terminal emulada para X (pero no indispensable)
rxvt-unicode: tiene un buen soporte para UTF-8, y no da problemas con
los atajas de teclados predeterminados.

// TRANSLATION MISSING
Run from your shell:

----
$ weechat
----

[[help_options]]
== Ayuda en linea / Opciones

WeeChat tiene ayuda para todos los comandos, solo teclee:

----
/help
----

Para obtener ayuda específicamente de un comando, teclee:

----
/help comando
----

Para configurar una opción, use:

----
/set config.section.option valor
----

(donde `config` es el nombre de la configuración del núcleo o del
plugin que desea configurar,  `section`, la sección de esa configuración
y `option` el nombre de la opción).

WeeChat usará inmediatamente el nuevo valor asignado (*no* es necesario
reiniciar WeeChat después de aplicar cambios a la configuración).

Usando el comando `/set` con un nombre tecleado parcialmente y el
comodín "*" al principio o al final del texto; pude mostrar todas las
opciones que contienen esas letras. Por ejemplo:

* mostrará todas las opciones de WeeChat y sus plugins:

----
/set
----

* mostrará solo las opciones de WeeChat:

----
/set weechat.*
----

* mostrará las opciones del plugin IRC:

----
/set irc.*
----

Puede mostrar la ayuda de una opción en especifico con  `/help`, por
ejemplo:

----
/help weechat.look.highlight
----

Todas las opciones se salvarán de manera automática cuando cierre
WeeChat o usando el comando `/save` para forzar la forzar a WeeChat a
guardar todos los archivos de configuración.

// TRANSLATION MISSING
[IMPORTANT]
It is *not recommended* to edit configuration files by hand because WeeChat
may write them at any time (for example on <<command_weechat_quit,/quit>>)
and after any change you must run the command <<command_weechat_reload,/reload>>
(with the risk of loosing other changes that were not yet saved with
<<command_weechat_save,/save>>). +
You can use the command <<command_weechat_set,/set>>, which checks the value
and applies immediately the changes.

[[core_vs_plugins]]
== Núcleo vs Plugins

Llamaremos "Núcleo de WeeChat" a la aplicación que solo se usa para
mostrar información en pantalla e interactuar con el usuario, eso es lo
único que hace el núcleo de WeeChat sin no tiene plugins. (para los
fieles seguidores: IRC fue parte del núcleo para las versiones ≤
0.2.6).

Todos los protocolos de red como IRC, provienen en plugins separados.

Use el comando `/plugin` para ver una lista de los plugins cargados,
seguramente vera irc y otros.

// TRANSLATION MISSING
[[add_irc_server]]
== Add an IRC server

// TRANSLATION MISSING
You can add an IRC server with `/server` command, for example:

----
/server add freenode chat.freenode.net
----

La ayuda está disponible; si te pierdes:

----
/help server
----

[[irc_server_options]]
== Personalizar las opciones de un servidor IRC

WeeChat usa las opciones por defecto para todos los servidores
("predeterminado") si no le especifica un valor individual a un servidor
en específico. Esas opciones por defectos son las que se muestran en
"irc.server_default.*"

Para cada opción de "server", WeeChat usa estos valores previamente
asignados siempre y cuando no sean Nulos. Si no hay nada asignado,
WeeChat usara los valores predeterminados ("irc.server_default.xxx")

Por ejemplo, tenemos el nick por defecto (que se basa en su login) pero
usted puedes sobreescribirlo para el servidor identificado como freenode
de la siguiente manera:

----
/set irc.server.freenode.nicks "nick,nick2,nick3,nick4,nick5"
----

También para configurar el nombre de usuario y el nombre real:

----
/set irc.server.freenode.username "Mi nombre de usuario"
/set irc.server.freenode.realname "Mi nombre real"
----

Para que el servidor se conecte cuando WeeChat inicie:

----
/set irc.server.freenode.autoconnect on
----

// TRANSLATION MISSING
To connect with SSL:

----
/set irc.server.freenode.addresses "chat.freenode.net/7000"
/set irc.server.freenode.ssl on
----

// TRANSLATION MISSING
If SASL is available on server, you can use it for authentication (you will be
identified before you join channels):

----
/set irc.server.freenode.sasl_username "nick"
/set irc.server.freenode.sasl_password "xxxxxxx"
----

// TRANSLATION MISSING
To run a command after connection to server, for example to authenticate
with nickserv (only if you don't use SASL for authentication):

----
/set irc.server.freenode.command "/msg nickserv identify xxxxxxx"
----

// TRANSLATION MISSING
[NOTE]
Many commands in option _command_ can be separated by `;` (semi-colon).

// TRANSLATION MISSING
If you want to protect your password in configuration files, you can use
secured data.

// TRANSLATION MISSING
First setup a passphrase:

----
/secure passphrase this is my secret passphrase
----

// TRANSLATION MISSING
Then add a secured data with your freenode password:

----
/secure set freenode_password xxxxxxx
----

// TRANSLATION MISSING
Then you can use `+${sec.data.freenode_password}+` instead of your password in
IRC options mentioned above, for example:

----
/set irc.server.freenode.sasl_password "${sec.data.freenode_password}"
----

Para unirse automáticamente a canales cuando el servidor se conecte:

----
/set irc.server.freenode.autojoin "#uncanal,#otrocanal"
----

Para eliminar un valor asignado a una opción de servidor y usar los
valores por defecto en su lugar, por ejemplo, usar el nick por defecto
(irc.server_default.nicks):

----
/set irc.server.freenode.nicks null
----

Otras opciones: pude configurar otras opciones con el siguiente comando,
donde "xxx" es el nombre de la opción.

----
/set irc.server.freenode.xxx valor
----

[[connect_to_irc_server]]
== Conectarse a un servidor IRC

----
/connect freenode
----

[NOTE]
Este comando también puede usarse para crear y conectarse a un nuevo
servidor sin usar el comando `/server` (¿debo reiterar que se puede ver
la ayuda de este comando con `/help connect`?).

Por defecto, todos los buffers del servidor están junto al buffer de
núcleo. Para cambiar entre el buffer del núcleo y el buffer de los
servidores use kbd:[Ctrl+x].

Es posible deshabilitar esta manera de tener todos los buffer de
servidores juntos para tenerlos de manera independiente:

----
/set irc.look.server_buffer independent
----

[[join_part_irc_channels]]
== join/part y canales IRC

Se une a un canal llamado "#canal":

----
/join #canal
----

Sale de un canal (mantiene el buffer abierto):

----
/part [mensaje de partida]
----

// TRANSLATION MISSING
Close a server, channel or private buffer (`/close` is an alias for
`/buffer close`):

----
/close
----

// TRANSLATION MISSING
[WARNING]
Closing the server buffer will close all channel/private buffers.

// TRANSLATION MISSING
Disconnect from server, on the server buffer:

----
/disconnect
----

// TRANSLATION MISSING
[[irc_private_messages]]
== IRC private messages

Open a buffer and send a message to another user (nick _foo_):

----
/query foo this is a message
----

Close the private buffer:

----
/close
----

[[buffer_window]]
== Manipulando buffer/ventana

Un buffer, es un componente vinculado a un plugin con un número, una
categoría y un nombre. El buffer contiene los datos que se muestran en
la pantalla.

Una ventana es una vista de un buffer. Por defecto, una sola ventana
muestra un solo buffer. Si divide la pantalla, podrá ver muchas
ventanas conteniendo varios buffer al mismo tiempo.

Comandos para manipular buffer y ventana:

----
/buffer
/window
----

(le reitero que puede obtener ayuda de los comandos con /help buffer y
/help ventana respectivamente)

Por ejemplo, para dividir la pantalla una pequeña ventana (1/3)
junto a otras mas grande (2/3) use el comando

----
/window splitv 33
----

// TRANSLATION MISSING
To remove the split:

----
/window merge
----

[[key_bindings]]
== Atajos de teclado

WeeChat usa muchas teclas por defecto. Las mismas, están bien
explicadas en la documentación pero debe conocer al menos la mas
importantes.

- kbd:[Alt+←] / kbd:[Alt+→] o kbd:[F5] / kbd:[F6]: Cambiara al buffer
  siguiente/anterior
- kbd:[F7] / kbd:[F8]: Cambiara a la siguiente/anterior ventana (cuando la pantalla
  este dividida)
- kbd:[F9] / kbd:[F10]: desplazamiento del texto en la barra de titulo
- kbd:[F11] / kbd:[F12]: desplazamiento del texto en la lista de nick
- kbd:[Tab]: Completa los textos o nick que se escriben
- kbd:[PgUp] / kbd:[PgDn]: desplazamiento del texto en el buffer
- kbd:[Alt+a]: salta al siguiente buffer con actividad reciente

De acuerdo con su teclado y/o sus necesidades, puede asignar teclas a un
comando usando el comando `/key`.
Una combinación de teclas muy valiosa es kbd:[Alt+k] para hallar el código de
alguna tecla.

Por ejemplo, para asignar la combinación kbd:[Alt+!] al comando `/buffer close`:

----
/key bind (presionamos alt-k) (presionamos alt-!) /buffer close
----

El comando se vera mas o menos así:

----
/key bind meta-! /buffer close
----

Para eliminar una combinación:

----
/key unbind meta-!
----

[[plugins_scripts]]
== Plugins/scripts

En algunas distribuciones como Debian, los plugins están disponibles en
un paquete separado (como weechat-plugin).
Los plugins se cargan de manera automática cuando son encontrados por WeeChat
(por favor, refierase a la documentación de WeeChat para ver como cargar/descargar
plugins y scripts).

// TRANSLATION MISSING
Many external scripts (from contributors) are available for WeeChat, you can
download and install scripts from the repository with the `/script` command,
for example:

----
/script install iset.pl
----

// TRANSLATION MISSING
See `/help script` for more info.

// TRANSLATION MISSING
A list of scripts is available in WeeChat with `/script` or at this URL:
https://weechat.org/scripts

[[more_doc]]
== Más documentación

Ahora puede usar WeeChat y leer las FAQ/documentación para cada pregunta
en: https://weechat.org/doc

Disfrute de WeeChat!
