= WeeChat preguntas frecuentes (FAQ)
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: es
:toc: left
:toclevels: 2
:sectnums:
:sectnumlevels: 2
:docinfo1:

Traductores

* Victorhck <victorhck.mailbox.org>, 2021


Este documento está escrito para WeeChat versiones ≥ 0.3.0 pero preferiblemente
usar mejor la última versión estable de WeeChat.

toc::[]


[[general]]
== General

[[weechat_name]]
=== ¿De dónde proviene el nombre de "WeeChat"?

"Wee" es un acrónimo recursivo que proviene de "Wee Enhanced Environment" (Entorno Mejorado Wee).
Así que el nombre completo sería "Wee Enhanced Environment for Chat" (Entorno Mejorado Wee para Chat).

"Wee" también significa "muy pequeño" (y sí, hay otros significados, pero estos
no se aplican a WeeChat!).

[[why_choose_weechat]]
=== ¿Por qué escoger WeeChat? X-Chat o Irssi son buenos...

Porque WeeChat es muy ligero y ofrece funcionalidades innovadoras.

Más información de las funcionalidades de WeeChat en la página: https://weechat.org/about/features

[[compilation_install]]
== Compilación / instalación

[[gui]]
=== ¿He oido que hay muchas interfaces gráficas de susuario (GUI) para WeeChat. ¿Cómo puedo compilarlas o usarlas?

Hay disponibles algunas GUIs, eche un vistazo a la página de interfaces remotas:
https://weechat.org/about/interfaces

[[compile_git]]
=== No puedo compilar WeeChat después de haber clonado el repositorio git, ¿por qué?

La manera recomendada para compilar WeeChat es con
link:weechat_user.en.html#compile_with_cmake[CMake].

Si lo está compilando con link:weechat_user.en.html#compile_with_autotools[autotools]
(y no con CMake), compruebe que tiene la versión más reciente de autoconf y automake.

Otra forma es instalar "devel package", que necesita menos dependencias.
Este paquete está compilado casi cada día utilizando el repositorio git. Tenga en cuenta que este
paquete puede no corresponder exactamente con la base de git y es menos conveniente
que la opción de clonar el repositorio de git a la hora de instalar actualizaciones.

[[compile_macos]]
=== ¿Cómo puedo instalar WeeChat en macOS?

Se recomienda utilizar https://brew.sh/[Homebrew], puede obtener ayuda con el comando:

----
brew info weechat
----

Puede instalar WeeChat con este comando:

----
brew install weechat
----

[[lost]]
=== He lanzado WeeChat, pero estoy perdido, ¿qué puedo hacer?

Para consultar la ayuda, escriba `/help`. Para buscar ayuda con un comando, escriba `/help command`.
link:weechat_user.en.html#key_bindings[La teclas] y
link:weechat_user.en.html#commands_and_options[comandos] aparecen listados
en la documentación.

Se recomienda a las personas recién llegadas leer la
link:weechat_quickstart.es.html[guía rápida].

[[display]]
== Visualización

[[charset]]
=== No veo algunos caracteres con acentos ¿qué puedo hacer?

Es un problema común con una variedad de causas, por favor lea detenidamente y compruebe
*TODAS* las soluciones que se muestran a continuación:

* Compruebe que weechat está enlazado a libncursesw (atención: es necesario en la mayoría
  de distribuciones, pero no en todas): `ldd /ruta/a/weechat`.
* Compruebe que el complemento "charset" está cargado mediante el comando `/plugin` (si no lo está,
  entonces probablemente necesite el paquete "weechat-plugins").
* Compruebe la salida del comando `/charset` (en el buffer principal). Debería ver
  _ISO-XXXXXX_ o _UTF-8_ para los caracteres de la terminal. Si ve _ANSI_X3.4-1968_ u
  otros valores, su idioma probablemente sea erróneo. +
  Para solucionarlo, compruebe que tiene los idiomas instalados mediante `locale -a` y establezca
  un valor apropiado en $LANG, por ejemplo: `+export LANG=es_ES.UTF-8+`.
* Estableza un valor global, por ejemplo:
  `/set charset.default.decode "ISO-8859-15"`.
* Si está utilizando UTF-8:
** Compruebe que su terminal está preparado para UTF-8 (la terminal recomendada para UTF-8 es
   rxvt-unicode).
** Si está utilizando el multiplexador screen, compruebe que lo está ejecuando con el modo UTF-8 
   ("`defutf8 on`" en ~/.screenrc o `screen -U` al ejecutar screen).
* Compruebe si la opción
  link:weechat_user.en.html#option_weechat.look.eat_newline_glitch[_weechat.look.eat_newline_glitch_]
  está en off (esta opción puede causar errores a la hora de mostrar el texto).

[NOTE]
Se recomienda utilizar UTF-8 para WeeChat. Si está utilizando ISO u otras opciones,
por favor, compruebe que *todos* sus ajustes (terminal, screen, ..) también están en ISO
y *no* en UTF-8.

[[unicode_chars]]
=== Algunos caracteres unicode se muestran en la terminal pero no en WeeChat, ¿por qué?

Esto puede estar causado por un error en libc en la función _wcwidth_, que debería estar solucionado
en glibc 2.22 (quizás todavía no está disponible en su distribución).

Hay una solución temporal que es utilizar una función de _wcwidth_ sin ese error:
https://blog.nytsoi.net/2015/05/04/emoji-support-for-weechat

Vea este reporte de error para más información:
https://github.com/weechat/weechat/issues/79

[[bars_background]]
=== Las barras del título y de estado no aparecen rellenadas, el color de fondo desaparece después del texto, ¿por qué

Esto puede estar causado por un valor erróneo en la variable TERM en su sheel (eche un vistazo a 
la salida del comando `echo $TERM` en su terminal).

Dependiendo de donde ejecute WeeChat, debería tener:

* Si WeeChat se ejecuta de manera local o en una máquina remota sin el multiplexador de terminal screen ni tmux, esto
  depende de la terminal utilizada: _xterm_, _xterm-256color_, _rxvt-unicode_,
  _rxvt-256color_, etc.
* Si WeeChat se ejecuta en el multiplexador de terminal screen, debería tener _screen_ o _screen-256color_.
* Si WeeChat se ejecuta en el multiplexador de la terminal tmux, debería tener _tmux_, _tmux-256color_,
  _screen_ o _screen-256color_.

Si es necesario, modifique su variable TERM: `export TERM="xxx"`.

[[screen_weird_chars]]
=== Cuando estoy utilizando Weechat con screen o tmux, veo de manera aleatoria caracteres extraños, ¿cómo puedo solucionar eso?

Esto puede ser causado por un valor erróneo de la variable TERM en su shell (eche un vistazo
a la salida del comando `echo $TERM` en su terminal, *fuera de una sesión de screen o tmux*). +
Por ejemplo, _xterm-color_ puede mostrar caracteres extraños, puede utilizar _xterm_
que es mejor (como muchos otros valores). +
Si es necesario, cambie el valor se su variable TERM mediante: `export TERM="xxx"`.

Si está utilizando gnome-terminal, compruebe que la opción
"Ambiguous-width characters" en el menú Preferencias/Perfil/Compatibilidad
está establecida a `narrow` o `estrecho`.

[[macos_display_broken]]
=== He compilado WeeChat en macOS, y veo "(null)" por todas partes en screen, ¿qué está mal?

Si ha compilado ncursesw usted mismo, trate de utilizar el ncurses estándar (el que viene
con el sistema).

Es más, en macOS, se recomienda instalar WeeChat mediante el gesto de paquetes
Homebrew.

[[buffer_vs_window]]
=== He escuchado cosas sobre "buffers" y "ventanas", ¿cual es la diferencia?

Un _buffer_ está compuesto por un número, un nombre, y unas líneas mostradas (y algunos otros
datos).

Una _ventana_ es un área de la pantalla en la que se muestra un _buffer_. Es posible dividir
su pantalla en muchas ventanas.

Cada ventana muestra un buffer, o un grupo de buffers unidos.
Un buffer puede ser ocultado (no mostrado en una ventana) o mostrado por una o más
ventanas.

[[buffers_list]]
=== ¿Cómo mostrar un listado de los buffers en la parte izquierda?

Con WeeChat ≥ 1.8, el complemento link:weechat_user.en.html#buflist_plugin[buflist]
está cargado y habilitado de manera predeterminada.

Con versiones anteriores, puede instalar el script _buffers.pl_:

----
/script install buffers.pl
----

Para limitar el tamaño de la barra (reemplace "buflist" por "buffers" si está utilizando el script
_buffers.pl_):

----
/set weechat.bar.buflist.size_max 15
----

Para mover la barra a la parte inferior:

----
/set weechat.bar.buflist.position bottom
----

Para desplazar la barra (hacer _scroll_): si el ratón está habilitado (key: kbd:[Alt+m]), puede hacerlo
con la rueda del ratón.

Las teclas predeterminadas para _hacer scroll_ en la barra son kbd:[F1] (o kbd:[Ctrl+F1]), kbd:[F2]
(o kbd:[Ctrl+F2]), kbd:[Alt+F1] y kbd:[Alt+F2].

Para el script _buffers.pl_, puede definir las teclas, similares a las teclas existentes para
hacer _scroll_ en la lista de apodos. +
Por ejemplo para utilizar kbd:[F1], kbd:[F2], kbd:[Alt+F1] y kbd:[Alt+F2]:

----
/key bind meta-OP /bar scroll buffers * -100%
/key bind meta-OQ /bar scroll buffers * +100%
/key bind meta-meta-OP /bar scroll buffers * b
/key bind meta-meta-OQ /bar scroll buffers * e
----

[NOTE]
Las teclas "meta-OP" y "meta-OQ" pueden ser diferentes en su terminal. Para encontrar el código
de la tecla, pulse kbd:[Alt+k] y después la tecla.

[[customize_buflist]]
=== ¿Cómo puedo personalizar la lista de lista de buffers, como el color, del buffer activo?

Puede navegar por las opciones del listado de buffers con el comando:

----
/fset buflist
----

El fondo del buffer activo es azul de manera predeterminada, puede cambiarlo
así, por ejemplo a rojo `red`:

----
/set buflist.format.buffer_current "${color:,red}${format_buffer}"
----

[NOTE]
Hay una coma antes del nombre color "red" porque es utilizado como fondo,
no el color del texto. +
También se puede utilizar cualquier color numérico en vez del nombre `red`,
como `237` para gris oscuro.

El complemento del listado de buffers _buflist_ ofrece múltiples opciones que puede configurar, por favor lea 
la ayuda de cada opción.

También hay una página wiki con ejemplos de configuraciones más completas:
https://github.com/weechat/weechat/wiki/buflist

[[customize_prefix]]
=== ¿Cómo puedo reducir la longitud de los apodos o eliminar la alineación de los apodos en el área del chat?

Para reducir la longitud máxima de los apodos en el área del chat:

----
/set weechat.look.prefix_align_max 15
----

Para eliminar la alineación de los apodos:

----
/set weechat.look.prefix_align none
----

[[status_hotlist]]
=== ¿Qué significa el texto What does the [H: 3(1,8), 2(4)] que aparece en la barra de estado?

Esto es lo que se llama "hotlist", una lista de _buffers_ con el número de mensajes
sin leer, por orden: resaltados, mensajes privados, mensajes, otros mensajes
(como mensajes de unión o abandono de la sala). +
El número de "mensajes sin leer" es el número de mensajes mostrados/recibidos
desde que sisitaste el buffer.

En este ejemplo `[H: 3(1,8), 2(4)]`, son:

* 1 mensaje resaltado y 8 mensajes sin leer en el buffer #3,
* 4 mensajes sin leer en el buffer #2.

El color del buffer/contador depende del tipo de mensaje, los colores predeterminados
son:

* resaltado: `lightmagenta` / `magenta`
* mensaje privado: `lightgreen` / `green`
* mensaje: `yellow` / `brown`
* otros mensajes: `default` / `default` (color del texto de la terminal)

Estos colores pueden ser cambiados con las opciones __weechat.color.status_data_*__
(buffers) y __weechat.color.status_count_*__ (contadores). +
Otras opciones de la lista rápida o _hotlist_ pueden ser cambiadas con las opciones __weechat.look.hotlist_*__.

Vea link:weechat_user.en.html#screen_layout[Guía de usuario / diseño de la pantalla] para
más información sobre este tema.

[[input_bar_size]]
=== ¿Cómo utilizar la línea de comandos con más de una línea?

La opción _size_ en la barra de entrada puede ser ajustada a un valor mayor que 1 (para un tamaño
fijo, el tamaño predeterminado es 1) o 0 para un tamaño dinámico, y después la opción _size_max_ establecerá
el tamaño máximo (0 = sin límite).

Ejemplo con tamaño dinámico:

----
/set weechat.bar.input.size 0
----

Máximo tamano de 2:

----
/set weechat.bar.input.size_max 2
----

[[one_input_root_bar]]
=== ¿Es posible mostrar solo una barra de entrada para todas las ventanas (después de haberla dividido)?

Sí, deberás crear una barra con el tipo "root" (con un elemento conocido en 
qué ventana estás), después eliminar la barra de entrada.

Por ejemplo:

----
/bar add rootinput root bottom 1 0 [buffer_name]+[input_prompt]+(away),[input_search],[input_paste],input_text
/bar del input
----

Si alguna vez no te safisface este, simplemente elimina la nueva barra, WeeChat automáticamente
creará la barra predeterminada "input" si el elemento "input_text" no está utilizado
en ninguna barra:

----
/bar del rootinput
----

[[terminal_copy_paste]]
=== ¿Cómo puedo copiar/pegar texto sin pegar la lista de apodos?

Con WeeChat ≥ 1.0, puedes utilizar una visualización simple (la tecla predeterminada: kbd:[Alt+l] (`L`)),
que mostrará solo el contenido de la ventana actual seleccionada,
sin ningún tipo de formato de texto.

Puede utilizar una terminal con selección rectangualr (como rxvt-unicode,
konsole, gnome-terminal, etc.). La tecla normalmente es kbd:[Ctrl] + kbd:[Alt] + la selección
con el ratón.

Otra solución es mover la lista de apodos a la parte superior o inferior, por ejemplo:

----
/set weechat.bar.nicklist.position top
----

[[urls]]
=== ¿Cómo puedo hacer clic sobre direcciones URL largas (de más de una línea)?

Con WeeChat ≥ 1.0, puede utilizar la visualización simple (la tecla predeterminada: kbd:[Alt+l] (`L`)).

Para abrir direcciones URL más fácilmente, puede:

* mover la lista de apodos a la parte superior con este comando:

----
/set weechat.bar.nicklist.position top
----

* inhabilitar la alineación de palabras multilínea (WeeChat ≥ 1.7):

----
/set weechat.look.align_multiline_words off
----

* o para todas las líneas unidas:

----
/set weechat.look.align_end_of_lines time
----

Con WeeChat ≥ 0.3.6, puede habilitar la opción "eat_newline_glitch", así
el caractere de la nueva línea no es añadido al final de cada línea mostrada (esto no romperá
la selección de la dirección URL):

----
/set weechat.look.eat_newline_glitch on
----

[IMPORTANTE]
Esta opción puede causar errores almostrar el contenido. Si experimenta algún problema de estos, deberá 
eliminar esa opción.

Otra solución es utilizar un script:

----
/script search url
----

[[change_locale_without_quit]]
=== Quiero cambiar el lenguaje utilizado por WeeChat para los mensajes, pero sin salir de WeeChat, ¿es esto posible?

Por supuesto que es posible:

----
/set env LANG en_US.UTF-8
/upgrade
----

[[timezone]]
=== ¿Cómo puedo cambiar la zona horaria?

No hay razón en WeeChat para cambiar la zona horaria, la variable de entorno
`TZ` deberá estar ajustada al valor apropiado.

En el archivo de inicialización de su shell o en la línea de comando, antes de ejecutar WeeChat:

----
export TZ=America/New_York
----

En WeeChat, el nuevo valor es inmediatamente utilizado:

----
/set env TZ America/New_York
----

[[use_256_colors]]
=== ¿Cómo puedo utilizar 256 colors en WeeChat?

256 colors están admitidos con WeeChat ≥ 0.3.4.

Priemro compruebe que su variable de entorno _TERM_ es correcta, los valores recomendados
son:

* en screen: _screen-256color_
* en tmux: _screen-256color_ or _tmux-256color_
* fuera de screen/tmux: _xterm-256color_, _rxvt-256color_, _putty-256color_, ...

[NOTE]
Puede tener que instalar el paquete "ncurses-term" para utilizar estos valores en la variable _TERM_.

Si está utilizando el multiplexador screen, puede añadir esta línea en su archivo de configuración _~/.screenrc_:

----
term screen-256color
----

Si su variable _TERM_ tiene un valor erróneo y ya WeeChat está ejecutándose,
puede cambiarlo con estos dos comandos (en WeeChat ≥ 1.0):

----
/set env TERM screen-256color
/upgrade
----

Para la versión 0.3.4, deberá utilizar el comando `/color` para añadir nuevos colores.

Para versiones ≥ 0.3.5, puede utilizar cualquier número de color en las opciones (opcional: puede
añadir alias al color con el comando `/color`).

Por favor lea la link:weechat_user.en.html#colors[Guía del usuario / Colores] para más
información sobre la gestión de los colores.

[[search_text]]
=== ¿Cómo busco texto en un buffer (como /lastlog en irssi)?

La tecla predeterminada es kbd:[Ctrl+r] (el comando es: `+/input texto_a_buscar_aquí+`).
Y para saltar a los textos resaltados: kbd:[Alt+p] / kbd:[Alt+n].

Vea la link:weechat_user.en.html#key_bindings[Guía del usuario / Atajos de teclado] para más
información sobre esta funcionalidad.

[[terminal_focus]]
=== ¿Cómo puedo ejecutar comandos cuando la terminal tiene o pierde el foco?

Puede habilitar el foco de los eventos con un código enviado a la terminal.

*Importante*:

* Deberá utilizar una terminal moderna compatible con xterm.
* De manera adicionar, parece importante que su valor de la variable TERM 
  sea igual a _xterm_ o _xterm-256color_.
* Si está utilizando tmux, deberá de manera adiciona habilitar los eventos del foco añadiendo
  `set -g focus-events on` en su fichero de configuración _.tmux.conf_.
* Esto *no* funciona bajo el multiplexado screen.

Para enviar el código cuando WeeChat es arrancado:

----
/set weechat.startup.command_after_plugins "/print -stdout \033[?1004h\n"
----

Y después enlazar dos teclas para el foco (reemplazar los comandos `/print` por los
comandos que prefiera):

----
/key bind meta2-I /print -core focus
/key bind meta2-O /print -core unfocus
----

Por ejemplo, para marcar buffers como leidos cuando una terminal pierde el foco:

----
/key bind meta2-O /input set_unread
----

[[screen_paste]]
=== Cuando WeeChat se está ejecutando en el multiplexador screen, al pegar texto en otra ventana de screen añade ~0 y ~1 alrededor del texto, ¿por qué?

Esto es causado por la opción de pegado de corchetes que está habilitado de manera predeterminada, y
no está adecuadamente gestionada por screen en otras ventanas.

Puede inhabilitar este modo de pegado con este comando:

----
/set weechat.look.paste_bracketed off
----

[[small_terminal]]
=== ¿Cómo puedo personalizar cómo se muestra para tamaños de terminales pequeñas (como 80x25), para no malgastar espacio?

Puede eliminar las barras laterales (lista de buffers y lista de apodos), cambie el formato en que se muestra la hora
para mostrar solo horas y segundos, inhabilite la alineación de mensajes y un juego de caracteres para
prefijos/sufijos de apodos:

----
/set buflist.look.enabled off
/bar hide nicklist
/set weechat.look.buffer_time_format "%H:%M"
/set weechat.look.prefix_align none
/set weechat.look.align_end_of_lines prefix
/set weechat.look.nick_suffix ">"
/set weechat.look.nick_prefix "<"
----

Terminal 80x25, con configuración predeterminada:

....
┌────────────────────────────────────────────────────────────────────────────────┐
│1.local     │Welcome on WeeChat channel!                                        │
│  weechat   │16:27:16        --> | FlashCode (~flashcode@localhost)  │@FlashCode│
│2.  #weechat│                    | has joined #weechat               │ bob      │
│            │16:27:16         -- | Mode #weechat [+nt] by hades.arpa │          │
│            │16:27:16         -- | Channel #weechat: 1 nick (1 op, 0 │          │
│            │                    | voices, 0 normals)                │          │
│            │16:27:18         -- | Channel created on Sun, 22 Mar    │          │
│            │                    | 2020 16:27:16                     │          │
│            │17:02:28        --> | bob (~bob_user@localhost) has     │          │
│            │                    | joined #weechat                   │          │
│            │17:03:12 @FlashCode | hi bob, you're the first user     │          │
│            │                    | here, welcome on the WeeChat      │          │
│            │                    | support channel!                  │          │
│            │17:03:33        bob | hi FlashCode                      │          │
│            │                                                        │          │
│            │                                                        │          │
│            │                                                        │          │
│            │                                                        │          │
│            │                                                        │          │
│            │                                                        │          │
│            │                                                        │          │
│            │                                                        │          │
│            │                                                        │          │
│            │[17:04] [2] [irc/local] 2:#weechat(+nt){2}                         │
│            │[@FlashCode(i)] █                                                  │
└────────────────────────────────────────────────────────────────────────────────┘
....

Terminal 80x25, después de los cambios:

....
┌────────────────────────────────────────────────────────────────────────────────┐
│Welcome on WeeChat channel!                                                     │
│16:27 --> FlashCode (~flashcode@localhost) has joined #weechat                  │
│16:27 -- Mode #weechat [+nt] by hades.arpa                                      │
│16:27 -- Channel #weechat: 1 nick (1 op, 0 voices, 0 normals)                   │
│16:27 -- Channel created on Sun, 22 Mar 2020 16:27:16                           │
│17:02 --> bob (~bob_user@localhost) has joined #weechat                         │
│17:03 <@FlashCode> hi bob, you're the first user here, welcome on the WeeChat   │
│      support channel!                                                          │
│17:03 <bob> hi FlashCode                                                        │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│                                                                                │
│[17:04] [2] [irc/local] 2:#weechat(+nt){2}                                      │
│[@FlashCode(i)] █                                                               │
└────────────────────────────────────────────────────────────────────────────────┘
....

[[key_bindings]]
== Key bindings

[[meta_keys]]
=== Algunas teclas (alt + tecla) no funcionan, ¿por qué?

Si está utilizando algunas terminales como xterm o uxterm, algunas teclas no
funcionan de manera predeterminada. Puede añadir una línea en el archivo _~/.Xresources_:

* Para xterm:
----
XTerm*metaSendsEscape: true
----
* Para uxterm:
----
UXTerm*metaSendsEscape: true
----

Y después recargar el archivo (`xrdb -override ~/.Xresources`) o reiniciar el servidor gráfico X.

Si está utilizando aplicación Terminal de macOS, habilite la opción
"Use option as meta key" en el menú Settings/Keyboard después de la cual puede utilizar la tecla 
kbd:[Option] como tecla meta.

[[customize_key_bindings]]
=== ¿Cómo puedo personalizar los atajos de teclado?

Los atajos de teclado son personalizables con el comando `/key`.

La combinación predeterminadad kbd:[Alt+k] le permite guardar el código de la tecla e insertarlo en la línea de comando.

[[jump_to_buffer_11_or_higher]]
=== ¿Cual es la tecla para saltar al buffer 11 (o un número mayor)?

La tecla es kbd:[Alt+j] y después introducir 2 dígitos, por ejemplo kbd:[Alt+j], kbd:[1],
kbd:[1] para saltar al buffer 11.

Puede crear un atajo de teclado, por ejemplo:

----
/key bind meta-q /buffer *11
----

Tiene una lista de las teclas predeterminadas en la
link:weechat_user.en.html#key_bindings[Guía del usuario / Atajos de teclado].

Para saltar a un buffer mayor de 100, podría definir un disparador y después utilizar
comandos como `/123` para saltar al buffer #123:

----
/trigger add numberjump modifier "2000|input_text_for_buffer" "${tg_string} =~ ^/[0-9]+$" "=\/([0-9]+)=/buffer *${re:1}=" "" "" "none"
----

[[global_history]]
=== ¿Cómo utilizar el historial globale (en vez del historial del buffer) con las teclas de las flechas arriba y abajo?

Puede asociar las teclas de las flechas arriba y abajo en el historial global (las teclas predeterminadas para el historial
global son kbd:[Ctrl+↑] y kbd:[Ctrl+↓]).

Ejemplo:

----
/key bind meta2-A /input history_global_previous
/key bind meta2-B /input history_global_next
----

[NOTE]
Las telcas "meta2-A" y "meta2-B" pueden ser diferentes en su terminal. Para encontrar el código
de la tecla pulse kbd:[Alt+k] y después la tecla.

[[mouse]]
== Ratón

[[mouse_not_working]]
=== El ratón no funciona en absoluto, ¿qué puedo hacer?

El ratón tiene soporte desde WeeChat ≥ 0.3.6.

Primero trate de habilitar el ratón:

----
/mouse enable
----

Si el ratón sigue sin funcionar, compruebe la variable TERM en su shell (eche un vistazo
a la salida de `echo $TERM` en su terminal).
De acuerdo a la información usada, el ratón podrá o no estar soportado.

Puede comprobar el soporte del ratón en la terminal:

----
$ printf '\033[?1002h'
----

Y después haga clic en el primer caracter de la terminal (superior izquierdo). Debería ver " !!#!!".

Para inhabilitar el ratón en la terminal:

----
$ printf '\033[?1002l'
----

[[mouse_coords]]
=== El ratón no hace nada para coordenadas X o Y mayores de 94 (o 222), ¿por qué?

Algunas terminales solo envían caracteres ISO para las coordenadas del ratón, así que esto no
funciona para X/Y mayores de 94 (o 222).

Debería utilizar una terminal que admitiera coordenadas UTF-8 para el ratón, como
rxvt-unicode.

[[mouse_select_paste]]
=== ¿Cómo puedo seleccionar o pegar texto en la terminal cuando el ratón está habilitado en WeeChat?

Cuando el ratón está habilitado en WeeChat, puede utilizar el modificador kbd:[Shift] para seleccionar o
hacer clik en la terminal, como si el ratón estuviera inhabilitado (en algunos terminales como iTerm,
tiene que utilizar kbd:[Alt] en vez de kbd:[Shift]).

[[irc]]
== IRC

[[irc_ssl_connection]]
=== Tengo algunos problemas al conectarme a un servidor utilizando SSL, ¿qué puedo hacer?

Si está utilizando macOS, deberá instalar `openssl` desde Homebrew.
Se añadirá un archivo CA que utiliza los certificados del sistema.

Con WeeChat ≤ 3.1, puede establecer la ruta de los certificados del sistema:

----
/set weechat.network.gnutls_ca_file "/usr/local/etc/openssl/cert.pem"
----

Si ve errores en gnutls handshake, puede intentar utilizar la clave más pequeña
Diffie-Hellman (la predeterminada es 2048):

----
/set irc.server.example.ssl_dhkey_size 1024
----

Si ve errores sobre el certificado, puede inhabilitar "ssl_verify" (tenga cuidado,
la conexión será menos segura haciendo esto):

----
/set irc.server.example.ssl_verify off
----

Si el servidor tiene un certificado inválido y usted conoce qué certificado
debería ser, puede especificar la huella (fingerprint) (SHA-512, SHA-256 or SHA-1):

----
/set irc.server.example.ssl_fingerprint 0c06e399d3c3597511dc8550848bfd2a502f0ce19883b728b73f6b7e8604243b
----

[[irc_ssl_handshake_error]]
=== Al conectar a un servidor con SSL, solo veo el error "TLS handshake failed", ¿qué puedo hacer?

Puede intentar una cadena de prioridad diferente (WeeChat ≥ 0.3.5 únicamente), reemplace "xxx"
por el nombre de su servidor:

----
/set irc.server.xxx.ssl_priorities "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.0:+VERS-SSL3.0:%COMPAT"
----

[[irc_ssl_libera]]
=== ¿Cómo puedo conectarme al servidor libera utilizando SSL?

Con WeeChat ≤ 3.1, establezca la opción _weechat.network.gnutls_ca_file_ en el archivo con
los certificados:

----
/set weechat.network.gnutls_ca_file "/etc/ssl/certs/ca-certificates.crt"
----

Nota: Si está ejecutando macOS con homebrew openssl instalado, puede ejecutar:

----
/set weechat.network.gnutls_ca_file "/usr/local/etc/openssl/cert.pem"
----

[NOTE]
Compruebe que tiene este archivo en su sistema (normalmente viene ofrecido por el paquete
"ca-certificates").

Establezca el puerto del servidor, SSL, después conecte:

----
/set irc.server.libera.addresses "irc.libera.chat/6697"
/set irc.server.libera.ssl on
/connect libera
----

[[irc_oauth]]
=== How to connect to a server that requires "oauth"?

Some servers like _twitch_ require oauth to connect.

The oauth is simply a password with the value "oauth:XXXX".

You can add such server and connect with following commands (replace name
and address by appropriate values):

----
/server add name irc.server.org -password=oauth:XXXX
/connect name
----

[[irc_sasl]]
=== How can I be identified before joining channels?

If the server supports SASL, you should use that instead of sending the
command for nickserv authentication, for example:

----
/set irc.server.libera.sasl_username "mynick"
/set irc.server.libera.sasl_password "xxxxxxx"
----

If the server does not support SASL, you can add a delay (between command and
join of channels):

----
/set irc.server.libera.command_delay 5
----

[[edit_autojoin]]
=== How can I add/remove channels from autojoin option?

You can use the `/set` command to edit the list of autojoin channels,
for example for the "libera" server:

----
/set irc.server.libera.autojoin [TAB]
----

[NOTE]
You can complete the name and value of option with the kbd:[Tab] key
(or kbd:[Shift+Tab] for partial completion, useful for the name). +
This way you don't have to type the whole list of channels.

You can also use the `/fset` command to edit the list of channels:

----
/fset autojoin
----

Another solution is to use a script:

----
/script search autojoin
----

[[ignore_vs_filter]]
=== What is the difference between the /ignore and /filter commands?

The `/ignore` command is an IRC command, so it applies only for IRC buffers
(servers and channels).
It lets you ignore some nicks or hostnames of users for a server or channel
(command will not apply on content of messages).
Matching messages are deleted by IRC plugin before display (so you'll
never see them, and can't be recovered by removing the ignore).

The `/filter` command is a WeeChat core command, so it applies to any buffer.
It lets you filter some lines in buffers with tags or regular expression for
prefix and content of line.
Filtered lines are only hidden, not deleted, and you can see them if you
disable filters (by default, the key kbd:[Alt+=] toggles filters).

[[filter_irc_join_part_quit]]
=== How can I filter join/part/quit messages on IRC channels?

With smart filter (keep join/part/quit from users who spoke recently):

----
/set irc.look.smart_filter on
/filter add irc_smart * irc_smart_filter *
----

With a global filter (hide *all* join/part/quit):

----
/filter add joinquit * irc_join,irc_part,irc_quit *
----

[NOTE]
For help: `/help filter`, `+/help irc.look.smart_filter+` and see
link:weechat_user.en.html#irc_smart_filter_join_part_quit[User's guide / Smart filter for join/part/quit messages].

[[filter_irc_join_channel_messages]]
=== How can I filter some messages displayed when I join an IRC channel?

With WeeChat ≥ 0.4.1, you can choose which messages are displayed when
joining a channel with the option _irc.look.display_join_message_ (see
`+/help irc.look.display_join_message+` for more info).

To hide messages (but keep them in buffer), you can filter them using the tag
(for example _irc_329_ for channel creation date). See `/help filter` for help
with filters.

[[filter_voice_messages]]
=== How can I filter voice messages (eg on Bitlbee server)?

It's not easy to filter voice messages, because voice mode can be set with other
modes in same IRC message.

If you want to do that, it's probably because Bitlbee is using voice to show
away users, and you are flooded with voice messages. Therefore, you can change
that and let WeeChat use a special color for away nicks in nicklist.

For Bitlbee ≥ 3, issue this on control channel _&bitlbee_:

----
channel set show_users online,away
----

For older version of Bitlbee, issue this on control channel _&bitlbee_:

----
set away_devoice false
----

For checking away nicks in WeeChat, see question about
<<color_away_nicks,away nicks>>.

If you really want to filter voice messages, you can use this command, but this
is not perfect (will work only if first mode changed is voice):

----
/filter add hidevoices * irc_mode (\+|\-)v
----

[[color_away_nicks]]
=== How can I see away nicks in nicklist?

You have to set option _irc.server_default.away_check_ to a positive value
(minutes between each check of away nicks).

You can set option _irc.server_default.away_check_max_nicks_ to limit away check
on small channels only.

For example, check every 5 minutes for away nicks, for channels with max 25
nicks:

----
/set irc.server_default.away_check 5
/set irc.server_default.away_check_max_nicks 25
----

[NOTE]
For WeeChat ≤ 0.3.3, options are _irc.network.away_check_ and
_irc.network.away_check_max_nicks_.

[[highlight_notification]]
=== How can I be warned when someone highlights me on a channel?

With WeeChat ≥ 1.0, there is a default trigger "beep" which sends a _BEL_ to
the terminal on a highlight or private message. Thus you can configure your
terminal (or multiplexer like screen/tmux) to run a command or play a sound
when a _BEL_ occurs.

Or you can add a command in "beep" trigger:

----
/set trigger.trigger.beep.command "/print -beep;/exec -bg /path/to/command arguments"
----

With an older WeeChat, you can use a script like _beep.pl_ or _launcher.pl_.

For _launcher.pl_, you have to setup a command:

----
/set plugins.var.perl.launcher.signal.weechat_highlight "/path/to/command arguments"
----

Other scripts on this subject:

----
/script search notify
----

[[disable_highlights_for_specific_nicks]]
=== How can I disable highlights for specific nicks?

With WeeChat ≥ 0.3.4 you can use the
link:weechat_user.en.html#max_hotlist_level_nicks[hotlist_max_level_nicks_add]
buffer property to set the max hotlist level for some nicks, per buffer,
or per group of buffers (like IRC servers).

To only disable highlights, you'd have to set it to 2:

----
/buffer set hotlist_max_level_nicks_add joe:2,mike:2
----

This buffer property isn't stored in the configuration though.
To automatically reapply these buffer properties, you would need the
_buffer_autoset.py_ script:

----
/script install buffer_autoset.py
----

For example, to permanently disable highlights from "mike" on #weechat
on the IRC server libera:

----
/buffer_autoset add irc.libera.#weechat hotlist_max_level_nicks_add mike:2
----

To apply it to the entire libera server instead:

----
/buffer_autoset add irc.libera hotlist_max_level_nicks_add mike:2
----

For more examples, see `+/help buffer_autoset+`.

[[irc_target_buffer]]
=== How can I change target buffer for commands on merged buffers (like buffer with servers)?

The default key is kbd:[Ctrl+x] (command is: `+/input switch_active_buffer+`).

[[plugins_scripts]]
== Plugins / scripts

[[openbsd_plugins]]
=== I'm using OpenBSD and WeeChat does not load any plugins, what's wrong?

Under OpenBSD, plugin filenames end with ".so.0.0" (".so" for Linux).

You must set that up:

----
/set weechat.plugin.extension ".so.0.0"
/plugin autoload
----

[[install_scripts]]
=== How can I install scripts? Are scripts compatible with other IRC clients?

With WeeChat ≥ 0.3.9 you can use the command `/script` to install and manage scripts
(see `/help script` for help). For older versions there is weeget.py and script.pl.

Scripts are not compatible with other IRC clients.

[[scripts_update]]
=== The command "/script update" can not read scripts, how to fix that?

First check questions about SSL connection in this FAQ.

If still not working, try to manually delete the scripts file (in your shell):

----
$ rm ~/.cache/weechat/script/plugins.xml.gz
----

[NOTE]
With WeeChat ≤ 3.1, the path should be: _~/.weechat/script/plugins.xml.gz_.

And update scripts again in WeeChat:

----
/script update
----

If you still have an error, then you must disable the automatic update of file
in WeeChat and download the file manually outside WeeChat (that means you'll
have to update manually the file yourself to get updates):

* in WeeChat:

----
/set script.scripts.cache_expire -1
----

* in your shell, with curl installed:

----
$ cd ~/.cache/weechat/script
$ curl -O https://weechat.org/files/plugins.xml.gz
----

[[spell_dictionaries]]
=== I installed aspell dictionaries on my system, how can I use them without restarting WeeChat?

You have to reload the spell plugin:

----
/plugin reload spell
----

[NOTE]
With WeeChat ≤ 2.4, the "spell" plugin was named "aspell", so the command is:
`/plugin reload aspell`.

[[settings]]
== Settings

[[editing_config_files]]
=== Can I edit configuration files (*.conf) by hand?

You can, but this is *NOT* recommended.

Command `/set` in WeeChat is recommended:

* You can complete the name and value of option with kbd:[Tab] key
  (or kbd:[Shift+Tab] for partial completion, useful for the name).
* The value is checked, a message is displayed in case of error.
* The value is used immediately, you don't need to restart anything.

If you still want to edit files by hand, you should be careful:

* If you put an invalid value for an option, WeeChat will display an error
  on load and discard the value (the default value for option will be used).
* If WeeChat is running, you'll have to issue the command `/reload`, and if
  some settings were changed but not saved with `/save`, you will lose them.

[[memory_usage]]
=== How can I tweak WeeChat to consume less memory?

You can try following tips to consume less memory:

* Use the latest stable version (it is supposed to have less memory leaks than
  older versions).
* Do not load some plugins if you don't use them, for example: buflist,
  fifo, logger, perl, python, ruby, lua, tcl, guile, javascript, php, spell,
  xfer (used for DCC). See `/help weechat.plugin.autoload`.
* Load only scripts that you really need.
* Do not load system certificates if SSL is *NOT* used: turn off this option:
  _weechat.network.gnutls_ca_system_.
* Reduce value of option _weechat.history.max_buffer_lines_number_ or set value
  of option _weechat.history.max_buffer_lines_minutes_.
* Reduce value of option _weechat.history.max_commands_.

[[cpu_usage]]
=== How can I tweak WeeChat to use less CPU?

You can follow same tips as for <<memory_usage,memory>>, and these ones:

* Hide "nicklist" bar: `/bar hide nicklist`.
* Remove display of seconds in status bar time:
  `+/set weechat.look.item_time_format "%H:%M"+` (this is the default value).
* Disable real time check of misspelled words in command line (if you enabled it):
  `+/set spell.check.real_time off+`.
* Set the _TZ_ variable (for example: `export TZ="Europe/Paris"`), to prevent
  frequent access to file _/etc/localtime_.

[[security]]
=== I am paranoid about security, which settings could I change to be even more secure?

Disable IRC part and quit messages:

----
/set irc.server_default.msg_part ""
/set irc.server_default.msg_quit ""
----

Disable answers to all CTCP queries:

----
/set irc.ctcp.clientinfo ""
/set irc.ctcp.finger ""
/set irc.ctcp.source ""
/set irc.ctcp.time ""
/set irc.ctcp.userinfo ""
/set irc.ctcp.version ""
/set irc.ctcp.ping ""
----

Unload and disable auto-loading of "xfer" plugin (used for IRC DCC):

----
/plugin unload xfer
/set weechat.plugin.autoload "*,!xfer"
----

Define a passphrase and use secured data wherever you can for sensitive data
like passwords: see `/help secure` and `/help` on options
(if you can use secured data, it is written in the help).
See also link:weechat_user.en.html#secured_data[User's guide / Secured data].

For example:

----
/secure passphrase xxxxxxxxxx
/secure set libera_username username
/secure set libera_password xxxxxxxx
/set irc.server.libera.sasl_username "${sec.data.libera_username}"
/set irc.server.libera.sasl_password "${sec.data.libera_password}"
----

[[sharing_config_files]]
=== I want to share my WeeChat configuration, what files should I share and what should I keep private?

You can share configuration files _*.conf_ except the file _sec.conf_ which
contains your passwords ciphered with your passphrase.

Some other files may contain sensitive info like passwords (if they are not
stored in _sec.conf_ with the `/secure` command).

See the link:weechat_user.en.html#files_and_directories[User's guide / Files and directories]
for more information about configuration files.

[[development]]
== Development

[[bug_task_patch]]
=== How should I report bugs, ask for new features or send patches?

See: https://weechat.org/about/support

[[gdb_error_threads]]
=== When I run WeeChat under gdb, there is an error about threads, what can I do?

When you run WeeChat under gdb, you may have this error:

----
$ gdb /path/to/weechat
(gdb) run
[Thread debugging using libthread_db enabled]
Cannot find new threads: generic error
----

To fix that, you can run gdb with this command (replace path to libpthread and
WeeChat with paths on your system):

----
$ LD_PRELOAD=/lib/libpthread.so.0 gdb /path/to/weechat
(gdb) run
----

[[supported_os]]
=== What is the list of supported platforms for WeeChat? Will it be ported to other operating systems?

WeeChat runs fine on most Linux/BSD distributions, GNU/Hurd, Mac OS and Windows
(Cygwin and Windows Subsystem for Linux).

We do our best to run on as many platforms as possible. Help is welcome for
some OS' we don't have, to test WeeChat.

[[help_developers]]
=== I want to help WeeChat developers. What can I do?

There are many tasks to do (testing, code, documentation, etc.)

Please contact us via IRC or mail, look at support page:
https://weechat.org/about/support

[[donate]]
=== Can I give money or other things to WeeChat developers?

You can give us money to help development.
Details on https://weechat.org/donate
