<?php

/** @generate-legacy-arginfo */

// TODO Match these function stubs to zend_parse_parameters, then run
//      `cd src/plugins/php && ~/php-src/build/gen_stub.php` to regenerate
//      weechat-php_*arginfo.h

function weechat_register(): mixed {}
function weechat_plugin_get_name(): mixed {}
function weechat_charset_set(): mixed {}
function weechat_iconv_to_internal(): mixed {}
function weechat_iconv_from_internal(): mixed {}
function weechat_gettext(): mixed {}
function weechat_ngettext(): mixed {}
function weechat_strlen_screen(): mixed {}
function weechat_string_match(): mixed {}
function weechat_string_match_list(): mixed {}
function weechat_string_has_highlight(): mixed {}
function weechat_string_has_highlight_regex(): mixed {}
function weechat_string_mask_to_regex(): mixed {}
function weechat_string_format_size(): mixed {}
function weechat_string_color_code_size(): mixed {}
function weechat_string_remove_color(): mixed {}
function weechat_string_is_command_char(): mixed {}
function weechat_string_input_for_buffer(): mixed {}
function weechat_string_eval_expression(): mixed {}
function weechat_string_eval_path_home(): mixed {}
function weechat_mkdir_home(): mixed {}
function weechat_mkdir(): mixed {}
function weechat_mkdir_parents(): mixed {}
function weechat_list_new(): mixed {}
function weechat_list_add(): mixed {}
function weechat_list_search(): mixed {}
function weechat_list_search_pos(): mixed {}
function weechat_list_casesearch(): mixed {}
function weechat_list_casesearch_pos(): mixed {}
function weechat_list_get(): mixed {}
function weechat_list_set(): mixed {}
function weechat_list_next(): mixed {}
function weechat_list_prev(): mixed {}
function weechat_list_string(): mixed {}
function weechat_list_size(): mixed {}
function weechat_list_remove(): mixed {}
function weechat_list_remove_all(): mixed {}
function weechat_list_free(): mixed {}
function weechat_config_new(): mixed {}
function weechat_config_new_section(): mixed {}
function weechat_config_search_section(): mixed {}
function weechat_config_new_option(): mixed {}
function weechat_config_search_option(): mixed {}
function weechat_config_string_to_boolean(): mixed {}
function weechat_config_option_reset(): mixed {}
function weechat_config_option_set(): mixed {}
function weechat_config_option_set_null(): mixed {}
function weechat_config_option_unset(): mixed {}
function weechat_config_option_rename(): mixed {}
function weechat_config_option_is_null(): mixed {}
function weechat_config_option_default_is_null(): mixed {}
function weechat_config_boolean(): mixed {}
function weechat_config_boolean_default(): mixed {}
function weechat_config_integer(): mixed {}
function weechat_config_integer_default(): mixed {}
function weechat_config_string(): mixed {}
function weechat_config_string_default(): mixed {}
function weechat_config_color(): mixed {}
function weechat_config_color_default(): mixed {}
function weechat_config_write_option(): mixed {}
function weechat_config_write_line(): mixed {}
function weechat_config_write(): mixed {}
function weechat_config_read(): mixed {}
function weechat_config_reload(): mixed {}
function weechat_config_option_free(): mixed {}
function weechat_config_section_free_options(): mixed {}
function weechat_config_section_free(): mixed {}
function weechat_config_free(): mixed {}
function weechat_config_get(): mixed {}
function weechat_config_get_plugin(): mixed {}
function weechat_config_is_set_plugin(): mixed {}
function weechat_config_set_plugin(): mixed {}
function weechat_config_set_desc_plugin(): mixed {}
function weechat_config_unset_plugin(): mixed {}
function weechat_key_bind(): mixed {}
function weechat_key_unbind(): mixed {}
function weechat_prefix(): mixed {}
function weechat_color(): mixed {}
function weechat_print(): mixed {}
function weechat_print_date_tags(): mixed {}
function weechat_print_y(): mixed {}
function weechat_print_y_date_tags(): mixed {}
function weechat_log_print(): mixed {}
function weechat_hook_command(): mixed {}
function weechat_hook_completion(): mixed {}
function weechat_hook_completion_get_string(): mixed {}
function weechat_hook_completion_list_add(): mixed {}
function weechat_hook_command_run(): mixed {}
function weechat_hook_timer(): mixed {}
function weechat_hook_fd(): mixed {}
function weechat_hook_process(): mixed {}
function weechat_hook_process_hashtable(): mixed {}
function weechat_hook_connect(): mixed {}
function weechat_hook_line(): mixed {}
function weechat_hook_print(): mixed {}
function weechat_hook_signal(): mixed {}
function weechat_hook_signal_send(): mixed {}
function weechat_hook_hsignal(): mixed {}
function weechat_hook_hsignal_send(): mixed {}
function weechat_hook_config(): mixed {}
function weechat_hook_modifier(): mixed {}
function weechat_hook_modifier_exec(): mixed {}
function weechat_hook_info(): mixed {}
function weechat_hook_info_hashtable(): mixed {}
function weechat_hook_infolist(): mixed {}
function weechat_hook_focus(): mixed {}
function weechat_hook_set(): mixed {}
function weechat_unhook(): mixed {}
function weechat_unhook_all(): mixed {}
function weechat_buffer_new(): mixed {}
function weechat_buffer_new_props(): mixed {}
function weechat_buffer_search(): mixed {}
function weechat_buffer_search_main(): mixed {}
function weechat_current_buffer(): mixed {}
function weechat_buffer_clear(): mixed {}
function weechat_buffer_close(): mixed {}
function weechat_buffer_merge(): mixed {}
function weechat_buffer_unmerge(): mixed {}
function weechat_buffer_get_integer(): mixed {}
function weechat_buffer_get_string(): mixed {}
function weechat_buffer_get_pointer(): mixed {}
function weechat_buffer_set(): mixed {}
function weechat_buffer_string_replace_local_var(): mixed {}
function weechat_buffer_match_list(): mixed {}
function weechat_current_window(): mixed {}
function weechat_window_search_with_buffer(): mixed {}
function weechat_window_get_integer(): mixed {}
function weechat_window_get_string(): mixed {}
function weechat_window_get_pointer(): mixed {}
function weechat_window_set_title(): mixed {}
function weechat_nicklist_add_group(): mixed {}
function weechat_nicklist_search_group(): mixed {}
function weechat_nicklist_add_nick(): mixed {}
function weechat_nicklist_search_nick(): mixed {}
function weechat_nicklist_remove_group(): mixed {}
function weechat_nicklist_remove_nick(): mixed {}
function weechat_nicklist_remove_all(): mixed {}
function weechat_nicklist_group_get_integer(): mixed {}
function weechat_nicklist_group_get_string(): mixed {}
function weechat_nicklist_group_get_pointer(): mixed {}
function weechat_nicklist_group_set(): mixed {}
function weechat_nicklist_nick_get_integer(): mixed {}
function weechat_nicklist_nick_get_string(): mixed {}
function weechat_nicklist_nick_get_pointer(): mixed {}
function weechat_nicklist_nick_set(): mixed {}
function weechat_bar_item_search(): mixed {}
function weechat_bar_item_new(): mixed {}
function weechat_bar_item_update(): mixed {}
function weechat_bar_item_remove(): mixed {}
function weechat_bar_search(): mixed {}
function weechat_bar_new(): mixed {}
function weechat_bar_set(): mixed {}
function weechat_bar_update(): mixed {}
function weechat_bar_remove(): mixed {}
function weechat_command(): mixed {}
function weechat_command_options(): mixed {}
function weechat_completion_new(): mixed {}
function weechat_completion_search(): mixed {}
function weechat_completion_get_string(): mixed {}
function weechat_completion_list_add(): mixed {}
function weechat_completion_free(): mixed {}
function weechat_info_get(): mixed {}
function weechat_info_get_hashtable(): mixed {}
function weechat_infolist_new(): mixed {}
function weechat_infolist_new_item(): mixed {}
function weechat_infolist_new_var_integer(): mixed {}
function weechat_infolist_new_var_string(): mixed {}
function weechat_infolist_new_var_pointer(): mixed {}
function weechat_infolist_new_var_time(): mixed {}
function weechat_infolist_search_var(): mixed {}
function weechat_infolist_get(): mixed {}
function weechat_infolist_next(): mixed {}
function weechat_infolist_prev(): mixed {}
function weechat_infolist_reset_item_cursor(): mixed {}
function weechat_infolist_fields(): mixed {}
function weechat_infolist_integer(): mixed {}
function weechat_infolist_string(): mixed {}
function weechat_infolist_pointer(): mixed {}
function weechat_infolist_time(): mixed {}
function weechat_infolist_free(): mixed {}
function weechat_hdata_get(): mixed {}
function weechat_hdata_get_var_offset(): mixed {}
function weechat_hdata_get_var_type_string(): mixed {}
function weechat_hdata_get_var_array_size(): mixed {}
function weechat_hdata_get_var_array_size_string(): mixed {}
function weechat_hdata_get_var_hdata(): mixed {}
function weechat_hdata_get_list(): mixed {}
function weechat_hdata_check_pointer(): mixed {}
function weechat_hdata_move(): mixed {}
function weechat_hdata_search(): mixed {}
function weechat_hdata_char(): mixed {}
function weechat_hdata_integer(): mixed {}
function weechat_hdata_long(): mixed {}
function weechat_hdata_string(): mixed {}
function weechat_hdata_pointer(): mixed {}
function weechat_hdata_time(): mixed {}
function weechat_hdata_hashtable(): mixed {}
function weechat_hdata_compare(): mixed {}
function weechat_hdata_update(): mixed {}
function weechat_hdata_get_string(): mixed {}
function weechat_upgrade_new(): mixed {}
function weechat_upgrade_write_object(): mixed {}
function weechat_upgrade_read(): mixed {}
function weechat_upgrade_close(): mixed {}
function forget_class(): mixed {}
function forget_function(): mixed {}
