= weechat(1)
:doctype: manpage
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: en
:man manual: WeeChat Manual
:man source: WeeChat {revnumber}

== NAME

weechat - the extensible chat client

== SYNOPSIS

[verse]
*weechat* [-a|--no-connect] [-d|--dir <path>] [-p|--no-plugin] [-r|--run-command <command>] [-s|--no-script] [--upgrade] [plugin:option...]
*weechat* [-c|--colors]
*weechat* [-h|--help]
*weechat* [-l|--license]
*weechat* [-v|--version]

== DESCRIPTION

WeeChat (Wee Enhanced Environment for Chat) is a free chat client, fast and
light, designed for many operating systems.
It is highly customizable and extensible with scripts.

== OPTIONS

include::cmdline_options.en.adoc[]

== PLUGIN OPTIONS

For complete doc on plugin options, please look at plugins documentation in
https://weechat.org/doc[WeeChat user's guide].

With irc plugin, you can connect to temporary server with an URL like:

    irc[6][s]://[[nickname][:password]@]server[:port][/#channel1[,#channel2...]]

To join WeeChat IRC channel support with nick "mynick":

    irc://mynick@chat.freenode.net/#weechat

IPv6 address can be enclosed in brackets to add a port after address, for
example:

    irc://mynick@[2001:db8:0:85a3::ac1f:8001]:6668/#test

== FILES

$HOME/.weechat/weechat.conf::
    main WeeChat configuration file

$HOME/.weechat/plugins.conf::
    plugins configuration file

$HOME/.weechat/sec.conf::
    configuration file with secured data

$HOME/.weechat/alias.conf::
    configuration file for _alias_ plugin

$HOME/.weechat/aspell.conf::
    configuration file for _aspell_ plugin

$HOME/.weechat/buflist.conf::
    configuration file for _buflist_ plugin

$HOME/.weechat/charset.conf::
    configuration file for _charset_ plugin

$HOME/.weechat/exec.conf::
    configuration file for _exec_ plugin

$HOME/.weechat/fifo.conf::
    configuration file for _fifo_ plugin

$HOME/.weechat/fset.conf::
    configuration file for _fset_ plugin

$HOME/.weechat/irc.conf::
    configuration file for _irc_ plugin

$HOME/.weechat/logger.conf::
    configuration file for _logger_ plugin

$HOME/.weechat/relay.conf::
    configuration file for _relay_ plugin

$HOME/.weechat/script.conf::
    configuration file for _script_ plugin

$HOME/.weechat/trigger.conf::
    configuration file for _trigger_ plugin

$HOME/.weechat/xfer.conf::
    configuration file for _xfer_ plugin

$HOME/.weechat/weechat.log::
    WeeChat log file

== AUTHORS

This manpage was written by {author}.

== COPYRIGHT

WeeChat is written by Sébastien Helleu and contributors (complete list is in
the AUTHORS.adoc file).

Copyright (C) 2003-2017 {author}

WeeChat is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

Please read the COPYING file for more information.

Web: https://weechat.org/

== SUPPORT / REPORTING BUGS

For help or a bug report: https://weechat.org/dev/support
