SET(WEECHAT_SOURCES
src/protocols/irc/irc-mode.c
src/protocols/irc/irc-nick.c
src/protocols/irc/irc-server.c
src/protocols/irc/irc-channel.c
src/protocols/irc/irc-commands.c
src/protocols/irc/irc-display.c
src/protocols/irc/irc-send.c
src/protocols/irc/irc-recv.c
src/protocols/irc/irc-dcc.c
src/protocols/irc/irc-ignore.c
src/protocols/irc/irc.h
src/plugins/plugins.c
src/plugins/plugins.h
src/plugins/plugins-config.c
src/plugins/plugins-config.h
src/plugins/plugins-interface.c
src/plugins/weechat-plugin.h
src/gui/curses/gui-curses-chat.c
src/gui/curses/gui-curses-color.c
src/gui/curses/gui-curses-infobar.c
src/gui/curses/gui-curses-input.c
src/gui/curses/gui-curses-keyboard.c
src/gui/curses/gui-curses-main.c
src/gui/curses/gui-curses-nicklist.c
src/gui/curses/gui-curses-panel.c
src/gui/curses/gui-curses-status.c
src/gui/curses/gui-curses-window.c
src/gui/curses/gui-curses.h
src/gui/gtk/gui-gtk-chat.c
src/gui/gtk/gui-gtk-color.c
src/gui/gtk/gui-gtk-infobar.c
src/gui/gtk/gui-gtk-input.c
src/gui/gtk/gui-gtk-keyboard.c
src/gui/gtk/gui-gtk-main.c
src/gui/gtk/gui-gtk-nicklist.c
src/gui/gtk/gui-gtk-panel.c
src/gui/gtk/gui-gtk-status.c
src/gui/gtk/gui-gtk-window.c
src/gui/gtk/gui-gtk.h
src/gui/gui-action.c
src/gui/gui-buffer.c
src/gui/gui-common.c
src/gui/gui-keyboard.c
src/gui/gui-log.c
src/gui/gui-panel.c
src/gui/gui-window.c
src/gui/gui.h
src/gui/gui-buffer.h
src/gui/gui-color.h
src/gui/gui-keyboard.h
src/gui/gui-panel.h
src/gui/gui-window.h
src/common/alias.c
src/common/alias.h
src/common/backtrace.c
src/common/backtrace.h
src/common/command.c
src/common/command.h
src/common/completion.c
src/common/completion.h
src/common/fifo.c
src/common/fifo.h
src/common/history.c
src/common/history.h
src/common/hotlist.c
src/common/hotlist.h
src/common/log.c
src/common/log.h
src/common/session.c
src/common/session.h
src/common/utf8.c
src/common/utf8.h
src/common/util.c
src/common/util.h
src/common/weechat.c
src/common/weechat.h
src/common/weeconfig.c
src/common/weeconfig.h
src/common/weelist.c
src/common/weelist.h
)
