= Водич за тестирање програма WeeChat
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: sr
:toc: left
:toc-title: Садржај
:sectnums:
:docinfo1:


[[purpose]]
== Намена

Многи захвални корисници су нас питали како могу да помогну развој програма WeeChat. Најлакши (у исто време и најкомпликованији) начин помоћи у развоју програма WeeChat је тестирање!

Тестирање је веома важан део развоја софтвера и не би требало да се занемари. Када се имплементирају неке могућности, требало би и да се тестирају, али за неке могућности постоји превише случајева коришћења или су ти случајеви компликовани, па програмери не могу да испробају баш сваки случај.

На пример: озлоглашени charset додатак је уведен у WeeChat верзије 0.2.2: нико од нас (програмери, људи који су дали допринос програму, и тестери) није користио канале са националним карактерима у својим именима, па када је објављена верзија 0.2.2, руски коринисници су нас засули примедбама. Да имамо више тестера, овако нешто се не би опет поновило у будућности.

Тестирање стабилне верзије програма WeeChat нема смисла јер су програмери стално заузети имплементирањем нових ствари (и исправљањем старих багова).


[[prepare_system]]
== Припремите свој систем

Пуно би нам помогло ако укључите Линукс _core_ фајлове: ако се програм WeeChat сруши, Линукс ће креирати фајл под именом _core_. Овај фајл садржи врло корисне дибаг информације, тако да прецизно можемо знати где је у програму WeeChat настао проблем.

Ако користите _bash_ командно окружење, додајте следећу линију у свој _~/.bashrc_:

----
ulimit -c unlimited
----


[[download]]
== Преузмите развојну верзију

Свеж кôд (са најновијим баговима и могућностима) је чува у GIT репозиторијуму.

Можете одлучити да га сами изградите (препоручени начин):

* GIT верзија може да се изгради и инсталира паралелно са стабилном верзијом.
* Није вам потребан root приступ, и не морате да жртвујете стабилну верзију програма WeeChat.

[[get_sources]]
=== Набавите и изградите изворне фајлове

Најпре креирајте директоријум, на пример _weechat-git_:

----
$ mkdir ~/weechat-git
$ cd ~/weechat-git
----

Ако имате инсталиран програм git, можете једноставно да клонирате git репозиторијум (препоручени начин):

----
$ git clone https://github.com/weechat/weechat.git
$ cd weechat
----

[NOTE]
Касније можете да извршите `git pull` у овом директоријуму, чиме преузимате делте са најновијим ажурирањима.

У супротном можете да преузмете и распакујете _devel_ пакет:

----
$ wget https://weechat.org/files/src/weechat-devel.tar.bz2
$ tar xvjf weechat-devel.tar.bz2
$ cd weechat-devel
----

CMake се препоручује за изградњу изворних фајлова:

----
$ mkdir build
$ cd build
$ cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/weechat-git -DWEECHAT_HOME=~/.weechat-dev -DCMAKE_BUILD_TYPE=Debug
$ make
$ make install
----

Ако немате CMake, ипак је могуће да употребите autotools:

----
$ ./autogen.sh
$ ./configure --prefix=$HOME/weechat-git WEECHAT_HOME=~/.weechat-dev
$ make
$ make install
----

[[install_binary_package]]
=== Инсталација бинарног пакета

У зависности од ваше Линукс дистрибуције:

* Debian: https://weechat.org/download/debian
* Gentoo: https://weechat.org/download
* ArchLinux: PKGBUILD са https://aur.archlinux.org/
* остале: не знамо! Хехе.


[[run]]
== Покретање програма WeeChat

Команда је:

----
$ ~/weechat-git/bin/weechat
----

Ако сте још увек будни, требало би да угледате познати интерфејс и да се хвалите тиме што поседујете најновију могућу верзију програма WeeChat. ;)

Ако сада искусите чудно понашање (можда постоје проблеми или крах или може да прокључа ваше пиво) не оклевајте да се придружите каналу _#weechat_ на _irc.libera.chat_ и да нам испричате о проблему.

Ако се програм не руши - реците нам и то, потребно нам је ваше извештавање!
