= WeeChat водич за брзи почетак
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: sr
:toc-title: Садржај

Превод:

* Иван Пешић (<ivan.pesic@gmail.com>), 2021.

[[start]]
== Покретање програма WeeChat

Препоручени (али не и обавезни) X терминал емулатор за покретање програма WeeChat је rxvt-unicode. Он поседује добру UTF-8 подршку и лепо ради са подразумеваним тастерским пречицама програма WeeChat.

Покретање из вашег командног окружења:

----
$ weechat
----

[[help]]
== Помоћ током извршавања

Програм WeeChat поседује помоћ за све команде, једноставно откуцајте:

----
/help
----

Ако желите да добијете помоћ за одређену команду, откуцајте:

----
/help команда
----

Помоћ постоји и за опције:

----
/help конфиг.одељак.опција
----

(где је `конфиг` име конфикурације (`weechat` за језгро, или име додатка), `одељак` је одељак ове конфигурације и `опција` је име опције).

[[options]]
== Постављање опција

Да бисте поставили опције, извршите:

----
/set конфиг.одељак.опција вредност
----

Програм WeeChat тренутно користи нову вредност (након измена конфигурације, *никада* не морате поново да покренете програм WeeChat).

Када програм WeeChat завршава извршавање, сва подешавања се чувају (или командом `/save` којом форсирате уписивање опција).

[IMPORTANT]
*Не препоручује* се ручно уређивање конфигурационих фајлова јер програм WeeChat може да их упише у било које време (на пример када извршава `/quit`) и након сваке измене морате извршити команду `/reload` (уз ризик да изгубите остале измене које још увек нисте сачували са `/save`). +
Можете употребити команду `/set` која проверава вредност и тренутно примењује измене.

Додатак _fset_ вам омогућава да једноставно прегледате опције и да их мењате.

На пример, да бисте приказали WeeChat опције:

----
/fset weechat.*
----

IRC опције:

----
/fset irc.*
----

Команда `/fset` поседује довршавање дела имена опције, тако да ако на пример, откуцате `/fset hot` и притиснете kbd:[Tab] то се довршава као `/fset hotlist`. Ако притиснете kbd:[Enter], приказују се опције везане за врућу листу.

За више информација у вези команде `/fset` и тастера, погледајте `/help fset`.

[[core_vs_plugins]]
== Језгро и додаци

WeeChat „језгро” се користи само за приказ података на екран и за интеракцију са корисником; то значи да је weechat језгро без додатака потпуно бескорисно (верни корисници: IRC је био део језгра у верзијама ≤ 0.2.6).

Сви мрежни протоколи као што је IRC су имплементирани у одвојеним додацима.

Да бисте видели листу учитаних додатака, употребите команду `/plugin`, у листи би требало да видите „irc” и остале додатке.

[[add_irc_server]]
== Додавање IRC сервера

IRC сервер можете додати командом `/server`, на пример:

----
/server add libera irc.libera.chat/6697 -tls
----

`freenode` је у овој команди интерно име сервера које користи програм WeeChat: касније ћете моћи да се повежете са њим помоћу `/connect libera`, а опције сервера су _irc.server.libera.xxx_.

Као и обично, ако се збуните доступна вам је помоћ:

----
/help server
----

[[irc_server_options]]
== Постављање прилагођених опција IRC сервера

Програм WeeChat користи подразумеване вредности за све сервере („вредности у крајњем случају”), онда када не наведете одређену вредност за опцију сервера. Ове подразумеване опције су „irc.server_default.*”.

За сваку опцију сервера, програм WeeChat користи њену вредност ако је дефинисана (није „null”). У супротном, програм WeeChat користи подразумевану вредност („irc.server_default.xxx”).

Постоје на пример, подразумевани надимци (засновани на вашем un*x корисничком имену), па можете да их преиначите за libera сервер следећом командом:

----
/set irc.server.libera.nicks "mynick,mynick2,mynick3,mynick4,mynick5"
----

Ако желите да поставите корисничко и реално име:

----
/set irc.server.libera.username "Моје корисничко име"
/set irc.server.libera.realname "Моје реално име"
----

Ако желите да укључите ауто повезивање са сервером током покретања програма:

----
/set irc.server.libera.autoconnect on
----

Ако сервер подржава SASL, можете да га користите за аутентификацију (бићете идентификовани пре него што приступите каналима):

----
/set irc.server.libera.sasl_username "mynick"
/set irc.server.libera.sasl_password "xxxxxxx"
----

Ако након повезивања са сервером желите да покренете команду, на пример за аутентификацију са nickserv (само ако не користите SASL за аутентификацију):

----
/set irc.server.libera.command "/msg nickserv identify xxxxxxx"
----

[NOTE]
Више команди у опцији _command_ можете да раздвојите са `;` (тачка зарез).

Ако желите да заштитите своју лозинку у конфигурационим фајловима, можете да користите обезбеђене податке.

Најпре поставите тајну реченицу:

----
/secure passphrase ово је моја тајна реченица
----

Затим додајте осигуране податке својом libera лозинком:

----
/secure set libera_password xxxxxxx
----

Затим у IRC опцијама поменутим изнад, уместо своје лозинке можете да користите `+${sec.data.libera_password}+`, на пример:

----
/set irc.server.libera.sasl_password "${sec.data.libera_password}"
----

Ако желите да се неким каналима аутоматски приступи када се повежете на сервер:

----
/set irc.server.libera.autojoin "#канал1,#канал2"
----

`/autojoin` команда вам омогућава да једноставно конфигуришете _autojoin_ опцију
(погледајте `/help autojoin`).

WeeChat такође можете подесити да аутоматски ажурира _autojoin_ опцију када
приступите каналу, или када га напустите:

----
/set irc.server_default.autojoin_dynamic on
----

Ако желите да уклоните вредност опције сервера и да уместо ње користите подразумевану вредност, на пример, да се користе подразумевани надимци (irc.server_default.nicks):

----
/unset irc.server.libera.nicks
----

Остале опције: можете да поставите остале опције командом („xxx” је име опције):

----
/set irc.server.libera.xxx вредност
----

[TIP]
Име и вредност опција можете да довршите тастером kbd:[Tab] и kbd:[Shift+Tab] за делимично довршавање (корисно је за дугачке речи као што је име опције).

[[connect_to_irc_server]]
== Повезивање са IRC сервером

----
/connect libera
----

Овом командом, програм WeeChat се повезује са libera сервером и аутоматски приступа каналима конфигурисаним „autojoin” опцијом сервера.

[NOTE]
Ова команда може да се искористи за креирање и повезивање са новим сервером без употребе команде `/server` (погледајте `/help connect`).

Подразумевано, бафери сервера се спајају са WeeChat _језгро_ бафером. Ако желите да се пребацујете између _језгро_ бафера и серверских бафера, можете да употребите kbd:[Ctrl+x].

Могуће је да се искључи аутоматско спајање серверских бафера тако да имате независне серверске бафере:

----
/set irc.look.server_buffer independent
----

[[join_part_irc_channels]]
== Join/part (приступ/напуштање) IRC канала

Приступ каналу:

----
/join #канал
----

Напуштање канала (уз остављање отвореног бафера):

----
/part [порука о напуштању]
----

Затварање бафера сервера, канала или приватног бафера (`/close` је алијас за `/buffer close`):

----
/close
----

[WARNING]
Затварање бафера сервера ће затворити и све бафере канала и приватне бафере.

Прекид везе са сервером, у баферу сервера:

----
/disconnect
----


[[irc_private_messages]]
== IRC приватне поруке

Отварање бафера и слање поруке другом кориснику (надимак _foo_):

----
/query foo ово је порука
----

Затварање приватног бафера:

----
/close
----

[[buffer_window]]
== Управљање баферима/прозорима

Бафер је компонента повезана са додатком која има број, категорију и име. Бафер садржи податке који се приказују на екрану.

Прозор је поглед на бафер. Подразумевано постоји само један прозор који приказује један бафер. Ако поделите екран, видећете више прозора са више бафера у исто време.

Команде којима се управља баферима и прозорима:

----
/buffer
/window
----

На пример, ако желите да свој екран поделите по вертикали на мали прозор (1/3 ширине), и велики прозор (2/3), употребите команду:

----
/window splitv 33
----

Ако желите да уклоните поделу:

----
/window merge
----

[[key_bindings]]
== Тастерске пречице

Програм WeeChat подразумевано користи многе тастере. Сви они се налазе у документацији, али би требало да знате барем оне најважније:

- kbd:[Alt+←] / kbd:[Alt+→] или kbd:[F5] / kbd:[F6]: прелаз на претходни/наредни бафер
- kbd:[F1] / kbd:[F2]: скроловање линије са листом бафера („buflist”)
- kbd:[F7] / kbd:[F8]: прелаз на претходни/наредни прозор (када је екран издељен)
- kbd:[F9] / kbd:[F10]: скроловање насловне траке
- kbd:[F11] / kbd:[F12]: скроловање листе надимака
- kbd:[Tab]: довршавање текста у траци за унос, као у вашем командном окружењу
- kbd:[PgUp] / kbd:[PgDn]: скроловање текста у текућем баферу
- kbd:[Alt+a]: скок на бафер са активношћу (у врућој листи)

У зависности од ваше тастатуре и/или ваших потреба, можете поново да вежете команду помоћу `/key` команде. Користан тастер је kbd:[Alt+k] којим можете да пронађете кодове тастера.

На пример, ако желите да вежете kbd:[Alt+!] са командом `/buffer close`:

----
/key bind (притисните alt-k) (притисните alt-!) /buffer close
----

Добићете следећу командну линију:

----
/key bind meta-! /buffer close
----

Ако желите да уклоните тастер:

----
/key unbind meta-!
----

[[plugins_scripts]]
== Додаци/скрипте

На неким дистрибуцијама као што је Debian, додаци су доступни кроз посебан пакет (као што је weechat-plugins). Додаци се аутоматски учитавају када се пронађу (молимо вас да погледате документацију програма WeeChat у вези учитавања/уклањања из меморије додатака или скрипти).

За програм WeeChat су доступне многе спољне скрипте (које су приложили корисници), можете да их преузмете и инсталирате из репозиторијума командом `/script`, на пример:

----
/script install go.py
----

За више детаља погледајте `/help script`.

Листа скрипти је доступна у WeeChat са `/script` или на
https://weechat.org/scripts/[овој страници ^↗^^].

[[more_doc]]
== Још документације

Сада можете почети да користите WeeChat и ако имате било каквих питања
прочитате
https://weechat.org/doc/[ЧПП/документацију ^↗^^].

Уживајте у коришћењу програма WeeChat!
