# SPDX-FileCopyrightText: 2026 Sébastien Helleu <flashcode@flashtux.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[check]
select = [
    "default",
    "compilation",
    "spelling",
]
path_words = "."
spelling_langs = [
    "en_US",
    "fr",
]
