# SPDX-FileCopyrightText: 2026 Sébastien Helleu <flashcode@flashtux.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[check]
select = [
    "checks",
]
ignore = [
    "acronyms",
    "brackets",
    "double-quotes",
    "double-words",
    "functions",
    "header",
    "html-tags",
    "paths",
    "punc-space-str",
    "unchanged",
    "unicode-ctrl",
    "urls",
]
path_words = "."
langs = [
    "en_US",
    "fr",
]
