= Guida al Tester di WeeChat
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: it
:toc: left
:toc-title: Indice
:sectnums:
:docinfo1:


// TRANSLATION MISSING
Translators:

* Marco Paolone <marcopaolone@gmail.com>, 2009-2012


[[purpose]]
== Scopo

Molti utenti riconoscenti chiedono come possono aiutare nello sviluppo
di WeeChat. Il modo più semplice (ed anche più delicato) per aiutare
lo sviluppo di WeeChat è il testing!

Il testing è una parte davvero importante dello sviluppo software e non
può essere sottovalutato. Quando vengono implementate alcune
funzionalità dovrebbero essere testate, ma per alcune di esse esistono
troppi casi di utilizzo o questi casi sono delicati e gli sviluppatori non
possono verificarli uno ad uno.

Per esempio: È stato introdotto un famigerato set di caratteri in WeeChat 0.2.2:
nessuno di noi (sviluppatori, contributori e tester) utilizzava canali con lettere
dell'alfabeto nazionale nei loro nomi e quando è stata rilasciata la 0.2.2 siamo
stati inondati dagli utenti russi. Se avessimo più tester non dovrebbe più
accadere in futuro.

Testare la versione stabile di WeeChat è inutile poiché gli sviluppatori sono
occupati nell'implementazione di nuove funzionalità (e nella correzione di
vecchi bug).


[[prepare_system]]
== Preparazione del sistema

Sarebbe molto di aiuto abilitare i file _core_ di Linux: se WeeChat
dovesse andare in crash, Linux scriverebbe un file chiamato _core_.
Questo file contiene informazioni di debug molto utili, per sapere
esattamente dove sia il problema in WeeChat.

Se si utilizza la shell _bash_, aggiungere la seguente riga al file _~/.bashrc_:

----
ulimit -c unlimited
----


[[download]]
== Download della versione di sviluppo

Il codice più fresco (con gli ultimi bug e le funzionalità più recenti) è
conservato in un deposito GIT.

È possibile compilarlo manualmente (raccomandato):

* La versione GIT può essere compilata ed installata parallelamente alla
* versione stabile, non è necessario l'accesso da root né sacrificare la
  versione stabile di WeeChat.

[[get_sources]]
=== Ottenere e compilare i sorgenti

Per prima cosa creare una directory, per esempio _weechat-git_:

----
$ mkdir ~/weechat-git
$ cd ~/weechat-git
----

Se si ha git installato, si può clonare il deposito git (raccomandato):

----
$ git clone https://github.com/weechat/weechat.git
$ cd weechat
----

[NOTE]
In seguito, si può eseguire `git pull` in questa directory per ricevere gli
ultimi aggiornamenti.

Altrimenti si può scaricare ed estrarre il pacchetto _devel_:

----
$ wget https://weechat.org/files/src/weechat-devel.tar.bz2
$ tar xvjf weechat-devel.tar.bz2
$ cd weechat-devel
----

Per compilare i sorgenti, si raccomanda cmake:

----
$ mkdir build
$ cd build
$ cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/weechat-git -DWEECHAT_HOME=~/.weechat-dev -DCMAKE_BUILD_TYPE=Debug
$ make
$ make install
----

Se cmake non è installato, è ancora possibile usare gli autotools:

----
$ ./autogen.sh
$ ./configure --prefix=$HOME/weechat-git WEECHAT_HOME=~/.weechat-dev
$ make
$ make install
----

[[install_binary_package]]
=== Installazione del pacchetto binario

A seconda della distribuzione Linux:

* Debian: https://weechat.org/download/debian
* Gentoo: https://weechat.org/download
* ArchLinux: PKGBUILD da https://aur.archlinux.org/
* altro: non lo sappiamo! Eheh.


[[run]]
== Eseguire WeeChat

Il comando è:

----
$ ~/weechat-git/bin/weechat
----

Se siete ancora svegli dovreste vedere un'interfaccia familiare e vantarvi del
fatto di avere la versione più nuova possibile di WeeChat. ;)

Se si dovessero verificare strani comportamenti (potrebbe andare in crash
o far bollire la vostra birra) non esitate ad entrare in _#weechat_ su
_chat.freenode.net_ e farcelo sapere.

Se non dovesse andare in crash - ditelo comunque, abbiamo bisogno dei vostri
commenti!
