= Guida Rapida a WeeChat
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: it
:toc:


[[start]]
== Avvio di WeeChat

Un emulatore di terminale raccomandato per X (ma non obbligatorio) è
rxvt-unicode (ha un buon supporto per UTF-8, e nessun problema con
le scorciatoie da tastiera predefinite).

Avviare dalla propria shell:

----
$ weechat
----

[[help_options]]
== Aiuto online / opzioni

WeeChat offre aiuto per tutti i comandi, basta digitare:

----
/help
----

Per ricevere aiuto su un comando specifico, digitare:

----
/help comando
----

Per impostare le opzioni, utilizzare:

----
/set config.sezione.opzione valore
----

(dove `config` è il nome della configurazione (`weechat` per il core,
oppure un nome plugin), `sezione` la sezione di questa configurazione
e `opzione` il nome dell'opzione).

WeeChat utilizza subito il nuovo valore (non c'è *mai* bisogno di riavviare
WeeChat dopo aver cambiato la configurazione).

È possibile utilizzare l'opzione `/set` con un nome parziale e il carattere jolly "*"
all'inizio o alla fine per visualizzare tutte le opzioni contenenti le lettere.
Per esempio:

* visualizza tutte le opzioni (WeeChat e plugin):

----
/set
----

* visualizza le opzioni di WeeChat:

----
/set weechat.*
----

* visualizza le opzioni del plugin IRC:

----
/set irc.*
----

È possibile visualizzare l'aiuto per ogni opzione con `/help`, per esempio:

----
/help weechat.look.highlight
----

Tutte le impostazioni vengono salvato all'uscita di WeeChat (o con il comando
`/save` per forzare il salvataggio di una o più opzioni).

Si possono modificare manualmente i file di configurazione (*.conf) e
ricaricarli con il comando `/reload` se non si vuole usare il comando `/set`.

[[core_vs_plugins]]
== Core vs plugin

Il "core" di WeeChat è utilizzato solo per visualizzare i dati sullo schermo
e interagire con l'utente; ciò vuol dire che il core di weechat senza i
plugin è inutile (utenti più fedeli: IRC faceva parte del core per le
versioni ≤ 0.2.6).

Tutti i protocolli di rete come IRC sono forniti in plugin separati.

Utilizzando il comando `plugin` per elencare i plugin caricati, è possibile
vedere "irc" ed altri plugin nella lista.

[[create_irc_server]]
== Creare un server IRC

// TRANSLATION MISSING
The server 'freenode' is created by default on first startup.

// TRANSLATION MISSING
You can add another IRC server with `/server` command, for example:

----
/server add oftc irc.oftc.net/6667
----

Come al solito, è disponibile l'aiuto se c'è qualche problema:

----
/help server
----

[[irc_server_options]]
== Impostare opzioni personalizzate per il server IRC

WeeChat usa valori predefiniti per tutti i server, se non si specifica un
valore preciso per un'opzione del server. Questi valori predefiniti sono
"irc.server_default.*"

Per ogni opzione del server, WeeChat usa il proprio valore se definito
(non "nullo"). Altrimenti si utilizza il valore predefinito
("irc.server_default.xxx").

Per esempio ci sono dei nick predefiniti (basati sul proprio login un*x), ed
è possibile sovrascriverli per il server freenode con il seguente comando:

----
/set irc.server.freenode.nicks "mynick,mynick2,mynick3,mynick4,mynick5"
----

Per impostare il nome utente ed il nome reale:

----
/set irc.server.freenode.username "Mio nome utente"
/set irc.server.freenode.realname "Mio nome reale"
----

Per impostare la connessione automatica al server all'avvio:

----
/set irc.server.freenode.autoconnect on
----

// TRANSLATION MISSING
To connect with SSL:

----
/set irc.server.freenode.addresses "chat.freenode.net/7000"
/set irc.server.freenode.ssl on
/set irc.server.freenode.ssl_dhkey_size 1024
----

// TRANSLATION MISSING
[NOTE]
Freenode does not support the default dhkey size of 2048, so it has to be set
to 1024.

Se SASL è disponibile sul server, è possibile usarlo per l'autenticazione
(l'autenticazione avviene prima dell'ingresso nei canali):

----
/set irc.server_default.sasl_mechanism dh-blowfish
/set irc.server.freenode.sasl_username "mynick"
/set irc.server.freenode.sasl_password "xxxxxxx"
----

Per eseguire un comando dopo la connessione al server, ad esempio per
autenticarsi con nickserv (solo se non viene usato SASL per l'autenticazione):

----
/set irc.server.freenode.command "/msg nickserv identify xxxxxxx"
----

// TRANSLATION MISSING
[NOTE]
Many commands in option 'command' can be separated by ';' (semi-colon).

Per entrare automaticamente in alcuni canali quando ci si connette
al server:

----
/set irc.server.freenode.autojoin "#canale1,#canale2"
----

Per eliminare il valore di un'opzione del server, e usare invece il valore
predefinito, per esempio per utilizzare i nick predefiniti
(irc.server_default.nicks):

----
/set irc.server.freenode.nicks null
----

Altre opzioni: è possibile impostare altre opzioni con il seguente comando
("xxx" è il nome dell'opzione):

----
/set irc.server.freenode.xxx value
----

[[connect_to_irc_server]]
== Connessione al server IRC e ingresso automatico nei canali

----
/connect freenode
----

[NOTE]
Questo comando può essere usato per creare e connettersi ad un nuovo server
senza utilizzare il comando `/server` (è necessario ripetere che è possibile
visualizzare l'aiuto per questo comando con `/help connect`?).

I buffer dei server vengono uniti al buffer 'core' di WeeChat in modo
predefinito. Per passare tra buffer 'core' e buffer server, si può digitare
key[ctrl-x].

È possibile disabilitare l'unione automatica dei server dei buffer per avere i
buffer dei server indipendenti:

----
/set irc.look.server_buffer independent
----

[[join_part_irc_channels]]
== Entrare/uscire dai canali IRC

Entra in un canale:

----
/join #canale
----

Esce da un canale (mantenendo il buffer aperto):

----
/part [messaggio di uscita]
----

Chiude il buffer del server o del canale (`/close` è un alias per `/buffer close`):

----
/close
----

// TRANSLATION MISSING
[[irc_private_messages]]
== IRC private messages

Open a buffer and send a message to another user (nick 'foo'):

----
/query foo this is a message
----

Close the private buffer:

----
/close
----

[[buffer_window]]
== Gestione buffer/finestra

Un buffer è un componente collegato ad un plugin con un numero,
una categoria e un nome. Un buffer contiene i dati visualizzati sullo
schermo.

Una finestra è la vista di un buffer. Il comportamento predefinito
prevede solo una finestra che visualizza un buffer. Se lo schermo
viene diviso, sarà possibile vedere più finestre con molti buffer allo
stesso tempo.

I comandi per gestire buffer e finestre:

----
/buffer
/window
----

(Qui non si ripeterà che è possibile avere aiuto su questi comandi con /help)

Per esempio, per dividere verticalmente lo schermo in una finestra piccola
(1/3 della larghezza) ed una grande (2/3), utilizzare il comando:

----
/window splitv 33
----

[[key_bindings]]
== Associazione tasti

WeeChat usa molti tasti. Essi sono tutti presenti nella documentazione,
ma si dovrebbero conoscere almeno quelli vitali:

- key[alt-]key[←]/key[→] oppure key[F5]/key[F6]: passa al buffer
  precedente/successivo
- key[F7]/key[F8]: passa alla finestra precedente/successiva (quando lo schermo
  è diviso)
- key[F9]/key[F10]: scorre la barra del titolo
- key[F11]/key[F12]: scorre la lista nick
- key[Tab]: completa il testo nella barra di input, proprio come nella shell
- key[PgUp]/key[PgDn]: scorre testo nel buffer corrente
- key[alt-a]: passa al buffer con attività (nella hotlist)

A seconda della propria tastiera e/o le proprie necessità, è possibile
associare nuovamente qualsiasi tasto ad un comando tramite
`/key`.
Un tasto utile è key[alt-k] per trovare i codici tasti.

Ad esempio, per associare key[alt-y] al comando `/buffer close`:

----
/key bind (digitare alt-k) (digitare alt-y) /buffer close
----

Si otterrà una riga di comando simile a:

----
/key bind meta-y /buffer close
----

Per eliminare il tasto:

----
/key unbind meta-y
----

[[plugins_scripts]]
== Plugin/script

Su alcune distribuzioni come Debian, i plugin sono disponibili tramite un
pacchetto separato (come weechat-plugins).
I plugin vengono caricati automaticamente quando trovati
(per favore consultare la documentazione per caricare/scaricare plugin
o script).

Sono disponibili molti script esterni (dai contributori) per WeeChat:
https://weechat.org/scripts

È possibile gestire gli script in WeeChat con il comando `/script` (consultare
`/help script` per maggiori informazioni).

[[more_doc]]
== Ulteriore documentazione

È ora possibilie usare WeeChat e leggere FAQ/documentazione per ogni altra
domanda:
https://weechat.org/doc

Buon WeeChat!
