= Guida Rapida a WeeChat
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: it
:toc: left
:toc-title: Indice
:sectnums:
:docinfo1:


// TRANSLATION MISSING
Translators:

* Marco Paolone <marcopaolone@gmail.com>, 2009-2013


[[start]]
== Avvio di WeeChat

Un emulatore di terminale raccomandato per X (ma non obbligatorio) è
rxvt-unicode: ha un buon supporto per UTF-8, e nessun problema con
le scorciatoie da tastiera predefinite.

Avviare dalla propria shell:

----
$ weechat
----

[[help]]
== Aiuto online

WeeChat offre aiuto per tutti i comandi, basta digitare:

----
/help
----

Per ricevere aiuto su un comando specifico, digitare:

----
/help comando
----

// TRANSLATION MISSING
Help is available for options as well:

----
/help config.section.option
----

(dove `config` è il nome della configurazione (`weechat` per il core,
oppure un nome plugin), `sezione` la sezione di questa configurazione
e `opzione` il nome dell'opzione).

// TRANSLATION MISSING
[[options]]
== Set options

Per impostare le opzioni, utilizzare:

----
/set config.sezione.opzione valore
----

WeeChat utilizza subito il nuovo valore (non c'è *mai* bisogno di riavviare
WeeChat dopo aver cambiato la configurazione).

Tutte le impostazioni vengono salvato all'uscita di WeeChat (o con il comando
`/save` per forzare il salvataggio di una o più opzioni).

// TRANSLATION MISSING
[IMPORTANT]
It is *not recommended* to edit configuration files by hand because WeeChat
may write them at any time (for example on `/quit`) and after any change
you must run the command `/reload` (with the risk of losing other changes
that were not yet saved with `/save`). +
You can use the command `/set`, which checks the value and applies immediately
the changes.

// TRANSLATION MISSING
The plugin _fset_ allows you to easily browse options and change them.

// TRANSLATION MISSING
For example to display WeeChat options:

----
/fset weechat.*
----

// TRANSLATION MISSING
IRC options:

----
/fset irc.*
----

// TRANSLATION MISSING
The `/fset` command has completion on part of option names, so for example if
you type `/fset hot` and press kbd:[Tab] this is completed as `/fset hotlist`.
If you press kbd:[Enter], options about the hotlist are displayed.

// TRANSLATION MISSING
For more information about `/fset` command and keys, see `/help fset`.

[[core_vs_plugins]]
== Core vs plugin

Il "core" di WeeChat è utilizzato solo per visualizzare i dati sullo schermo
e interagire con l'utente; ciò vuol dire che il core di weechat senza i
plugin è inutile (utenti più fedeli: IRC faceva parte del core per le
versioni ≤ 0.2.6).

Tutti i protocolli di rete come IRC sono forniti in plugin separati.

Utilizzando il comando `plugin` per elencare i plugin caricati, è possibile
vedere "irc" ed altri plugin nella lista.

// TRANSLATION MISSING
[[add_irc_server]]
== Add an IRC server

// TRANSLATION MISSING
You can add an IRC server with `/server` command, for example:

----
/server add libera irc.libera.chat/6697 -ssl
----

// TRANSLATION MISSING
In this command, `libera` is the internal server name used by WeeChat:
you'll be able to connect with `/connect libera` and the server options
are _irc.server.libera.xxx_.

Come al solito, è disponibile l'aiuto se c'è qualche problema:

----
/help server
----

[[irc_server_options]]
== Impostare opzioni personalizzate per il server IRC

WeeChat usa valori predefiniti per tutti i server, se non si specifica un
valore preciso per un'opzione del server. Questi valori predefiniti sono
"irc.server_default.*"

Per ogni opzione del server, WeeChat usa il proprio valore se definito
(non "nullo"). Altrimenti si utilizza il valore predefinito
("irc.server_default.xxx").

Per esempio ci sono dei nick predefiniti (basati sul proprio login un*x), ed
è possibile sovrascriverli per il server libera con il seguente comando:

----
/set irc.server.libera.nicks "mynick,mynick2,mynick3,mynick4,mynick5"
----

Per impostare il nome utente ed il nome reale:

----
/set irc.server.libera.username "Mio nome utente"
/set irc.server.libera.realname "Mio nome reale"
----

Per impostare la connessione automatica al server all'avvio:

----
/set irc.server.libera.autoconnect on
----

Se SASL è disponibile sul server, è possibile usarlo per l'autenticazione
(l'autenticazione avviene prima dell'ingresso nei canali):

----
/set irc.server.libera.sasl_username "mynick"
/set irc.server.libera.sasl_password "xxxxxxx"
----

Per eseguire un comando dopo la connessione al server, ad esempio per
autenticarsi con nickserv (solo se non viene usato SASL per l'autenticazione):

----
/set irc.server.libera.command "/msg nickserv identify xxxxxxx"
----

// TRANSLATION MISSING
[NOTE]
Many commands in option _command_ can be separated by `;` (semi-colon).

// TRANSLATION MISSING
If you want to protect your password in configuration files, you can use
secured data.

// TRANSLATION MISSING
First setup a passphrase:

----
/secure passphrase this is my secret passphrase
----

// TRANSLATION MISSING
Then add a secured data with your libera password:

----
/secure set libera_password xxxxxxx
----

// TRANSLATION MISSING
Then you can use `+${sec.data.libera_password}+` instead of your password in
IRC options mentioned above, for example:

----
/set irc.server.libera.sasl_password "${sec.data.libera_password}"
----

Per entrare automaticamente in alcuni canali quando ci si connette
al server:

----
/set irc.server.libera.autojoin "#canale1,#canale2"
----

// TRANSLATION MISSING
The `/autojoin` command lets you configure the _autojoin_ option easily
(see `/help autojoin`).

// TRANSLATION MISSING
You can also configure WeeChat to automatically update the _autojoin_ option
when you join or leave channels:

----
/set irc.server_default.autojoin_dynamic on
----

Per eliminare il valore di un'opzione del server, e usare invece il valore
predefinito, per esempio per utilizzare i nick predefiniti
(irc.server_default.nicks):

----
/unset irc.server.libera.nicks
----

Altre opzioni: è possibile impostare altre opzioni con il seguente comando
("xxx" è il nome dell'opzione):

----
/set irc.server.libera.xxx value
----

// TRANSLATION MISSING
[TIP]
You can complete name and value of options with the kbd:[Tab] key
and kbd:[Shift+Tab] for a partial completion (useful for long words like
the name of option).

[[connect_to_irc_server]]
== Connessione al server IRC

----
/connect libera
----

// TRANSLATION MISSING
With this command, WeeChat connects to the libera server and auto-joins the
channels configured in the "autojoin" server option.

// TRANSLATION MISSING
[NOTE]
Questo comando può essere usato per creare e connettersi ad un nuovo server
senza utilizzare il comando `/server` (see `/help connect`).

I buffer dei server vengono uniti al buffer _core_ di WeeChat in modo
predefinito. Per passare tra buffer _core_ e buffer server, si può digitare
kbd:[Ctrl+x].

È possibile disabilitare l'unione automatica dei server dei buffer per avere i
buffer dei server indipendenti:

----
/set irc.look.server_buffer independent
----

[[join_part_irc_channels]]
== Entrare/uscire dai canali IRC

Entra in un canale:

----
/join #canale
----

Esce da un canale (mantenendo il buffer aperto):

----
/part [messaggio di uscita]
----

// TRANSLATION MISSING
Close a server, channel or private buffer (`/close` is an alias for
`/buffer close`):

----
/close
----

// TRANSLATION MISSING
[WARNING]
Closing the server buffer will close all channel/private buffers.

// TRANSLATION MISSING
Disconnect from server, on the server buffer:

----
/disconnect
----

// TRANSLATION MISSING
[[irc_private_messages]]
== IRC private messages

Open a buffer and send a message to another user (nick _foo_):

----
/query foo this is a message
----

Close the private buffer:

----
/close
----

[[buffer_window]]
== Gestione buffer/finestra

Un buffer è un componente collegato ad un plugin con un numero,
una categoria e un nome. Un buffer contiene i dati visualizzati sullo
schermo.

Una finestra è la vista di un buffer. Il comportamento predefinito
prevede solo una finestra che visualizza un buffer. Se lo schermo
viene diviso, sarà possibile vedere più finestre con molti buffer allo
stesso tempo.

I comandi per gestire buffer e finestre:

----
/buffer
/window
----

Per esempio, per dividere verticalmente lo schermo in una finestra piccola
(1/3 della larghezza) ed una grande (2/3), utilizzare il comando:

----
/window splitv 33
----

// TRANSLATION MISSING
To remove the split:

----
/window merge
----

[[key_bindings]]
== Associazione tasti

WeeChat usa molti tasti. Essi sono tutti presenti nella documentazione,
ma si dovrebbero conoscere almeno quelli vitali:

- kbd:[Alt+←] / kbd:[Alt+→] oppure kbd:[F5] / kbd:[F6]: passa al buffer
  precedente/successivo
// TRANSLATION MISSING
- kbd:[F1] / kbd:[F2]: scroll bar with list of buffers ("buflist")
- kbd:[F7] / kbd:[F8]: passa alla finestra precedente/successiva (quando lo schermo
  è diviso)
- kbd:[F9] / kbd:[F10]: scorre la barra del titolo
- kbd:[F11] / kbd:[F12]: scorre la lista nick
- kbd:[Tab]: completa il testo nella barra di input, proprio come nella shell
- kbd:[PgUp] / kbd:[PgDn]: scorre testo nel buffer corrente
- kbd:[Alt+a]: passa al buffer con attività (nella hotlist)

A seconda della propria tastiera e/o le proprie necessità, è possibile
associare nuovamente qualsiasi tasto ad un comando tramite
`/key`.
Un tasto utile è kbd:[Alt+k] per trovare i codici tasti.

Ad esempio, per associare kbd:[Alt+!] al comando `/buffer close`:

----
/key bind (digitare alt-k) (digitare alt-!) /buffer close
----

Si otterrà una riga di comando simile a:

----
/key bind meta-! /buffer close
----

Per eliminare il tasto:

----
/key unbind meta-!
----

[[plugins_scripts]]
== Plugin/script

Su alcune distribuzioni come Debian, i plugin sono disponibili tramite un
pacchetto separato (come weechat-plugins).
I plugin vengono caricati automaticamente quando trovati
(per favore consultare la documentazione per caricare/scaricare plugin
o script).

// TRANSLATION MISSING
Many external scripts (from contributors) are available for WeeChat, you can
download and install scripts from the repository with the `/script` command,
for example:

----
/script install go.py
----

// TRANSLATION MISSING
See `/help script` for more info.

// TRANSLATION MISSING
A list of scripts is available in WeeChat with `/script` or on
https://weechat.org/scripts/[this page ^↗^,window=_blank].

[[more_doc]]
== Ulteriore documentazione

// TRANSLATION MISSING
You can now use WeeChat and read
https://weechat.org/doc/[FAQ/documentation ^↗^,window=_blank]
for any other questions.

Buon WeeChat!
