= FAQ di WeeChat (Domande Frequenti)
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: it
:toc:


[NOTE]
Questo documento è stato scritto per le versioni di WeeChat ≥ 0.3.0, ma dovrebbe
essere usato preferibilmente con l'ultima versione stabile di WeeChat.


[[general]]
== Generale

[[weechat_name]]
=== Da dove viene il nome "WeeChat"?

"Wee" è un acronimo ricorsivo che sta per "Wee Enhanced Environment".
Quindi il nome completo è "Wee Enhanced Envoronment for Chat."

"Wee" significa anche "molto piccolo" (e sì, c'è un altro significato, ma
non c'entra con WeeChat!).

[[why_choose_weechat]]
=== Perché scegliere WeeChat? X-Chat ed Irssi vanno così bene...

// TRANSLATION MISSING
Because WeeChat is very light and brings innovating features.

Maggiori informazioni su http://weechat.org/about/features

[[compilation_install]]
== Compilazione / installazione

[[gui]]
=== Ho sentito parlare di molte interfacce per WeeChat. Come si possono compilare/utilizzare?

// TRANSLATION MISSING
Some remote GUIs are available, see the links on features page:
http://weechat.org/about/features

[[compile_git]]
=== Non è possibile compilare WeeChat dopo aver clonato il repository git, perché?

Il metodo raccomandato per compilare WeeChat è utilizzando cmake.

Se si sta compilando con autotools (e non cmake), verificare che siano installate
le ultime versioni di autoconf e automake.

L'altro metodo è installare il "pacchetto di sviluppo", che richiede meno
dipendenze. Questo pacchetto viene generato  quasi tutti i giorni utilizzando
il repository git. È bene notare che potrebbe non corrispondere
esattamente alla base git ed è meno conveniente rispetto al clone di git
per l'installazione degli aggiornamenti.

// TRANSLATION MISSING
[[compile_osx]]
=== How can I install WeeChat on OS X?

// TRANSLATION MISSING
It is recommended to use http://brew.sh/[Homebrew], you can get help with:

----
brew info weechat
----

// TRANSLATION MISSING
You can install WeeChat with this command:

----
brew install weechat --with-python --with-perl
----

[[lost]]
=== Ho avviato WeeChat, ma mi sono perso, cosa posso fare?

Per l'aiuto digitare `/help`. Per l'aiuto su un comando, digitare `/help comando`.
Tasti e comandi sono elencati nella documentazione.

Si raccomanda ai nuovi utenti di leggere la guida rapida: http://weechat.org/doc

[[display]]
== Visualizzare

[[charset]]
=== Non riesco a vedere alcuni caratteri con gli accenti, cosa posso fare?

È un problema noto, per favore leggere con attenzione e verificare *OGNI*
soluzione tra quelle elencate:

* verificare che weechat abbia un link con libncursesw (attenzione:
  necessario su molte distribuzioni ma non tutte): `ldd /path/di/weechat`
* verificare che il plugin "charset" sia caricato con il comando `plugin` (se non
  lo è, probabilmente è necessario il pacchetto "weechat-plugins")
* verificare l'output del comando `/charset` (sul buffer core). Dovrebbero essere
  visualizzati 'ISO-XXXXXX' oppure 'UTF-8' per il set caratteri del terminale.
  Se invece compaiono 'ANSI_X3.4-1968' o altri valori, il locale probabilmente
  non è esatto (correggere la variabile $LANG).
* impostare il valore di decodifica globale, per esempio:
  `/set charset.default.decode = ISO-8859-15`
* se si usa la localizzazione UTF-8:
** verificare che il proprio terminale sia compatibile con UTF-8 (quello
    raccomandato è rxvt-unicode)
** se si sta utilizzando screen, verificare che sia in esecuzione in modalità
    UTF-8 ("`defutf8 on` nel file ~/.screenrc` oppure `screen -U` per avviare
    screen)
// TRANSLATION MISSING
* check that option 'weechat.look.eat_newline_glitch' is off (this option may
  cause display bugs)

[NOTE]
Si raccomanda il locale UTF-8 per WeeChat. Se si utilizza ISO o un altro
locale, per favore verificare che *tutte* le impostazioni (terminale, screen)
siano ISO e *non* UTF-8.

[[bars_background]]
=== Barre come quella del titolo e di stato non sono complete, il colore di sfondo si ferma dopo il testo, perché?

Potrebbe essere causato da un valore errato della variabile TERM nella propria
shell (consultare l'output di `echo $TERM` nel terminale).

A seconda di dove viene eseguito WeeChat, si dovrebbe avere:

* se WeeChat viene eseguito localmente o su una macchina remota senza
  screen, dipende dal terminale utilizzato: 'xterm', 'xterm-256color',
  'rxvt-unicode', 'rxvt-256color', ...
* se WeeChat viene eseguito in screen, dovrebbe essere 'screen' o 'screen-256color'.

Se necessario, correggere la variabile TERM: `export TERM="xxx"`.

[[screen_weird_chars]]
=== Quando uso weechat con screen/tmux, appaiono dei caratteri strani, come posso risolvere il problema?

Potrebbe essere causato da un valore errato della variabile TERM nella propria
shell (consultare l'output di `echo $TERM` nel terminale *al di fuori di
screen/tmux*).

Per esempio, 'xterm-color' potrebbe visualizzare questo tipo di caratteri strani,
è meglio utilizzare 'xterm' che funziona (come molti altri valori).

Se necessario, correggere la variabile TERM: `export TERM="xxx"`.

[[osx_display_broken]]
=== Ho compilato WeeChat su OS X, e vedo "(null)" dovunque sullo schermo, cosa non va?

Se ncursesw è stato compilato manualmente, utilizzare ncurses standard (incluse
col sistema).

Inoltre, su OS X, si raccomanda di installare WeeChat con il gestore pacchetti
Homebrew.

[[buffer_vs_window]]
=== Ho sentito parlare di "buffer" e "finestre", qual è la differenza?

Un 'buffer' è composto da un numero, un nome, delle righe visualizzate (e
qualche altro dato).

Una 'finestra' (o window) è un'aread dello schermo in cui viene visualizzato
un buffer. È possibile dividere lo schermo in più finestre.

Ogni finestra visualizza un buffer. Un buffer può essere nascosto (non visualizzato
da una finestra) o visualizzato da una o più finestre.

[[buffers_list]]
=== Come si può visualizzare la lista dei buffer sulla sinistra?

Utilizzando lo script 'buffers.pl':

----
/script install buffers.pl
----

Per limitare la dimensione della barra:

----
/set weechat.bar.buffers.size_max 15
----

Per spostare la barra in basso:

----
/set weechat.bar.buffers.position bottom
----

[[customize_prefix]]
=== Come si può ridurre la lunghezza dei nick o rimuovere l'allineamento nella finestra di chat?

Per ridurre la lunghezza massima dei nick nell'area di chat:

----
/set weechat.look.prefix_align_max 15
----

To remove nick alignment:
Per rimuovere l'allineamento dei nick:

----
/set weechat.look.prefix_align none
----

[[input_bar_size]]
=== Come posso usare la riga di comando con più di una riga?

L'opzione 'size' nella barra di input può essere impostata a un valore maggiore
di uno (il valore predefinito per la dimensione fissa è 1) oppure 0 per la
dimensione dinamica, e poi l'opzione 'size_max' imposta la dimensione massima (0
= nessun limite).

Esempio con la dimensione dinamica:

----
/set weechat.bar.input.size 0
----

Dimensione massima a 2:

----
/set weechat.bar.input.size_max 2
----

[[one_input_root_bar]]
=== È possibile mostrare solo una barra di input per tutte le finestre (dopo lo split)?

Sì, bisogna creare una barra con il tipo "root" (con un elemento per sapere in
quale finestra ci si trova), poi eliminare la barra di input corrente.

Ad esempio:

----
/bar add rootinput root bottom 1 0 [buffer_name]+[input_prompt]+(away),[input_search],[input_paste],input_text
/bar del input
----

Se non si è soddisfatti del risultato, basta eliminare la nuova barra, WeeChat
creerà automaticamente la barra predefinita "input" se l'elemento "input_text"
non viene usato da un'altra barra:

----
/bar del rootinput
----

[[terminal_copy_paste]]
=== Come posso copiare/incollare testo senza incollare la lista nick?

// TRANSLATION MISSING
With WeeChat ≥ 1.0, you can use the bare display (default key: key[alt-l]).

È possibile usare un terminale con la selezione rettangolare (come
rxvt-unicode, konsole, gnome-terminal, ...). La combinazione tasti in
generale è key[ctrl-]key[alt-] selezione mouse.

Un'altra soluzione è spostare la lista nick in alto o in basso, per esempio:

----
/set weechat.bar.nicklist.position top
----

[[urls]]
=== Come posso cliccare su URL lunghi (più di una riga)?

// TRANSLATION MISSING
With WeeChat ≥ 1.0, you can use the bare display (default key: key[alt-l]).

Con le impostazioni predefinite, WeeChat mostra l'ora ed il prefisso per ogni
riga e le barre opzionali intorno all'area di chat. Per facilitare il clic
delle url, è possibile spostare la lista nick in alto e rimuovere
l'allineamento sul nick:

----
/set weechat.bar.nicklist.position top
/set weechat.look.prefix_align none
/set weechat.look.align_end_of_lines time
----

Con WeeChat ≥ 0.3.6, si può abilitare l'opzione "eat_newline_glitch", in
modo che non venga aggiunto il carattere di nuova riga all'inizio di ogni riga
visualizzata (non interferisce con la selezione delle url):

----
/set weechat.look.eat_newline_glitch on
----

[IMPORTANT]
Questa opzione può causare bug di visualizzazione. Se si dovessero verificare
tali problemi, è necessario disabilitare questa opzione.

Una soluzione alternativa è usare uno script:

----
/script search url
----

[[change_locale_without_quit]]
=== Voglio cambiare la lingua utilizzata da WeeChat per i messaggi, ma senza uscire da WeeChat, è possibile?

// TRANSLATION MISSING
Yes, with WeeChat ≥ 1.0:

----
/set env LANG it_IT.UTF-8
/upgrade
----

// TRANSLATION MISSING
With older WeeChat:

----
/script install shell.py
/shell setenv LANG=it_IT.UTF-8
/upgrade
----

[[use_256_colors]]
=== Come posso usare 256 colori in WeeChat?

I 256 colori sono supportati nelle versioni di WeeChat ≥ 0.3.4.

Per prima cosa verificare che la variabile di ambiente 'TERM' sia corretta, i
valori raccomandati sono:

* con screen: 'screen-256color'
* al di fuori di screen: 'xterm-256color', 'rxvt-256color', 'putty-256color',...

[NOTE]
Potrebbe essere necessario installare il pacchetto "ncurses-term" per usare
questi valori nella variabile 'TERM'.

Se si sta utilizzando screen, è possibile aggiungere questa riga al
proprio '~/.screenrc':

----
term screen-256color
----

// TRANSLATION MISSING
If your 'TERM' variable has wrong value and that WeeChat is already running,
you can change it with these two commands (with WeeChat ≥ 1.0):

----
/set env TERM screen-256color
/upgrade
----

Per la versione 0.3.4, bisogna usare il comando `/color` per aggiungere nuovi colori.

Per le versioni ≥ 0.3.5, è possibile usare qualsiasi numero di colore nelle
opzioni (opzionale: si possono aggiungere gli alias ai colori con il comando `/color`).

Per favore consultare la guida per l'utente per maggiori informazioni sulla gestione
dei colori.

[[search_text]]
=== Come posso cercare testo nel buffer (come /lastlog con irssi)?

Il tasto predefinito è key[ctrl-r] (il comando è: `/input search-text`).
E per passare alle notifiche: key[alt-p] / key[alt-n].

Consultare la guida per l'utente per maggiori informazioni su questa funzione
(combinazioni tasti predefiniti).

// TRANSLATION MISSING
[[terminal_focus]]
=== How can I execute commands when terminal gets/loses focus?

You must enable the focus events with a special code sent to terminal.

*Important*:

* Currently, *only* 'xterm' seems to support this feature.
* It does *not* work under screen/tmux.

To send the code when WeeChat is starting:

----
/set weechat.startup.command_after_plugins "/print -stdout \033[?1004h\n"
----

And then you bind two keys for the focus (replace the `/print` commands by the
commands of your choice):

----
/key bind meta2-I /print -core focus
/key bind meta2-O /print -core unfocus
----

[[key_bindings]]
== Associazioni dei tasti

[[meta_keys]]
=== Alcuni tasti meta (alt + tasto) non funzionano, perché?

Se si utilizzano terminali come xterm o uxterm, alcuni tasti meta non funzionano
per default. È possibile aggiungere una riga nel file '~/.Xresources':

* per xterm:
----
XTerm*metaSendsEscape: true
----
* per uxterm:
----
UXTerm*metaSendsEscape: true
----

Al termine, ricaricare la configurazione (`xrdb -override ~/.Xresources`) o riavviare X.

[[customize_key_bindings]]
=== Come posso personalizzare le associazioni dei tasti?

Le associazioni dei tasti sono personalizzabili con il comando `/key`.

Il tasto predefinito key[alt-k] consente di registrare il codice tasto ed
inserirlo nella riga di comando.

[[jump_to_buffer_11_or_higher]]
=== Qual è il tasto per passare al buffer 11 (o superiore)?

Il tasto è key[alt-j] seguito da due numeri, ad esempio key[alt-j], key[1],
key[1] per passare al buffer 11.

È possibile associare un tasto, ad esempio:

----
/key bind meta-q /buffer *11
----

List of default keys is in User's guide.
L'elenco dei tasti predefiniti è nella Guida dell'utente.

[[global_history]]
=== Come si può usare la cronologia globale (invece di quella del buffer) con i tasti su e giù?

È possibile associare i tasti su e giù alla cronologia globale (quelli predefiniti
sono key[ctrl-↑] e key[ctrl-↓]).

Esempio:

----
/key bind meta2-A /input history_global_previous
/key bind meta2-B /input history_global_next
----

[NOTE]
I tasti "meta2-A" e "meta2-B" possono essere differenti nel proprio terminale.
Per trovare il codice tasto digitare key[alt-k] poi il tast (su o giù).

[[mouse]]
== Mouse

[[mouse_not_working]]
=== Il mouse non funziona affatto, cosa posso fare?

Il mouse è supportato con le versioni di WeeChat ≥ 0.3.6.

Per prima cosa provare ad abilitare il mouse:

----
/mouse enable
----

Se il mouse ancora non funziona, verificare la variabile TERM nella propria
shell (consultare l'output di `echo $TERM` nel terminale).
In base al terminale usato, il mouse potrebbe non essere supportato.

È possibile testare il supporto al mouse nel terminale:

----
$ printf '\033[?1002h'
----

E poi cliccare sul primo carattere del terminale (in alto a sinistra. Dovrebbe
essere possibile vedere  !!#!!".

Per disabilitare il mouse nel terminale:

----
$ printf '\033[?1002l'
----

[[mouse_coords]]
=== Il mouse non fa nulla per X o Y maggiori di 94 (o 222), perché?

Alcuni terminale inviano solo caratteri ISO per le coordinate del mouse, per cui
non funziona per X/Y maggiori di 94 (o 222).

Bisogna utilizzare un terminale che supporti le coordinate UTF-8 per il mouse,
come rxvt-unicode.

[[mouse_select_paste]]
=== Come posso selezionare o incollare del testo nel terminale quando il mouse è abilitato in WeeChat?

Quando il mouse è abilitato in WeeChat, è possibile usare il modificatore
key[shift] per selezionare o cliccare nel terminale, come se il mouse fosse
disabilitato (in alcuni terminali come iTerm, bisogna usare key[alt] invece di
key[shift]).

[[irc]]
== IRC

[[irc_ssl_connection]]
=== Ho dei problemi nella connessione al server con SSL, cosa posso fare?

// TRANSLATION MISSING
If you are using Mac OS X, you must install `curl-ca-bundle` and set the path
to certificates in WeeChat:

----
/set weechat.network.gnutls_ca_file "/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt"
----

Se si verificano problemi con l'handshake gnutls, si può cercare di
usare una chiave Diffie-Hellman più piccola (la predefinita è 2048):

----
/set irc.server.freenode.ssl_dhkey_size 1024
----

Se si verificano errori con i certificati, è possibile disabilitare "ssl_verify"
(attenzione, la connessione in questo modo sarà meno sicura):

----
/set irc.server.freenode.ssl_verify off
----

[[irc_ssl_handshake_error]]
=== Alla connessione al server con SSL ottengo solo l'errore "handshake TLS fallito", cosa posso fare?

Provare una stringa di priorità diversa (solo WeeChat ≥ 0.3.5), sostituendo
"xxx" con il nome del server:

----
/set irc.server.xxx.ssl_priorities "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.0:+VERS-SSL3.0:%COMPAT"
----

[[irc_ssl_freenode]]
=== Come ci si può connettere al server freenode via SSL?

Impostare l'opzione 'weechat.network.gnutls_ca_file' con il file dei certificati:

----
/set weechat.network.gnutls_ca_file "/etc/ssl/certs/ca-certificates.crt"
----

[NOTE]
Verificare la presenza di questo file sul sistema (solitamente installato dal
pacchetto "ca-certificates").

Impostare la porta del server, SSL, dhkey_size, poi riconnettersi:

----
/set irc.server.freenode.addresses "chat.freenode.net/7000"
/set irc.server.freenode.ssl on
/set irc.server.freenode.ssl_dhkey_size 1024
/connect freenode
----

// TRANSLATION MISSING
[[irc_oauth]]
=== How to connect to a server that requires "oauth"?

Some servers like 'twitch' require oauth to connect.

The oauth is simply a password with the value "oauth:XXXX".

You can create such server and connect with following commands (replace name
and address by appropriate values):

----
/server add name irc.server.org -password=oauth:XXXX
/connect name
----

[[irc_sasl]]
=== Come posso essere identificato prima di entrare in un canale?

Se il server supporta SASL, dovrebbe essere utilizzato invece di inviare il
comando di autenticazione con nickserv, ad esempio:

----
/set irc.server_default.sasl_mechanism dh-blowfish
/set irc.server.freenode.sasl_username "mynick"
/set irc.server.freenode.sasl_password "xxxxxxx"
----

Se il server non supporta SASL, è possibile aggiungere un ritardo (tra il
comando e l'ingresso nei canali):

----
/set irc.server.freenode.command_delay 5
----

[[ignore_vs_filter]]
=== Qual è la differenza tra i comandi /ignore e /filter?

Il comando `/ignore` è un comando IRC, per cui è utile solo per i buffer
IRC (server e canali).
Consente di ignorare alcuni nick o nomi host di utenti per un server o per
un canale (il comando non viene applicato sul contenuto dei messaggi).
I messaggi corrispondenti vengono eliminati dal plugin IRC prima di
essere visualizzati (perciò non verranno mai mostrati).

Il comando `/filter` è un comando core, perciò funziona per qualsiasi
buffer. Esso consente di filtrare alcune righe nei buffer mediante tag
o espressioni regolari per il prefisso ed il contenuto delle righe.
Le righe filtrate vengono solo nascoste, non eliminate, ed è possibile
visualizzarle se i filtri vengono disabilitati (il comando predefinito
key[alt-=] abilita/disabilita i filtri).

[[filter_irc_join_part_quit]]
=== Come posso filtrare i messaggi di entrata/uscita/abbandono sui canali IRC?

Con il filtro intelligente (mantiene entrata/uscita/abbandono degli utenti che
hanno scritto di recente):

----
/set irc.look.smart_filter on
/filter add irc_smart * irc_smart_filter *
----

Con un filtro globale (nasconde *tutti* entrata/uscita/abbandono):

----
/filter add joinquit * irc_join,irc_part,irc_quit *
----

[NOTE]
Per aiuto: `/help filter` e `/help irc.look.smart_filter`

[[filter_irc_join_channel_messages]]
=== Come posso filtrare i messaggi visualizzati all'ingresso su un canale IRC?

// TRANSLATION MISSING
With WeeChat ≥ 0.4.1, you can choose which messages are displayed or not when
joining a channel with the option 'irc.look.display_join_message' (see
`/help irc.look.display_join_message` for more info).

// TRANSLATION MISSING
To hide messages (but keep them in buffer), you can filter them using the tag
(for example 'irc_329' for channel creation date). See `/help filter` for help
with filters.

[[filter_voice_messages]]
=== Come posso filtrare i messaggi voice (ad esempio su server Bitlbee)?

Non è semplice filtrare i messaggi voice, perché la modalità voice può essere
impostata in altri modi nello stesso messaggio IRC.

Se si vuole, è probabilmente perché Bitlbee utilizza il voice per visualizzare gli
utenti assenti, e si viene tempestati di messaggi voice. Perciò, è possibile
modificare questo comportamento e consentire a WeeChat di utilizzare un
colore speciale per i nick assenti nella lista nick.

Per versioni di Bitlbee ≥ 3, sul canale '&bitlbee' digitare:

----
channel set show_users online,away
----

Per versioni precedenti di Bitlbee, sul canale '&bitlbee' digitare:

----
set away_devoice false
----

Per verificare i nick assenti in WeeChat, consultare la domanda
relativa a <<color_away_nicks,nick assenti>>.

Se davvero di desidera filtrare i messaggi voice, è possibile usare questo
comando, ma non funzionerà perfettamente (funziona se la prima modalità
modificata è il voice):

----
/filter add hidevoices * irc_mode (\+|\-)v
----

[[color_away_nicks]]
=== Come posso vedere i nick assenti nella lista nick?

È necessario impostare l'opzione 'irc.server_default.away_check' su un valore
positivo (minuti tra ogni controllo dei nick assenti).

L'opzione 'irc.server_default.away_check_max_nicks' limita il controllo delle
assenze solo sui canali più piccoli.

Ad esempio, per controllare ogni 5 minuti per i nick assenti, sui canali con
massimo 25 nick:

----
/set irc.server_default.away_check 5
/set irc.server_default.away_check_max_nicks 25
----

[NOTE]
Per WeeChat ≤ 0.3.3, le opzioni sono 'irc.network.away_check' e
'irc.network.away_check_max_nicks'.

[[highlight_notification]]
=== Come posso essere avvisato quando qualcuno mi cerca in un canale?

// TRANSLATION MISSING
With WeeChat ≥ 1.0, there is a default trigger "beep" which sends a 'BEL' to
the terminal on a highlight or private message. Thus you can configure your
terminal (or multiplexer like screen/tmux) to run a command or play a sound
when a 'BEL' occurs.

// TRANSLATION MISSING
Or you can add a command in "beep" trigger:

----
/set trigger.trigger.beep.command "/print -beep;/exec -bg /path/del/comando argomenti"
----

// TRANSLATION MISSING
With an older WeeChat, you can use a script like 'beep.pl' or 'launcher.pl'.

Per 'launcher.pl', bisogna impostare il comando:

----
/set plugins.var.perl.launcher.signal.weechat_highlight "/path/del/comando argomenti"
----

Altri script correlati:

----
/script search notify
----

[[irc_target_buffer]]
=== Come si può modificare il buffer destinazione per i comandi sui buffer uniti (come i buffer con i server)?

Il tasto predefinito è key[ctrl-x] (il comando è: `/input switch_active_buffer`).

[[plugins_scripts]]
== Plugin / script

[[openbsd_plugins]]
=== Uso OpenBSD e WeeChat non carica nessun plugin, cosa c'è che non va?

In OpenBSD, i nomi file dei plugin finiscono con ".so.0.0" (".so" in Linux).

Si deve impostare in questo modo:

----
/set weechat.plugin.extension ".so.0.0"
/plugin autoload
----

// TRANSLATION MISSING
[[install_scripts]]
=== How can I install scripts? Are scripts compatible with other IRC clients?

// TRANSLATION MISSING
You can use the command `/script` to install and manage scripts
(see `/help script` for help).

Gli script non sono compatibili con altri client IRC.

[[settings]]
== Impostazioni

[[memory_usage]]
=== Come posso ottimizzare WeeChat per poter utilizzare meno memoria?

Esistono diversi trucchi per ottimizzare l'uso della memoria:

* utilizzare l'ultima versione stabile (si suppone che abbia meno falle di memoria
  rispetto le versioni precedenti)
* non caricare alcuni plugin se non vengono utilizzati, ad esempio: aspell, fifo,
  logger, perl, python, ruby, lua, tcl, guile, xfer (usato per DCC)
* caricare solo gli script veramente necessari
* non caricare i certificati se SSL *NON* viene usato: usare una stringa vuota nell'opzione
  'weechat.network.gnutls_ca_file'
* ridurre il valore dell'opzione 'weechat.history.max_buffer_lines_number'  oppure
  impostare il valore dell'opzione 'weechat.history.max_buffer_lines_minutes'
* ridurre il valore dell'opzione 'weechat.history.max_commands'

// TRANSLATION MISSING
[[cpu_usage]]
=== How can I tweak WeeChat to use less CPU?

// TRANSLATION MISSING
You can follow same tips as for <<memory_usage,memory>>, and these ones:

* hide "nicklist" bar: `/bar hide nicklist`
* remove display of seconds in status bar time:
  `/set weechat.look.item_time_format "%H:%M"` (this is the default value)
* set the 'TZ' variable (for example: `export TZ="Europe/Paris"`), to prevent
  frequent access to file '/etc/localtime'

[[development]]
== Sviluppo

[[bug_task_patch]]
=== Come posso segnalare bug, richiedere nuove funzionalità o inviare patch?

// TRANSLATION MISSING
See: http://weechat.org/dev/support

[[gdb_error_threads]]
=== Quando eseguo WeeChat in gdb, c'è un errore riguardo ai thread, cosa posso fare?

Quando viene eseguito WeeChat all'interno di gdb, potrebbe verificarsi
questo errore:

----
$ gdb /path/to/weechat
(gdb) run
[Thread debugging using libthread_db enabled]
Cannot find new threads: generic error
----

Per correggerlo, è possibile eseguire gdb con questo comando (sostituire il
path di libpthread e WeeChat con i path del proprio sistema):

----
$ LD_PRELOAD=/lib/libpthread.so.0 gdb /path/to/weechat
(gdb) run
----

[[supported_os]]
=== Qual è la lista delle piattaforme supportate da WeeChat? Verrà effettuato il port su altri sistemi operativi?

La lista completa è su questa pagina: http://weechat.org/download

Facciamo del nostro meglio per portarlo su più piattaforme possibili. L'aiuto
per gli OS che non abbiamo, e su cui testare WeeChat, è ben accetto.

[[help_developers]]
=== Voglio aiutare gli sviluppatori di WeeChat. Cosa posso fare?

Ci sono molti compiti da fare (testing, scrittura del codice, documentazione, ...)

Per favore contattateci su IRC o via mail e consultate la pagina di supporto:
http://weechat.org/dev/support

[[donate]]
=== Posso donare denaro o altre cose agli sviluppatori di WeeChat?

È possibile donare denaro per aiutare lo sviluppo.
Maggiori dettagli su http://weechat.org/about/donate
