WEECHAT_RC_OK = ...
WEECHAT_RC_OK_EAT = ...
WEECHAT_RC_ERROR = ...
WEECHAT_CONFIG_READ_OK = ...
WEECHAT_CONFIG_READ_MEMORY_ERROR = ...
WEECHAT_CONFIG_READ_FILE_NOT_FOUND = ...
WEECHAT_CONFIG_WRITE_OK = ...
WEECHAT_CONFIG_WRITE_ERROR = ...
WEECHAT_CONFIG_WRITE_MEMORY_ERROR = ...
WEECHAT_CONFIG_OPTION_SET_OK_CHANGED = ...
WEECHAT_CONFIG_OPTION_SET_OK_SAME_VALUE = ...
WEECHAT_CONFIG_OPTION_SET_ERROR = ...
WEECHAT_CONFIG_OPTION_SET_OPTION_NOT_FOUND = ...
WEECHAT_CONFIG_OPTION_UNSET_OK_NO_RESET = ...
WEECHAT_CONFIG_OPTION_UNSET_OK_RESET = ...
WEECHAT_CONFIG_OPTION_UNSET_OK_REMOVED = ...
WEECHAT_CONFIG_OPTION_UNSET_ERROR = ...
WEECHAT_LIST_POS_SORT = ...
WEECHAT_LIST_POS_BEGINNING = ...
WEECHAT_LIST_POS_END = ...
WEECHAT_HOTLIST_LOW = ...
WEECHAT_HOTLIST_MESSAGE = ...
WEECHAT_HOTLIST_PRIVATE = ...
WEECHAT_HOTLIST_HIGHLIGHT = ...
WEECHAT_HOOK_PROCESS_RUNNING = ...
WEECHAT_HOOK_PROCESS_ERROR = ...
WEECHAT_HOOK_CONNECT_OK = ...
WEECHAT_HOOK_CONNECT_ADDRESS_NOT_FOUND = ...
WEECHAT_HOOK_CONNECT_IP_ADDRESS_NOT_FOUND = ...
WEECHAT_HOOK_CONNECT_CONNECTION_REFUSED = ...
WEECHAT_HOOK_CONNECT_PROXY_ERROR = ...
WEECHAT_HOOK_CONNECT_LOCAL_HOSTNAME_ERROR = ...
WEECHAT_HOOK_CONNECT_GNUTLS_INIT_ERROR = ...
WEECHAT_HOOK_CONNECT_GNUTLS_HANDSHAKE_ERROR = ...
WEECHAT_HOOK_CONNECT_MEMORY_ERROR = ...
WEECHAT_HOOK_CONNECT_TIMEOUT = ...
WEECHAT_HOOK_CONNECT_SOCKET_ERROR = ...
WEECHAT_HOOK_SIGNAL_STRING = ...
WEECHAT_HOOK_SIGNAL_INT = ...
WEECHAT_HOOK_SIGNAL_POINTER = ...

def register(name, author, version, license, description, shutdown_function, charset):
    """`register in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_register>`_"""
    ...
def plugin_get_name(plugin):
    """`plugin_get_name in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_plugin_get_name>`_"""
    ...
def charset_set(charset):
    """`charset_set in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_charset_set>`_"""
    ...
def iconv_to_internal(charset, string):
    """`iconv_to_internal in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_iconv_to_internal>`_"""
    ...
def iconv_from_internal(charset, string):
    """`iconv_from_internal in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_iconv_from_internal>`_"""
    ...
def gettext(string):
    """`gettext in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_gettext>`_"""
    ...
def ngettext(string, plural, count):
    """`ngettext in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_ngettext>`_"""
    ...
def strlen_screen(string):
    """`strlen_screen in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_strlen_screen>`_"""
    ...
def string_match(string, mask, case_sensitive):
    """`string_match in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_string_match>`_"""
    ...
def string_match_list(string, masks, case_sensitive):
    """`string_match_list in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_string_match_list>`_"""
    ...
def string_eval_path_home(path, pointers, extra_vars, options):
    """`string_eval_path_home in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_string_eval_path_home>`_"""
    ...
def string_mask_to_regex(mask):
    """`string_mask_to_regex in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_string_mask_to_regex>`_"""
    ...
def string_has_highlight(string, highlight_words):
    """`string_has_highlight in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_string_has_highlight>`_"""
    ...
def string_has_highlight_regex(string, regex):
    """`string_has_highlight_regex in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_string_has_highlight_regex>`_"""
    ...
def string_format_size(size):
    """`string_format_size in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_string_format_size>`_"""
    ...
def string_remove_color(string, replacement):
    """`string_remove_color in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_string_remove_color>`_"""
    ...
def string_is_command_char(string):
    """`string_is_command_char in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_string_is_command_char>`_"""
    ...
def string_input_for_buffer(string):
    """`string_input_for_buffer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_string_input_for_buffer>`_"""
    ...
def string_eval_expression(expr, pointers, extra_vars, options):
    """`string_eval_expression in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_string_eval_expression>`_"""
    ...
def mkdir_home(directory, mode):
    """`mkdir_home in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_mkdir_home>`_"""
    ...
def mkdir(directory, mode):
    """`mkdir in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_mkdir>`_"""
    ...
def mkdir_parents(directory, mode):
    """`mkdir_parents in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_mkdir_parents>`_"""
    ...
def list_new():
    """`list_new in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_list_new>`_"""
    ...
def list_add(list, data, where, user_data):
    """`list_add in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_list_add>`_"""
    ...
def list_search(list, data):
    """`list_search in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_list_search>`_"""
    ...
def list_search_pos(list, data):
    """`list_search_pos in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_list_search_pos>`_"""
    ...
def list_casesearch(list, data):
    """`list_casesearch in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_list_casesearch>`_"""
    ...
def list_casesearch_pos(list, data):
    """`list_casesearch_pos in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_list_casesearch_pos>`_"""
    ...
def list_get(list, position):
    """`list_get in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_list_get>`_"""
    ...
def list_set(item, value):
    """`list_set in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_list_set>`_"""
    ...
def list_next(item):
    """`list_next in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_list_next>`_"""
    ...
def list_prev(item):
    """`list_prev in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_list_prev>`_"""
    ...
def list_string(item):
    """`list_string in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_list_string>`_"""
    ...
def list_size(list):
    """`list_size in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_list_size>`_"""
    ...
def list_remove(list, item):
    """`list_remove in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_list_remove>`_"""
    ...
def list_remove_all(list):
    """`list_remove_all in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_list_remove_all>`_"""
    ...
def list_free(list):
    """`list_free in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_list_free>`_"""
    ...
def config_new(name, callback_reload, callback_reload_data):
    """`config_new in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_new>`_"""
    ...
def config_new_section(config_file, name, user_can_add_options, user_can_delete_options, callback_read, callback_read_data, callback_write, callback_write_data, callback_create_option, callback_create_option_data, callback_delete_option, callback_delete_option_data):
    """`config_new_section in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_new_section>`_"""
    ...
def config_search_section(config_file, section_name):
    """`config_search_section in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_search_section>`_"""
    ...
def config_new_option(config_file, section, name, type, description, string_values, min, max, default_value, value, null_value_allowed, callback_check_value, callback_check_value_data, callback_change, callback_change_data, callback_delete, callback_delete_data):
    """`config_new_option in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_new_option>`_"""
    ...
def config_search_option(config_file, section, option_name):
    """`config_search_option in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_search_option>`_"""
    ...
def config_string_to_boolean(text):
    """`config_string_to_boolean in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_string_to_boolean>`_"""
    ...
def config_option_reset(option, run_callback):
    """`config_option_reset in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_option_reset>`_"""
    ...
def config_option_set(option, value, run_callback):
    """`config_option_set in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_option_set>`_"""
    ...
def config_option_set_null(option, run_callback):
    """`config_option_set_null in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_option_set_null>`_"""
    ...
def config_option_unset(option):
    """`config_option_unset in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_option_unset>`_"""
    ...
def config_option_rename(option, new_name):
    """`config_option_rename in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_option_rename>`_"""
    ...
def config_option_is_null(option):
    """`config_option_is_null in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_option_is_null>`_"""
    ...
def config_option_default_is_null(option):
    """`config_option_default_is_null in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_option_default_is_null>`_"""
    ...
def config_boolean(option):
    """`config_boolean in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_boolean>`_"""
    ...
def config_boolean_default(option):
    """`config_boolean_default in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_boolean_default>`_"""
    ...
def config_integer(option):
    """`config_integer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_integer>`_"""
    ...
def config_integer_default(option):
    """`config_integer_default in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_integer_default>`_"""
    ...
def config_string(option):
    """`config_string in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_string>`_"""
    ...
def config_string_default(option):
    """`config_string_default in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_string_default>`_"""
    ...
def config_color(option):
    """`config_color in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_color>`_"""
    ...
def config_color_default(option):
    """`config_color_default in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_color_default>`_"""
    ...
def config_write_option(config_file, option):
    """`config_write_option in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_write_option>`_"""
    ...
def config_write_line(config_file, option_name, value):
    """`config_write_line in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_write_line>`_"""
    ...
def config_write(config_file):
    """`config_write in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_write>`_"""
    ...
def config_read(config_file):
    """`config_read in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_read>`_"""
    ...
def config_reload(config_file):
    """`config_reload in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_reload>`_"""
    ...
def config_option_free(option):
    """`config_option_free in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_option_free>`_"""
    ...
def config_section_free_options(section):
    """`config_section_free_options in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_section_free_options>`_"""
    ...
def config_section_free(section):
    """`config_section_free in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_section_free>`_"""
    ...
def config_free(config_file):
    """`config_free in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_free>`_"""
    ...
def config_get(option_name):
    """`config_get in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_get>`_"""
    ...
def config_get_plugin(option_name):
    """`config_get_plugin in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_get_plugin>`_"""
    ...
def config_is_set_plugin(option_name):
    """`config_is_set_plugin in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_is_set_plugin>`_"""
    ...
def config_set_plugin(option_name, value):
    """`config_set_plugin in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_set_plugin>`_"""
    ...
def config_set_desc_plugin(option_name, description):
    """`config_set_desc_plugin in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_set_desc_plugin>`_"""
    ...
def config_unset_plugin(option_name):
    """`config_unset_plugin in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_config_unset_plugin>`_"""
    ...
def key_bind(context, keys):
    """`key_bind in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_key_bind>`_"""
    ...
def key_unbind(context, key):
    """`key_unbind in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_key_unbind>`_"""
    ...
def prefix(prefix):
    """`prefix in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_prefix>`_"""
    ...
def color(color_name):
    """`color in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_color>`_"""
    ...
def prnt(buffer, message):
    """`prnt in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_prnt>`_"""
    ...
def prnt_date_tags(buffer, date, tags, message):
    """`prnt_date_tags in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_prnt_date_tags>`_"""
    ...
def prnt_y(buffer, y, message):
    """`prnt_y in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_prnt_y>`_"""
    ...
def log_print(message):
    """`log_print in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_log_print>`_"""
    ...
def hook_command(command, description, args, args_description, completion, callback, callback_data):
    """`hook_command in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_command>`_"""
    ...
def hook_completion(completion_item, description, callback, callback_data):
    """`hook_completion in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_completion>`_"""
    ...
def hook_completion_get_string(completion, property):
    """`hook_completion_get_string in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_completion_get_string>`_"""
    ...
def hook_completion_list_add(completion, word, nick_completion, where):
    """`hook_completion_list_add in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_completion_list_add>`_"""
    ...
def hook_command_run(command, callback, callback_data):
    """`hook_command_run in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_command_run>`_"""
    ...
def hook_timer(interval, align_second, max_calls, callback, callback_data):
    """`hook_timer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_timer>`_"""
    ...
def hook_fd(fd, flag_read, flag_write, flag_exception, callback, callback_data):
    """`hook_fd in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_fd>`_"""
    ...
def hook_process(command, timeout, callback, callback_data):
    """`hook_process in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_process>`_"""
    ...
def hook_process_hashtable(command, options, timeout, callback, callback_data):
    """`hook_process_hashtable in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_process_hashtable>`_"""
    ...
def hook_connect(proxy, address, port, ipv6, retry, local_hostname, callback, callback_data):
    """`hook_connect in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_connect>`_"""
    ...
def hook_line(buffer_type, buffer_name, tags, callback, callback_data):
    """`hook_line in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_line>`_"""
    ...
def hook_print(buffer, tags, message, strip_colors, callback, callback_data):
    """`hook_print in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_print>`_"""
    ...
def hook_signal(signal, callback, callback_data):
    """`hook_signal in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_signal>`_"""
    ...
def hook_signal_send(signal, type_data, signal_data):
    """`hook_signal_send in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_signal_send>`_"""
    ...
def hook_hsignal(signal, callback, callback_data):
    """`hook_hsignal in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_hsignal>`_"""
    ...
def hook_hsignal_send(signal, hashtable):
    """`hook_hsignal_send in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_hsignal_send>`_"""
    ...
def hook_config(option, callback, callback_data):
    """`hook_config in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_config>`_"""
    ...
def hook_modifier(modifier, callback, callback_data):
    """`hook_modifier in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_modifier>`_"""
    ...
def hook_modifier_exec(modifier, modifier_data, string):
    """`hook_modifier_exec in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_modifier_exec>`_"""
    ...
def hook_info(info_name, description, args_description, callback, callback_data):
    """`hook_info in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_info>`_"""
    ...
def hook_info_hashtable(info_name, description, args_description, output_description, callback, callback_data):
    """`hook_info_hashtable in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_info_hashtable>`_"""
    ...
def hook_infolist(infolist_name, description, pointer_description, args_description, callback, callback_data):
    """`hook_infolist in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_infolist>`_"""
    ...
def hook_focus(area, callback, callback_data):
    """`hook_focus in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_focus>`_"""
    ...
def hook_set(hook, property, value):
    """`hook_set in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hook_set>`_"""
    ...
def unhook(hook):
    """`unhook in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_unhook>`_"""
    ...
def unhook_all():
    """`unhook_all in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_unhook_all>`_"""
    ...
def buffer_new(name, input_callback, input_callback_data, close_callback, close_callback_data):
    """`buffer_new in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_buffer_new>`_"""
    ...
def current_buffer():
    """`current_buffer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_current_buffer>`_"""
    ...
def buffer_search(plugin, name):
    """`buffer_search in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_buffer_search>`_"""
    ...
def buffer_search_main():
    """`buffer_search_main in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_buffer_search_main>`_"""
    ...
def buffer_clear(buffer):
    """`buffer_clear in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_buffer_clear>`_"""
    ...
def buffer_close(buffer):
    """`buffer_close in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_buffer_close>`_"""
    ...
def buffer_merge(buffer, target_buffer):
    """`buffer_merge in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_buffer_merge>`_"""
    ...
def buffer_unmerge(buffer, number):
    """`buffer_unmerge in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_buffer_unmerge>`_"""
    ...
def buffer_get_integer(buffer, property):
    """`buffer_get_integer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_buffer_get_integer>`_"""
    ...
def buffer_get_string(buffer, property):
    """`buffer_get_string in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_buffer_get_string>`_"""
    ...
def buffer_get_pointer(buffer, property):
    """`buffer_get_pointer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_buffer_get_pointer>`_"""
    ...
def buffer_set(buffer, property, value):
    """`buffer_set in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_buffer_set>`_"""
    ...
def buffer_string_replace_local_var(buffer, string):
    """`buffer_string_replace_local_var in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_buffer_string_replace_local_var>`_"""
    ...
def buffer_match_list(buffer, string):
    """`buffer_match_list in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_buffer_match_list>`_"""
    ...
def current_window():
    """`current_window in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_current_window>`_"""
    ...
def window_search_with_buffer(buffer):
    """`window_search_with_buffer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_window_search_with_buffer>`_"""
    ...
def window_get_integer(window, property):
    """`window_get_integer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_window_get_integer>`_"""
    ...
def window_get_string(window, property):
    """`window_get_string in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_window_get_string>`_"""
    ...
def window_get_pointer(window, property):
    """`window_get_pointer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_window_get_pointer>`_"""
    ...
def window_set_title(window, title):
    """`window_set_title in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_window_set_title>`_"""
    ...
def nicklist_add_group(buffer, parent_group, name, color, visible):
    """`nicklist_add_group in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_nicklist_add_group>`_"""
    ...
def nicklist_search_group(buffer, from_group, name):
    """`nicklist_search_group in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_nicklist_search_group>`_"""
    ...
def nicklist_add_nick(buffer, group, name, color, prefix, prefix_color, visible):
    """`nicklist_add_nick in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_nicklist_add_nick>`_"""
    ...
def nicklist_search_nick(buffer, from_group, name):
    """`nicklist_search_nick in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_nicklist_search_nick>`_"""
    ...
def nicklist_remove_group(buffer, group):
    """`nicklist_remove_group in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_nicklist_remove_group>`_"""
    ...
def nicklist_remove_nick(buffer, nick):
    """`nicklist_remove_nick in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_nicklist_remove_nick>`_"""
    ...
def nicklist_remove_all(buffer):
    """`nicklist_remove_all in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_nicklist_remove_all>`_"""
    ...
def nicklist_group_get_integer(buffer, group, property):
    """`nicklist_group_get_integer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_nicklist_group_get_integer>`_"""
    ...
def nicklist_group_get_string(buffer, group, property):
    """`nicklist_group_get_string in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_nicklist_group_get_string>`_"""
    ...
def nicklist_group_get_pointer(buffer, group, property):
    """`nicklist_group_get_pointer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_nicklist_group_get_pointer>`_"""
    ...
def nicklist_group_set(buffer, group, property, value):
    """`nicklist_group_set in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_nicklist_group_set>`_"""
    ...
def nicklist_nick_get_integer(buffer, nick, property):
    """`nicklist_nick_get_integer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_nicklist_nick_get_integer>`_"""
    ...
def nicklist_nick_get_string(buffer, nick, property):
    """`nicklist_nick_get_string in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_nicklist_nick_get_string>`_"""
    ...
def nicklist_nick_get_pointer(buffer, nick, property):
    """`nicklist_nick_get_pointer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_nicklist_nick_get_pointer>`_"""
    ...
def nicklist_nick_set(buffer, nick, property, value):
    """`nicklist_nick_set in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_nicklist_nick_set>`_"""
    ...
def bar_item_search(name):
    """`bar_item_search in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_bar_item_search>`_"""
    ...
def bar_item_new(name, build_callback, build_callback_data):
    """`bar_item_new in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_bar_item_new>`_"""
    ...
def bar_item_update(name):
    """`bar_item_update in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_bar_item_update>`_"""
    ...
def bar_item_remove(item):
    """`bar_item_remove in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_bar_item_remove>`_"""
    ...
def bar_search(name):
    """`bar_search in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_bar_search>`_"""
    ...
def bar_new(name, hidden, priority, type, condition, position, filling_top_bottom, filling_left_right, size, size_max, color_fg, color_delim, color_bg, separator, items):
    """`bar_new in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_bar_new>`_"""
    ...
def bar_set(bar, property, value):
    """`bar_set in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_bar_set>`_"""
    ...
def bar_update(name):
    """`bar_update in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_bar_update>`_"""
    ...
def bar_remove(bar):
    """`bar_remove in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_bar_remove>`_"""
    ...
def command(buffer, command):
    """`command in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_command>`_"""
    ...
def command_options(buffer, command, options):
    """`command_options in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_command_options>`_"""
    ...
def info_get(info_name, arguments):
    """`info_get in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_info_get>`_"""
    ...
def info_get_hashtable(info_name, dict_in):
    """`info_get_hashtable in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_info_get_hashtable>`_"""
    ...
def infolist_new():
    """`infolist_new in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_new>`_"""
    ...
def infolist_new_item(infolist):
    """`infolist_new_item in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_new_item>`_"""
    ...
def infolist_new_var_integer(item, name, value):
    """`infolist_new_var_integer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_new_var_integer>`_"""
    ...
def infolist_new_var_string(item, name, value):
    """`infolist_new_var_string in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_new_var_string>`_"""
    ...
def infolist_new_var_pointer(item, name, pointer):
    """`infolist_new_var_pointer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_new_var_pointer>`_"""
    ...
def infolist_new_var_time(item, name, time):
    """`infolist_new_var_time in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_new_var_time>`_"""
    ...
def infolist_get(infolist_name, pointer, arguments):
    """`infolist_get in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_get>`_"""
    ...
def infolist_next(infolist):
    """`infolist_next in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_next>`_"""
    ...
def infolist_prev(infolist):
    """`infolist_prev in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_prev>`_"""
    ...
def infolist_reset_item_cursor(infolist):
    """`infolist_reset_item_cursor in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_reset_item_cursor>`_"""
    ...
def infolist_search_var(infolist, name):
    """`infolist_search_var in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_search_var>`_"""
    ...
def infolist_fields(infolist):
    """`infolist_fields in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_fields>`_"""
    ...
def infolist_integer(infolist, var):
    """`infolist_integer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_integer>`_"""
    ...
def infolist_string(infolist, var):
    """`infolist_string in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_string>`_"""
    ...
def infolist_pointer(infolist, var):
    """`infolist_pointer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_pointer>`_"""
    ...
def infolist_time(infolist, var):
    """`infolist_time in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_time>`_"""
    ...
def infolist_free(infolist):
    """`infolist_free in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_free>`_"""
    ...
def hdata_get(hdata_name):
    """`hdata_get in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_get>`_"""
    ...
def hdata_get_var_offset(hdata, name):
    """`hdata_get_var_offset in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_get_var_offset>`_"""
    ...
def hdata_get_var_type_string(hdata, name):
    """`hdata_get_var_type_string in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_get_var_type_string>`_"""
    ...
def hdata_get_var_array_size(hdata, pointer, name):
    """`hdata_get_var_array_size in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_get_var_array_size>`_"""
    ...
def hdata_get_var_array_size_string(hdata, pointer, name):
    """`hdata_get_var_array_size_string in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_get_var_array_size_string>`_"""
    ...
def hdata_get_var_hdata(hdata, name):
    """`hdata_get_var_hdata in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_get_var_hdata>`_"""
    ...
def hdata_get_list(hdata, name):
    """`hdata_get_list in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_get_list>`_"""
    ...
def hdata_check_pointer(hdata, list, pointer):
    """`hdata_check_pointer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_check_pointer>`_"""
    ...
def hdata_move(hdata, pointer, count):
    """`hdata_move in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_move>`_"""
    ...
def hdata_search(hdata, pointer, search, count):
    """`hdata_search in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_search>`_"""
    ...
def hdata_char(hdata, pointer, name):
    """`hdata_char in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_char>`_"""
    ...
def hdata_integer(hdata, pointer, name):
    """`hdata_integer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_integer>`_"""
    ...
def hdata_long(hdata, pointer, name):
    """`hdata_long in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_long>`_"""
    ...
def hdata_string(hdata, pointer, name):
    """`hdata_string in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_string>`_"""
    ...
def hdata_pointer(hdata, pointer, name):
    """`hdata_pointer in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_pointer>`_"""
    ...
def hdata_time(hdata, pointer, name):
    """`hdata_time in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_time>`_"""
    ...
def hdata_hashtable(hdata, pointer, name):
    """`hdata_hashtable in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_hashtable>`_"""
    ...
def hdata_compare(hdata, pointer1, pointer2, name, case_sensitive):
    """`hdata_compare in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_compare>`_"""
    ...
def hdata_update(hdata, pointer, hashtable):
    """`hdata_update in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_update>`_"""
    ...
def hdata_get_string(hdata, property):
    """`hdata_get_string in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_get_string>`_"""
    ...
def upgrade_new(filename, callback_read, callback_read_data):
    """`upgrade_new in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_upgrade_new>`_"""
    ...
def upgrade_write_object(upgrade_file, object_id, infolist):
    """`upgrade_write_object in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_upgrade_write_object>`_"""
    ...
def upgrade_read(upgrade_file):
    """`upgrade_read in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_upgrade_read>`_"""
    ...
def upgrade_close(upgrade_file):
    """`upgrade_close in WeeChat plugin API reference <https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_upgrade_close>`_"""
    ...
