= WeeChat テスターガイド
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: ja
:toc: left
:toc-title: 目次
:sectnums:
:docinfo1:


翻訳者:

* Ryuunosuke Ayanokouzi <i38w7i3@yahoo.co.jp>, 2012-2017


[[purpose]]
== 目的

WeeChat
開発への協力に興味を持っていただきありがとうございます。開発に協力する最も簡単
(で最も大変) な方法はテストです!

テストはソフトウェア開発においてとても重要で、疎かにできないものです。何か新しい機能が実装されたらその機能はテストされるべきです。しかし、機能によっては使用条件が広すぎるか使用条件が特殊過ぎるため、開発チームが全ての条件をテストできない場合があります。

例: WeeChat 0.2.2 で導入された charset プラグインは悪名高いものでした:
開発チームにはチャンネル名に各国語を使うユーザー
(開発者、貢献者、テスター)
がいなかったため、0.2.2
がリリースされると、チームを非難するロシア人ユーザが殺到しました。より多くのテスターがいれば、今後そのようなことはおきないでしょう。

開発者は新機能の実装 (と古いバグの修正) に忙しいので、WeeChat
安定版をテストすることは意味がありません。


[[prepare_system]]
== システムの準備

Linux の _core_ ファイルを有効にすることはとても役に立ちます: WeeChat
がクラッシュすると、Linux は _core_ と呼ばれるファイルを作ります。このファイルには、WeeChat
に問題の有る箇所を正確に示す、とても役立つデバッグ情報が含まれています。

_bash_ シェルを使っている場合、以下の行を _~/.bashrc_ に追記してください:

----
ulimit -c unlimited
----


[[download]]
== 開発版のダウンロード

最新のコード (最新のバグと最新の機能も含んでいますが) は GIT リポジトリにあります。

手作業で最新のコードをビルドすることができます (推奨):

* GIT 版は安定版と共存してビルド、インストールできます。
* root 権限は必要ありません、WeeChat
  安定版を捨てる必要もありません。

[[get_sources]]
=== ソースの取得とビルド

最初にディレクトリを作ってください、ここでは _weechat-git_:

----
$ mkdir ~/weechat-git
$ cd ~/weechat-git
----

git がインストール済みの場合、git
リポジトリを clone してください (推奨):

----
$ git clone https://github.com/weechat/weechat.git
$ cd weechat
----

[NOTE]
clone の後、このディレクトリ内で `git pull`
を実行すれば、最新のアップデートとの差分が更新されます。

他の方法として _devel_ パッケージをダウンロードして展開する方法があります:

----
$ wget https://weechat.org/files/src/weechat-devel.tar.bz2
$ tar xvjf weechat-devel.tar.bz2
$ cd weechat-devel
----

ソースをビルドするには cmake を使うことを推奨します:

----
$ mkdir build
$ cd build
$ cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/weechat-git -DWEECHAT_HOME=~/.weechat-dev -DCMAKE_BUILD_TYPE=Debug
$ make
$ make install
----

cmake が無い場合は autotools を使うことも可能です:

----
$ ./autogen.sh
$ ./configure --prefix=$HOME/weechat-git WEECHAT_HOME=~/.weechat-dev
$ make
$ make install
----

[[install_binary_package]]
=== バイナリパッケージのインストール

Linux ディストリビューション別に:

* Debian: https://weechat.org/download/debian
* Gentoo: https://weechat.org/download
* ArchLinux: http://aur.archlinux.org/ から PKGBUILD
* その他: 知らないよ! てへぺろ(・ω<)


[[run]]
== WeeChat の実行

コマンド:

----
$ ~/weechat-git/bin/weechat
----

より万全を期すなら、上の方法を使って WeeChat
の最新バージョンを使っていることを確認するべきです ;)

おかしな (問題を引き起こしたり、クラッシュしたり、あなたを怒らせるような) 挙動を見つけたら
_chat.freenode.net_ の _#weechat_ に参加して、開発チームにこの挙動を教えてください。

クラッシュしなかったとしても教えてください。開発チームはあなたからのフィードバックをお待ちしています!
