= WeeChat クイックスタートガイド
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:toc2:
:toc-title: 目次
:max-width: 100%


翻訳者:

* Ryuunosuke Ayanokouzi <i38w7i3@yahoo.co.jp>, 2009-2016


[[start]]
== WeeChat を起動

X 用ターミナルエミュレータは rxvt-unicode を推奨します (UTF-8
がサポートされており、デフォルトのキーバインドで問題が発生しないためです)。

シェルから起動するには:

----
$ weechat
----

[[help_options]]
== オンラインヘルプ / オプション

WeeChat はすべてのコマンドにヘルプがあります。ヘルプを見るには、以下のコマンドを入力してください:

----
/help
----

特定のコマンドに対するヘルプを見るには、以下のコマンドを入力してください:

----
/help command
----

オプションを設定するには以下のコマンドを入力してください:

----
/set config.section.option value
----

(ここで `config` は設定名 (core の場合は
`weechat` もしくはプラグイン名)、`section`
はこの設定のセクション、`option` はオプション名)。

オプション設定はすぐに反映されます (設定変更後に
WeeChat を再起動する必要は*ありません*)。

`/set` オプションはすべての指定された文字を含むオプションを表示するために部分一致指定や先頭や最後にワイルドカード
"*" を指定することができます。
例:

* 全ての設定名を表示します (WeeChat およびプラグイン)

----
/set
----

* WeeChat のオプションを表示します

----
/set weechat.*
----

* IRC プラグインのオプションを表示します

----
/set irc.*
----

`/help` とオプション名を指定することでヘルプを表示できます、例:

----
/help weechat.look.highlight
----

すべての設定は WeeChat の終了時 (または強制的に設定保存を行う
`/save` コマンドを使用した場合) に保存されます。

`/set` コマンド以外の設定方法として、設定ファイル (*.conf)
を直接修正し、`/reload` コマンドで再読込することもできます。

[[core_vs_plugins]]
== コア vs プラグイン

WeeChat の "core" にはユーザインタフェースに関わるものだけが含まれているため、
プラグインがなければ使い物になりません (以前からのユーザーへ: IRC
関連はバージョン 0.2.6 までコアに含まれていました)。

IRC 等全てのネットワークプロトコルはそれぞれ異なるプラグインで提供しています。

`/plugin` コマンドで読み込まれているプラグイン一覧を表示できます。"irc"
やその他のプラグインはここから確認してください。

[[add_irc_server]]
== IRC サーバを追加する

IRC サーバを追加するには `/server` コマンドを使ってください、例:

----
/server add freenode chat.freenode.net
----

書式が思い出せない場合はヘルプを利用してください:

----
/help server
----

[[irc_server_options]]
== IRC サーバのオプションを設定する

もしサーバオプションが特に設定されていない場合、WeeChat
はデフォルト設定をすべてのサーバに適用します
(フォールバック方式)。これらのデフォルト設定は "irc.server_default.*" です。

サーバオプションが定義されていれば ("null" でなければ) それを使用します。定義されていなければ、WeeChat
はデフォルト設定を使用します ("irc.server_default.xxx")。

例えばデフォルトでは (un*x ログイン名をベースにした)
ニックネームが設定されますが、以下のコマンドで freenode サーバ用の設定として上書きすることが可能です:

----
/set irc.server.freenode.nicks "mynick,mynick2,mynick3,mynick4,mynick5"
----

ユーザ名と実名を設定する場合:

----
/set irc.server.freenode.username "My user name"
/set irc.server.freenode.realname "My real name"
----

サーバへの自動接続を設定する場合:

----
/set irc.server.freenode.autoconnect on
----

SSL を使って接続する場合:

----
/set irc.server.freenode.addresses "chat.freenode.net/7000"
/set irc.server.freenode.ssl on
----

サーバで SASL を利用可能な場合、SASL を利用してニックネーム認証することができます
(チャンネル参加前にニックネーム認証が行われるでしょう):

----
/set irc.server.freenode.sasl_username "mynick"
/set irc.server.freenode.sasl_password "xxxxxxx"
----

例えば nickserv との認証などを行うためにサーバ接続後にコマンドを実行するには
(SASL を利用して認証を行わない場合):

----
/set irc.server.freenode.command "/msg nickserv identify xxxxxxx"
----

[NOTE]
'command' オプションに複数のコマンドを含める場合は ';' (セミコロン) で区切ってください。

設定ファイル内にパスワードを直接書きたくない場合、保護データを使うことが可能です。

最初にパスフレーズを登録します:

----
/secure passphrase this is my secret passphrase
----

その後に freenode のパスワードを含む保護データを追加します:

----
/secure set freenode_password xxxxxxx
----

こうすることで前述したようにパスワードを IRC オプションに直接書くのではなく
 `${sec.data.freenode_password}` を指定可能になります。例えば以下のように設定します:

----
/set irc.server.freenode.sasl_password "${sec.data.freenode_password}"
----

チャンネルへの自動参加を設定する場合:

----
/set irc.server.freenode.autojoin "#channel1,#channel2"
----

サーバオプションの代わりにデフォルトの値を使用する、例えばデフォルトのニックネーム
(irc.server_default.nicks) を使用する場合:

----
/set irc.server.freenode.nicks null
----

その他設定: その他のオプションも以下のコマンドで設定できます
("xxx" は設定名です):

----
/set irc.server.freenode.xxx value
----

[[connect_to_irc_server]]
== サーバに接続し、チャンネルに自動接続する

----
/connect freenode
----

[NOTE]
このコマンドは、`/server`
を使わずに新しいサーバの作成および接続ができます (`/help connect`
でこのコマンドのヘルプを確認することができます)。

デフォルトでは、サーババッファは Weechat の 'core' バッファとマージされます。'core'
バッファとサーババッファ間で切り替えたい場合は、key[ctrl-x] が使用できます。

サーババッファへの自動マージを無効にして
独立したサーババッファにすることができます:

----
/set irc.look.server_buffer independent
----

[[join_part_irc_channels]]
== チャンネルに接続 / 切断する

チャンネルに接続する

----
/join #channel
----

チャンネルから切断する (バッファは開いたままにする)

----
/part [切断メッセージ]
----

// TRANSLATION MISSING
Close a server, channel or private buffer (`/close` is an alias for
`/buffer close`):

----
/close
----

// TRANSLATION MISSING
[WARNING]
Closing the server buffer will close all channel/private buffers.

// TRANSLATION MISSING
Disconnect from server, on the server buffer:

----
/disconnect
----

[[irc_private_messages]]
== IRC プライベートメッセージ

バッファを開いてメッセージを他のユーザ (ニックネーム 'foo') 宛に送信する:

----
/query foo this is a message
----

プライベートバッファを閉じる:

----
/close
----

[[buffer_window]]
== バッファ / ウィンドウ管理

バッファは番号、カテゴリおよび名前とともにプラグインに関連づけられたあるコンポーネントです。
バッファは画面に表示するデータを含んでいます。

ウィンドウはバッファを表示するためにあります。デフォルトでは、1
つのウィンドウは 1 つのバッファだけを表示できます。画面を分割することで、
同時に複数のウィンドウと関連するバッファを見ることができるでしょう。

バッファ / ウィンドウを管理するためのコマンド:

----
/buffer
/window
----

(言うまでもありませんが /help でこれらのコマンドもヘルプを確認することができます)

例えば、ウィンドウを垂直方向に小さいウィンドウ (1/3 幅) と大きいウィンドウ
(2/3 幅) に分割する場合は次のコマンドを実行します:

----
/window splitv 33
----

[[key_bindings]]
== キー割り当て設定

WeeChat はデフォルトでたくさんのショートカットキーが設定されています。
これらはドキュメントに記載されていますが、いくつか重要なキーがあります:

- key[alt-]key[←]/key[→] または key[F5]/key[F6]: 前後のバッファに切り替える
- key[F7]/key[F8]: 前後のウィンドウに切り替える(画面分割時)
- key[F9]/key[F10]: タイトルバーをスクロール表示
- key[F11]/key[F12]: ニックネーム一覧をスクロール表示
- key[Tab]: 入力バーでシェルと同様のテキスト補完を行う
- key[PgUp]/key[PgDn]: 現在のバッファのテキストをスクロール表示
- key[alt-a]: (ホットリスト内の) アクティブなバッファに移動する

必要であれば、`/key`
コマンドでショートカットキーの割り当てを変更することができます。
キーコードを調べるには、key[alt-k] が役に立つでしょう。

例えば、key[alt-!] に `/buffer close` を割り当てる場合:

----
/key bind (alt-kを押下) (alt-!を押下) /buffer close
----

コマンドラインには以下のように表示されます:

----
/key bind meta-! /buffer close
----

キー割り当てを解除する場合:

----
/key unbind meta-!
----

[[plugins_scripts]]
== プラグイン / スクリプト

Debian のようにいくつかのディストリビューションでは、プラグイン用パッケージが独立して用意されています
(例えば weechat-plugins)。
見つかったプラグインは自動的に読み込まれます (プラグイン /
スクリプトの読み込み、有効 / 無効は WeeChat のドキュメントを参照してください)。

WeeChat では多くの外部スクリプト (貢献者の作った)
を利用できます、スクリプトをリポジトリからダウンロードしてインストールするには、`/script`
コマンドを使ってください、例:

----
/script install iset.pl
----

より詳しい情報を参照するには `/help script` を使ってください。

スクリプトの一覧を参照するには WeeChat から `/script` を実行するか、以下の URL にアクセスしてください:
https://weechat.org/scripts

[[more_doc]]
== 詳しいドキュメント情報

FAQ やその他の質問に関するドキュメントはこちらで参照できます:
https://weechat.org/doc

WeeChat を楽しんでください!
