= weechat(1)
:doctype: manpage
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: ja
:man manual: WeeChat マニュアル
:man source: WeeChat {revnumber}

== 名前

weechat - 拡張可能なチャットクライアント

== 書式

[verse]
*weechat* [-a|--no-connect] [-d|--dir <path>] [-p|--no-plugin] [-r|--run-command <command>] [-s|--no-script] [--upgrade] [plugin:option...]
*weechat* [-c|--colors]
*weechat* [-h|--help]
*weechat* [-l|--license]
*weechat* [-v|--version]

== 説明

WeeChat (Wee Enhanced Environment for Chat) はフリーのチャットクライアントです。
高速で軽量、多くのオペレーティングシステムで動くように設計されています。
スクリプトを使って高度にカスタマイズと拡張可能です。

== オプション

include::cmdline_options.ja.adoc[]

== プラグインオプション

プラグインオプションに関する完全な文書は
https://weechat.org/doc[WeeChat ユーザーズガイド] のプラグインの章を参照してください。

irc プラグインでは以下の様な URL で一時的なサーバに接続することができます:

    irc[6][s]://[[nickname][:password]@]server[:port][/#channel1[,#channel2...]]

"mynick" というニックネームで WeeChat IRC チャンネルサポートに参加するには:

    irc://mynick@chat.freenode.net/#weechat

IPv6 アドレスの後にポートを指定するには IPv6
アドレスを括弧に入れてください、例えば:

    irc://mynick@[2001:db8:0:85a3::ac1f:8001]:6668/#test

== ファイル

$HOME/.weechat/weechat.conf::
    WeeChat の主要設定ファイル

$HOME/.weechat/plugins.conf::
    プラグイン設定ファイル

$HOME/.weechat/sec.conf::
    保護されたデータを含む設定ファイル

$HOME/.weechat/alias.conf::
    _alias_ プラグイン用の設定ファイル

$HOME/.weechat/aspell.conf::
    _aspell_ プラグイン用の設定ファイル

$HOME/.weechat/charset.conf::
    _charset_ プラグイン用の設定ファイル

$HOME/.weechat/exec.conf::
    _exec_ プラグイン用の設定ファイル

$HOME/.weechat/irc.conf::
    _irc_ プラグイン用の設定ファイル

$HOME/.weechat/logger.conf::
    _logger_ プラグイン用の設定ファイル

$HOME/.weechat/relay.conf::
    _relay_ プラグイン用の設定ファイル

$HOME/.weechat/script.conf::
    _script_ プラグイン用の設定ファイル

$HOME/.weechat/trigger.conf::
    _trigger_ プラグイン用の設定ファイル

$HOME/.weechat/xfer.conf::
    _xfer_ プラグイン用の設定ファイル

$HOME/.weechat/weechat.log::
    WeeChat ログファイル

== 著者

この manpage を書いたのは {author} さんです。

翻訳したのは Ryuunosuke Ayanokouzi さんです。

== 著作権

WeeChat は Sébastien Helleu さんと貢献者によって作成されています
(完全なリストは AUTHORS.adoc ファイルを参照してください)。

著作権 (C) 2003-2016 {author}

WeeChat はフリーソフトウェアです。あなたはこれを、フリーソフトウェア財団によって発行された
GNU 一般公衆利用許諾契約書 (バージョン 2 か、希望によってはそれ以降のバージョンのうちどれか)
の定める条件の下で再頒布または改変することができます。

より詳しい情報は COPYING ファイルを読んでください。

Web: https://weechat.org/

== サポート / バグ報告

手助けを受けたりバグを報告するには: https://weechat.org/dev/support
